### ISSUE TITLE
'Collection' page icon 

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#1003]
Apologies if this was discussed already, but how do we feel about the icon?

<img width="110" alt="Screenshot 2023-02-08 at 16 46 13" src="https://user-images.githubusercontent.com/36884067/217595818-3aaa6089-83c5-4b90-b842-b9afb7783532.png">

It represents literally what the user is going to see on that page - a list. 

However, I wonder if it isn't more intuitive having the little 9 squares? IMO it conveys more the meaning of applications
<img width="34" alt="Screenshot 2023-02-08 at 16 48 07" src="https://user-images.githubusercontent.com/36884067/217596297-993addaa-d867-4dbe-be2f-aee005b9fe74.png">

Open to other suggestions!

**Comment by anasereijo** [comment]
@madsrh any particular thoughts or ideas for this?

**Comment by madsrh** [comment]
No thoughts 😅 Maybe this will be easier when we've settled on a name. Manage? 

I can't find it, but I believe @Jupi007 already suggested the grid icon.

**Comment by Jupi007** [comment]
Yes, I suggested this icon yesterday 🙂

**Comment by anasereijo** [comment]
Coming back to this :)
Maybe we shouldn't use the grid icon for the 'collection' page, as it's the same icon we use for 'all categories'.

I quite like this 🍎 solution
<img width="202" alt="Screenshot 2023-02-09 at 11 19 49" src="https://user-images.githubusercontent.com/36884067/217799611-b68df3b9-bed3-4ae4-8b8a-51555571f10a.png">
I know it's for the updates page, and here we combined both, but I think icon is also very standard for 'installed'.

thoughts?

**Comment by Jupi007** [comment]
Well, I have to disagree because an "update" icon will specifically have a semantic of "update" and not at all of "app gallery".
While an icon with a semantic meaning of "apps" will perfectly fit to the installed app gallery, and will also fit to the update view when a badge who indicate a number of updates is displayed.

**Comment by anasereijo** [comment]
> Well, I have to disagree because an "update" icon will specifically have a semantic of "update" and not at all of "app gallery". While an icon with a semantic meaning of "apps" will perfectly fit to the installed app gallery, and will also fit to the update view when a badge who indicate a number of updates is displayed.

Which icon would you think would be better for this page, then?

**Comment by Feichtmeier** [comment]
I have a neutral/no opinion on the icon and the name! You need to :boxing_glove: discuss this between each other :smile_cat: 

![grafik](https://user-images.githubusercontent.com/15329494/217844730-465dbcec-2652-4811-b862-67754e0ff851.png)
![grafik](https://user-images.githubusercontent.com/15329494/217845131-bb775f8d-1ea1-4b33-9c20-41592caae3d3.png)

**Comment by Jupi007** [comment]
@anasereijo  Honestly, I don't think it is problematic to use the `app_grid` icon in two places, as long as it is not in the same part of the ui.
Here we would use it in the navbar and in the category selection dropdown (which is hidden 99% of the time).

But if you think it is very problematic, I personally think that `app_grid` fits better in the sidebar to show "all installed app", than in the dropdown where it means "all categories". So maybe should we find an icon for "all categories"?

**Comment by Feichtmeier** [comment]
oh I have forgotten this. then I actually have a mini opinion: if we go with the app grid, we should change the "all"-icon.

**Comment by Feichtmeier** [comment]
one more suggestion
![grafik](https://user-images.githubusercontent.com/15329494/217855954-4b160072-7e3d-403b-bd97-01f25d71949c.png)

**Comment by anasereijo** [comment]
That's exactly my concern – having the same icon for 2 different purposes. Even if '99%' of the time, users won't see both at the same time, doesn't mean that the user won't recall that same icon for 'collection' page. There's also the issue of when, on small windows, the side-nav hides the labels when we have just the icons.

soooo, yeah, we could have something different for categories? what about 'A' store icon?
<img width="69" alt="Screenshot 2023-02-09 at 15 25 25" src="https://user-images.githubusercontent.com/36884067/217856231-ff3f4bd8-d6cc-4f26-8471-36e95da1d88c.png">

**Comment by anasereijo** [comment]
@Feichtmeier ah, missed your suggestion! that could be an option!

**Comment by Feichtmeier** [comment]
So app grid it is?

**Comment by anasereijo** [comment]
> So app grid it is?

App grid for 'collections' and A for categories. I will create a separate issue for that. 👍

**Comment by Feichtmeier** [comment]
Fixed with #1010
