### ISSUE TITLE
New icon for 'All categories'

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#1008]
what about 'A' store icon?
<img width="69" alt="Screenshot 2023-02-09 at 15 25 25" src="https://user-images.githubusercontent.com/36884067/217856231-ff3f4bd8-d6cc-4f26-8471-36e95da1d88c.png">

_Originally posted by @anasereijo in https://github.com/ubuntu-flutter-community/software/issues/1003#issuecomment-1424370580_

**Comment by Jupi007** [comment]
Just noticed this was the "app update" icon (there's a progressbar inside it).
I'll add one without, and name it simply "app".

**Comment by anasereijo** [comment]
> Just noticed this was the "app update" icon (there's a progressbar inside it). I'll add one without, and name it simply "app".

Interesting! Does it mean that the icon is used to convey update elsewhere?

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/217896731-d04a4779-4220-4792-bb83-d3a400c8690b.png)
 Yes, the two update & update settings apps in Ubuntu plus a third one if you have snap-store from stable

**Comment by anasereijo** [comment]
> ![image](https://user-images.githubusercontent.com/15329494/217896731-d04a4779-4220-4792-bb83-d3a400c8690b.png) Yes, the two update & update settings apps in Ubuntu plus a third one if you have snap-store from stable

Ah, I meant more UI-Icons, sorry for not being specific. 

But yeah, that's also a good point, even though we also use that A icon for the (old) store inside the bag. On the flutter store, we use the snap store one (but that's yet to be approved, I think).

I believe those might change at some point. 

I will try to get more info internally but, in the meantime, it's okay to proceed with this.

**Comment by Feichtmeier** [comment]
Maybe rather

![image](https://user-images.githubusercontent.com/15329494/217900870-d22b1f25-80ad-4ac1-a1f8-cf5f8ca8449d.png)

?

or just

![image](https://user-images.githubusercontent.com/15329494/217901726-ca29e4ef-ba28-4780-be0e-cdcef15ebdd3.png)

?

**Comment by Jupi007** [comment]
The snap icon fits well imo :+1:

**Comment by anasereijo** [comment]
@Feichtmeier the snap one also came to my mind, but the one with the shopping bag, to match the store icon. 
However, as I said, we might have to change the application icon, when a final decision is made about the name and also from a product strategy point of view.

**Comment by Feichtmeier** [comment]
ok!

**Comment by Feichtmeier** [comment]
ok then I wait for the icon changes before the new software release
