### ISSUE TITLE
Make publisher name click search for publisher

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#1016]
When clicking the publisher name, currently the users gets send to the app page. I would expect to be directed to the publishers page.

https://snapcraft.io/publisher/kde
_not_
https://snapcraft.io/kdenlive

I tried to fix this, but couldn't find the correct string in `app_data`? 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/3986894/217961229-424a69bf-e1cf-47c6-b3d1-b603d123317f.png)

**Comment by whiskeyPeak** [comment]
We can get the unique username from ```context.watch<SnapModel>().publisher.username``` and then add that id to the website string. :D

Should pressing the application name direct to the snapcraft application webpage?

**Comment by madsrh** [comment]
> We can get the unique username from context.watch<SnapModel>().publisher.username and then add that id to the website string. :D

I'm not sure how to do that 😁 Feel free to create a PR. I tried this hacky solution: 👎 

`website: 'https://snapcraft.io/publisher/' + context.read<SnapModel>().publisher!.username,`

> Should pressing the application name direct to the snapcraft application webpage?

I had the same thought, but I really don't think so - would be a bit too much IMHO.

**Comment by Nightmayr** [comment]
I personally think with this, as a user if I click the publisher name I'd expect to see all apps published under that publisher in the snap-store app rather than be redirected to an external website.

**Comment by madsrh** [comment]
> I personally think with this, as a user if I click the publisher name I'd expect to see all apps published under that publisher in the snap-store app rather than be redirected to an external website.

Absolutely! That would be a much better experience. Can we do that @Feichtmeier ?

**Comment by Feichtmeier** [comment]
> > I personally think with this, as a user if I click the publisher name I'd expect to see all apps published under that publisher in the snap-store app rather than be redirected to an external website.
> 
> Absolutely! That would be a much better experience. Can we do that @Feichtmeier ?

If the snap serves respond correctly yes. Eventually this needs a change in snapd.dart

**Comment by d-loose** [comment]
This works on snapcraft.io, e.g.: https://snapcraft.io/search?q=publisher%3Acanonical, but it seems like the [snapd API](https://snapcraft.io/docs/snapd-api#heading--find) doesn't support such queries (see https://github.com/ubuntu-flutter-community/software/issues/863#issuecomment-1406754838)

**Comment by d-loose** [comment]
I wonder if we could just send a request to the [snapstore API](https://api.snapcraft.io/docs/search.html#snaps_find) directly

**Comment by Feichtmeier** [comment]
> I wonder if we could just send a request to the [snapstore API](https://api.snapcraft.io/docs/search.html#snaps_find) directly

No why? Let's better put this into snaps.dart

**Comment by d-loose** [comment]
> > I wonder if we could just send a request to the [snapstore API](https://api.snapcraft.io/docs/search.html#snaps_find) directly
> 
> No why? Let's better put this into snaps.dart

If you mean snapd.dart: no, that's strictly for the snapd API. We'd need a separate dart library that exposes the snapstore API.

**Comment by Feichtmeier** [comment]
Hm IMO then this should be made available as a query and then ported to snapd.dart

That would feel the most intuitive for me to use something like

SnapDClient.findSnapsByPublisher(name: 'snapcrafters');

**Comment by Feichtmeier** [comment]
Search for:

- muq
- ken
- canonical
- keshav (but not his full name keshavbhatt
