### ISSUE TITLE
Minimum window size can be changed to a size lower than what it is set to in my_application.cc

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#1023]
My laptop has a screen resolution of 1920x1200, so by setting that as the minimum window size, the software centre app should theoretically cover the entire screen on my laptop. This isn't the case.

https://user-images.githubusercontent.com/73116038/218001910-7b605a2e-fb1e-4d1e-9bea-aecaabe5b320.mp4

**Comment by jpnurmi** [comment]
Upgrading to handy_window 0.3.0 should help:

- https://github.com/ubuntu-flutter-community/handy_window/issues/26

**Comment by jpnurmi** [comment]
Handy window is sneaky and steals some space around the window for drawing shadows and rounded corners. Therefore, a minimum size hint set for the underlying native GDK window includes the shadows. It's not super intuitive but if we need an accurate minimum size, we need to take the shadows into account... :(
