### ISSUE TITLE
Collection page: show badge on app format selector

### ISSUE THREAD

**Issue by Jupi007** [ubuntu-flutter-community/software#1026]
For example in the latter screenshot, there's a (29) badge in the left pane, but only 1 snap update available.
Add a tiny badge to the package selector drop down would help the user to find the 29 available deb updates:

![image](https://user-images.githubusercontent.com/36476595/218063811-fd7cc6a3-cab2-4064-bdd9-7d472334ce72.png)

![Capture d’écran du 2023-02-10 11-04-56](https://user-images.githubusercontent.com/36476595/218063932-397e354d-0c34-4616-b12c-0912a21009d0.png)

Or:

![image](https://user-images.githubusercontent.com/36476595/218066916-67ee197f-46b2-4768-91d2-bdfb19f2e9db.png)

Sorry for the French 🙈

**Comment by Feichtmeier** [comment]
Very nice idea :+1: 

Dot first then badge with number is good :+1:
