### ISSUE TITLE
snap-store showing installed .deb as uninstalled in review section

### ISSUE THREAD

**Issue by raghavdhingra24** [ubuntu-flutter-community/software#1032]
Hi Flutter Snap Store Dev Team,
Recently I was going through the flutter snap-store and went to review section of a installed .deb app and it showed that the app was uninstalled. This issue was seen by me in pages of several installed .deb apps. Pages of snap apps are not affected.
Version - 0.2.8-alpha. 
Thanks

https://user-images.githubusercontent.com/106472154/218272424-2ee7f264-e5fc-4a11-b7e5-4ba618fe239b.mp4

**Comment by Feichtmeier** [comment]
Thanks! I think we just missed to display this correctly in this section down there
Thanks for the issue, def a bug :) :bug:
