### ISSUE TITLE
FAB colors have too high contrast

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#1037]
<img width="300px" src="https://user-images.githubusercontent.com/3986894/218342428-9c77afdb-43a5-4b21-a657-80e88e0525cb.png">

Nitpicking: @Feichtmeier is this inverse contrast is a bit too strong here? It sticks out a bit from the rest of the UI 🤷‍♂️ 

<img width="600px" src="https://user-images.githubusercontent.com/3986894/218340277-31cf0b94-e3df-46ee-9ad1-af819163a321.png">

Could we do something like this? This is using the same plain `Colors.gray` in both themes, but I think it needs a bit customizing for each theme. WDYT?

<img width="600px" src="https://user-images.githubusercontent.com/3986894/218340652-c0f6e6dc-9b18-4837-b6b3-218bd8741932.png">

An alternativ suggestion would be darker gray (dark theme) and white with a button border (light theme)

<img width="600px" src="https://user-images.githubusercontent.com/3986894/218342167-890f00ac-5998-4790-aeb1-8d132103389c.png">

**Comment by Feichtmeier** [comment]
I think it's fine
