### ISSUE TITLE
BannerAppHeader: avoid overflow by constraining title

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#1061]
![grafik](https://user-images.githubusercontent.com/15329494/218981030-f4f394c7-be0f-45d6-94ab-2643a5986125.png)

**Comment by madsrh** [comment]
I'm guessing this is a very rare issue? We should really encourage developers to give their app a name that is shorter than 75 characters 😄 So constraining the title is a great idea.

Would it have be possible to make the container height scale?
![Ikke-navngivet-1](https://user-images.githubusercontent.com/3986894/218984196-37169e75-47ae-47e1-bfdb-d15ee6cc404f.gif)

**Comment by Feichtmeier** [comment]
yes but then you get this jump effect when you come from the grid. I tried to align the header height to the second row of banners

good luck with encouraging 129412574582345 debian packages' maintainers ;)

**Comment by Feichtmeier** [comment]
we can just set maxLines = 1 and overFlow = ellipses
