### ISSUE TITLE
Store shows snap updates with up-to-date snaps

### ISSUE THREAD

**Issue by d-loose** [ubuntu-flutter-community/software#1062]
The update buttons don't do anything in this case though.

[Screencast from 2023-02-15 10-27-29.webm](https://user-images.githubusercontent.com/113362648/218988793-21027bf1-d5a5-441b-aebb-e9597f70fa72.webm)

**Comment by d-loose** [comment]
Some more insights on this:

![Screenshot from 2023-02-15 11-00-57](https://user-images.githubusercontent.com/113362648/218999671-29cde3ea-c076-4d0d-bd22-58a797e02370.png)

Tracking `latest/stable` should accept all `2.58.*` versions, but we're currently just checking if the versions differ to determine whether an update is available (https://github.com/ubuntu-flutter-community/software/blob/main/lib/app/common/snap/snap_utils.dart#L15)

**Comment by Feichtmeier** [comment]
That could become funny. Because I've found versions with the weirdest tags. There is sadly not rule or convention for snap versions

**Comment by Feichtmeier** [comment]
Do we have snap refresh --list in snapd.dart?

https://snapcraft.io/docs/keeping-snaps-up-to-date
