### ISSUE TITLE
Collection: track update amount and updating/installing progress also for snaps

### ISSUE THREAD

**Issue by local-optimum** [ubuntu-flutter-community/software#1066]
Edit: high-jacking this issue by @Feichtmeier 

TODO:

Collection: track update amount and updating/installing progress also for snaps in the in-app menu-entry badge/progress bar and the ubuntu dock badge/progress bar

![image](https://user-images.githubusercontent.com/55029393/219332749-6989740d-77bc-44f1-a34f-aedf3e87221d.png)

the following should also be shown for SNAPS (screenshot shows debs)
![Bildschirmfoto vom 2023-02-17 11-21-43](https://user-images.githubusercontent.com/15329494/219618657-4abca1dc-704d-4deb-ba70-b80b698ba081.png)

____________________

@local-optimum 's question:

Snap update counts don't appear in the notification above the collection icon, only deb updates.

In addition deb updates look to require a manual 'check for updates' to load. Potentially related to : https://github.com/ubuntu-flutter-community/software/issues/348

Can I get some clarity on the cadence of automatic update checking and intended functionality?

**Comment by Feichtmeier** [comment]
It was enabled long time ago but we found it too computation heavy. We could enable it on the view init but see this issues for Ken's plans on updates

#451
#348

I suggest before we put any more brain time here you should talk to Ken about the plans

**Comment by Feichtmeier** [comment]
> Can I get some clarity on the cadence of automatic update checking and intended functionality?

@local-optimum 
More clearer answer:

I planed to have all update functionalities related to ubuntu inside the app at first. I had a version where the app was never closed and only put into background state with an update timer running every 30 minutes. @kenvandine correctly suggested that this is a bad idea as long living processes can cause issues and said it would be better to make the whole update checking via a systemd service that invokes this app if there are updates. 
UNTIL this is all coded and ofc discussed I have no idea what the design should be. The ideal thing for the user is clear:

- One app to rule them all
- one app to find them
- One app to bring them all
- and in the darkness bind them

;)

**Comment by Feichtmeier** [comment]
> notification above the collection icon 

I guess you mean the badge?
This is indeed an issue we should fix
