### ISSUE TITLE
collection-page: can't open snaps

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#1076]
can't open apps from the collection page

[Screencast from 16-02-23 15_18_25.webm](https://user-images.githubusercontent.com/36884067/219408775-a3fe4195-951b-4b5c-b84a-b577e0a678be.webm)

**Comment by Feichtmeier** [comment]
Yes, see #209

It's a snap limitation where noone gives me an answer on
:/

**Comment by anasereijo** [comment]
> Yes, see #209
> 
> It's a snap limitation where noone gives me an answer on :/

:/ adding that to today's agenda!
