### ISSUE TITLE
Certain snaps not showing up in search results (Steam - Early Access)

### ISSUE THREAD

**Issue by local-optimum** [ubuntu-flutter-community/software#1079]
The current Steam snap does not appear in search results in the new Ubuntu Software app
- This is likely because it is only available via the beta channel
- This is unlikely to be an issue with snapd filtering as it is returned by running `snap find steam` in the CLI
- Have not personally confirmed, but it appears to be available in the current stable version of Ubuntu Software

We should be careful to ensure we are surfacing all snaps available via the `snap find` command.

**Comment by Feichtmeier** [comment]
@local-optimum fixed some hours before :) check #1077

**Comment by local-optimum** [comment]
Way ahead of me, sorry!
