### ISSUE TITLE
UpdatePage: switch appformat dropdown to toggle button

### ISSUE THREAD

**Issue by local-optimum** [ubuntu-flutter-community/software#1080]
As mentioned in the updates page thread but breaking out here for easier tracking. It has been identified through user surveys (and personal experience) that the drop down package select makes it difficult for users to find the debian packages or see debian updates easily without fiddling with the drop downs.

We already have an excellent solution on the app pages themselves:
![image](https://user-images.githubusercontent.com/55029393/219496246-f24386d6-c65f-4bcf-80b5-52d52047001f.png)

I propose that we change ALL snap/deb drop downs to use the same toggle approach as the above, as seen on:
- The search page
- The collection/manage page

And any future locations this might arise.

**Comment by Feichtmeier** [comment]
Oh generally I like this idea
However, you were all very happy about the unified search if Debian packages are available. So you need three states: all, only snaps or only debs. I think a drop-down fits better for the search?

**Comment by madsrh** [comment]
> ...So you need three states

Good point. A drop-down would be better than a three way toggle.

**Comment by anasereijo** [comment]
This will change the whole experience. I think we need to think carefully before changing everything to the toggle. We spent quite sometime thinking how we could merge and display both packages together. Things we need to evaluate: what are we trying to solve here? Is there an issue with the current drop-down? Also, Martin will provide us the user testing report soon, so I’d wait until then to see if there are any issues with it or not, and take it from there:
Thank you

**Comment by madsrh** [comment]
> It has been identified through user surveys (and personal experience) that the drop down package select makes it difficult for users to find the debian packages or see debian updates easily without fiddling with the drop downs.

I agree. It makes total sense to use the toggle on the update page (we had tabs earlier), BUT in places where multiple package formats can be selected (search), we should keep the dropdown.

![image](https://user-images.githubusercontent.com/3986894/221130668-5ff60c81-722a-4252-a4d6-499acd187001.png)
