### ISSUE TITLE
Some suggestions for visual and functional improvements to the Snap Store

### ISSUE THREAD

**Issue by matheucomth** [ubuntu-flutter-community/software#1109]
1-  The initial explore page does not have a lot of space, only featured applications are displayed. My suggestion would be to add categories (SOCIALS, GAMES, MEDIAS, MUSIC, VIDEO), just below a section of most downloaded applications and just below another section for recently updated applications
![Captura de tela de 2023-02-22 16-26-07](https://user-images.githubusercontent.com/33396386/220742405-0fcbd4f1-2c4a-4ebc-ba4d-0c0625b3b427.png)

2 - On the application page, there is the name of the developer, it would be interesting that when you click, it takes you to the page (within the snap store itself) of the developer showing all its published applications, as in the play store.
![Captura de tela de 2023-02-22 16-29-09](https://user-images.githubusercontent.com/33396386/220742717-9af71bb5-93f1-4094-85f9-39f72a3b2adc.png)

**Comment by Feichtmeier** [comment]
Hi @matheucomth 

thanks for your input

the second of your request is now live :) you can test it in preview/edge

For the explorepage rework there is a huge creative discussion here:

https://github.com/ubuntu-flutter-community/software/discussions/358

**Comment by madsrh** [comment]
Damn, you're fast @Feichtmeier 😆 

Thanks for the issue @matheucomth 

I'll close this issues and it is fixed/duplicate.

**Comment by matheucomth** [comment]
Thanks bros, congratulations for work
