### ISSUE TITLE
Loading images takes a long time

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#1116]
When viewing the **Games** category, the image banners takes a while to load. The frustrating thing is that if I click another category (eg. **Art & Design**) and then back to **Games**, it has to reload the images again. Although far from that obvious, the same is also somewhat true for icons.

Can we somehow cache these images? I would imagine that these won't change that dramatically over time, so having them stored the next time the app is launched would be useful.

I tried fiddling with the image quality, but I couldn't make that change anything for better or worse.

![image](https://user-images.githubusercontent.com/3986894/220973113-469e84b2-7474-4c97-9258-58cf9638b9c5.png)

**Comment by Feichtmeier** [comment]
Good idea

**Comment by dejvizelo** [comment]
I would like to work on this issue

**Comment by Feichtmeier** [comment]
Sure 😊
