### ISSUE TITLE
Allow cancelling ongoing snap changes

### ISSUE THREAD

**Issue by d-loose** [ubuntu-flutter-community/software#1131]
We should provide a way to cancel snap refreshes that are in progress (e.g. if downloading a snap takes longer than expected).

**Comment by madsrh** [comment]
Do you want a confirm dialog here or why did you tag UI here @d-loose ? 😊

**Comment by d-loose** [comment]
Yes sorry, I meant to add a sentence about that - the main question I have is: where do we put the 'cancel' button? Directly next to the loading spinner? Should it replace the 'update' button?
I'd also add a simple confirmation dialog, but that should be rather straightforward UI-wise :)

**Comment by Feichtmeier** [comment]
Now that you fixed the multi cancel auth issue, I would say that this is kind of low prio. WDYT? It would be nice to have maybe but users rarely cancel updates, unless they take forever. And in theory that should not matter for snap changes, right?
