### ISSUE TITLE
Explorepage: Snaps have lowercase titles

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#1156]
Titles for snap packages on explore page is all lowercase, but on app page it's capitalized.
Is this because the apppage uses `appdata.title`, but the app_banner uses `appstream` and can we fix it?

![image](https://user-images.githubusercontent.com/3986894/224581014-e4bcf053-2d59-4a51-bf5b-1e8bdfaed8fb.png)

![image](https://user-images.githubusercontent.com/3986894/224581022-21c4b026-7bc7-4f95-8e9c-338e8d43d202.png)

![image](https://user-images.githubusercontent.com/3986894/224581031-a95d9504-7342-4071-bd51-32fc9465baf2.png)

**Comment by Feichtmeier** [comment]
I think because we show .name and not .title
