### ISSUE TITLE
AppPage doesn't display both packages types if we selected the filter on search

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#1175]
sorry for the complicated title 😅

when we filter by **one** type of package, and click on an app that has both types of packages, the AppPage will only show the selected package.

https://user-images.githubusercontent.com/36884067/226943006-7d781977-fa4e-4a7c-9120-4a683aaea241.mov

might be related to this [issue](https://github.com/ubuntu-flutter-community/software/issues/1174)  or even this [one](https://github.com/ubuntu-flutter-community/software/issues/867)

**Comment by d-loose** [comment]
Currently the search function doesn't consider the unselected package type at all, i.e. if you unselect 'Debian packages', it won't even search for Debian packages.
So, if I understand you correctly, we should always perform a complete search of all package types, but only display those which are available as the selected package type (but include the other type as well, if available). Does that make sense? :)

**Comment by d-loose** [comment]
Fixed by #1241
