### ISSUE TITLE
star ratings: change text label

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#1182]
This might be nitpicking, but currently, the text label reads 'Click to rate:'. 
I got the feedback that it is quite redundant telling the users to click. 

Having 'Rate:' should be sufficient.

<img width="712" alt="Screenshot 2023-03-23 at 11 28 58" src="https://user-images.githubusercontent.com/36884067/227191321-d495f335-1826-47be-8dd4-eaf65662c1ed.png">

**Comment by madsrh** [comment]
That is nitpicking for sure 😅 but it's good. I think this falls within my flutter skills 😂

👍

**Comment by jpnurmi** [comment]
With ODRS, it's not possible to send a rating alone but it must be coupled with a textual review. :( Thus, I'm afraid we cannot have these nice clickable stars here but only in the review dialog. Should we make the stars non-interactive and change the label again?

**Comment by Feichtmeier** [comment]
IMO having one place for both star and review (the dialog) is a clearer objective for the user to solve, so I am fine with disabling the interactiveness on the stars

**Comment by anasereijo** [comment]
> With ODRS, it's not possible to send a rating alone but it must be coupled with a textual review. :( Thus, I'm afraid we cannot have these nice clickable stars here but only in the review dialog. Should we make the stars non-interactive and change the label again?

@jpnurmi could you create a separate issue for this and assign me to it so I can have a look asap? Thank you 🙏
