### ISSUE TITLE
App-page - add number of reviews

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#1185]
would be nice to have the number of reviews next to the stars

<img width="616" alt="Screenshot 2023-03-23 at 16 53 51" src="https://user-images.githubusercontent.com/36884067/227277547-f95d135e-9ad0-4c56-a72f-63cb8b799223.png">

<img width="218" alt="Screenshot 2023-03-23 at 16 54 18" src="https://user-images.githubusercontent.com/36884067/227277710-648fb906-7bb8-4ae1-b75b-ac3bde556b2a.png">

**Comment by shan-shaji** [comment]
@anasereijo Can i work on this?

**Comment by Feichtmeier** [comment]
ofc

**Comment by shan-shaji** [comment]
@Feichtmeier how we are handling the spacing between the widgets? Do we have any common widget for that?

**Comment by Feichtmeier** [comment]
There is a constant in yaru widgets. 20px = yaruPagePadding or sth. But that's about it

in this context this should be a gridview 
normally around things 20px
between text and icons 5px
between containers 10px
