### ISSUE TITLE
deb update window tab should ressemble more snap updates

### ISSUE THREAD

**Issue by alculete** [ubuntu-flutter-community/software#1207]
When updating debs the text becomes very large and seems out of place.
It should resemble more like the snaps update with small text. It can be added just a line of the current update and below a terminal that can be opened to see all details if needed. 
![image](https://user-images.githubusercontent.com/2129497/229331424-01f5ac22-0358-4159-a012-156fae74803b.png)

**Comment by anasereijo** [comment]
Thanks for your feedback @alculete, I agree - it is not consistent with the Snap tab. 
We will be redesigning the whole Manage page soon, and will take your feedback into consideration, so I will close this now. 
cheers
