### ISSUE TITLE
Only snaps appear

### ISSUE THREAD

**Issue by TylerMS887** [ubuntu-flutter-community/software#1208]
The app only lets me install (or sometimes view) snap apps.

[Screencast from 2023-04-03 08-42-30.webm](https://user-images.githubusercontent.com/115214762/229443790-087c88a1-466c-4602-8f76-e9e165424515.webm)

It refuses to do operations related to APT.

[Screencast from 2023-04-03 08-48-40.webm](https://user-images.githubusercontent.com/115214762/229445445-dd206e35-5482-4923-b75e-14c2023000e9.webm)

**Comment by TylerMS887** [comment]
It was a system issue.
A rogue PPA was in my apt sources. It was incompatible with 23.04. Removing the PPA fixed the issue.

**Comment by Feichtmeier** [comment]
Interesting! Thanks @TylerMS887 for re-checking
But eventually we could be better at handling ppa errors like this :thinking:
