### ISSUE TITLE
unable to see debs tabs of installed apps

### ISSUE THREAD

**Issue by alculete** [ubuntu-flutter-community/software#1215]
![image](https://user-images.githubusercontent.com/2129497/231224881-f19b7951-f5ac-45e0-a73f-b395189a4b29.png)

**Comment by soumyaDghosh** [comment]
Same issue here, seems like previously packagekit was slow to load, but now it's not loading anymore

**Comment by Feichtmeier** [comment]
I can not confirm this on my machine. @madsrh does this also happen to you?

**Comment by alculete** [comment]
Now I can see debs installations. It was like this for over a week. I will close the ticket

**Comment by soumyaDghosh** [comment]
# This hasn't been fixed yet.
 **Still only snaps are shown.**
![Screenshot from 2023-04-24 00-28-48](https://user-images.githubusercontent.com/72045785/233859549-ed04f2d6-73be-4b15-9fa0-4914aa1fe14d.png)

**Comment by alculete** [comment]
I think we are reporting different issues, mine was on installed apps that I couldn't see debs. Try to search GIMP and open it see if you have deb option

![image](https://user-images.githubusercontent.com/2129497/233859898-2af05793-0553-4e5d-aa5f-f57dd1b10a64.png)

**Comment by madsrh** [comment]
> madsrh does this also happen to you?

Nope, everything looks normal here 🤷‍♂️ 

@soumyaDghosh the debs are not as fast as snaps, so you'll have to give the Explore page a few seconds to load before the deb icons appear.

> I think we are reporting different issues, mine was on installed apps that I couldn't see debs. Try to search GIMP and open it see if you have deb option.

+1 @alculete alculete

**Comment by alculete** [comment]
having the same issue again after upgrading some snaps, closing snap store, re-opening, and going to manage
![image](https://user-images.githubusercontent.com/2129497/234170429-2214fe69-8af5-44b4-bfc1-7a77a1fffb60.png)

**Comment by Feichtmeier** [comment]
> having the same issue again after upgrading some snaps, closing snap store, re-opening, and going to manage
> ![image](https://user-images.githubusercontent.com/2129497/234170429-2214fe69-8af5-44b4-bfc1-7a77a1fffb60.png)
> 

Thanks!

Could you open it via terminal and copy paste the output if there is any?

**Comment by Feichtmeier** [comment]
@alculete does this still happen to you?

**Comment by d-loose** [comment]
Seems like the `packagekit-control` plug is not connected.
Can you run `snap connect snap-store:packagekit-control` and see if that resolves it?

**Comment by soumyaDghosh** [comment]
No help. BTW, this thing can be done from the settings app also of gnome.

**Comment by alculete** [comment]
> @alculete does this still happen to you?

Yes, still happening

**Comment by Feichtmeier** [comment]
Okay now it happened to me aswell

```bash
frederik@carbon:~$ snap-store
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.583" (uid=1000 pid=54340 comm="/snap/snap-store/969/bin/software" label="snap.snap-store.snap-store (enforce)") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination="org.freedesktop.PackageKit" (bus)
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1124)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObject.getAllProperties (package:dbus/src/dbus_remote_object.dart:142)
<asynchronous suspension>
#3      PackageKitClient.connect (package:packagekit/src/packagekit_client.dart:1425)
<asynchronous suspension>
#4      ExploreModel.init (package:software/app/explore/explore_model.dart:49)
<asynchronous suspension>
```

@kenvandine @d-loose did anything change for apparmor and the name of this app?

**Comment by soumyaDghosh** [comment]
There is a regression of apparmor in Ubuntu 23.04, many snaps, I have published worked in 22.10 without a need of dbus, but now they needs a slot for dbus

**Comment by d-loose** [comment]
I could finally reproduce the bug (sporadically).
In my case the actual issue was that the PackageKit service was stopped (but somehow this still resulted in an apparmor denial error message, which is quite confusing). This means it's not related to snap/apparmor at all.

So for those who are currently encountering this issue:
* What's the output of `systemctl is-active packagekit.service`?
* If it's `inactive`, does `systemctl restart packagekit.service` resolve the issue?

It seems like the PackageKit daemon automatically quits after some time. Running the console client `pkcon` has no issues, though - the daemon get restarted whenever it's run.

**Comment by soumyaDghosh** [comment]
> * systemctl restart packagekit.service

Though, in my case, `packagekit.service` was active, but restarting it fixes the issue.

**Comment by Feichtmeier** [comment]
Thanks for investigating @d-loose 

I'll test to restart the systemd service

**Comment by Feichtmeier** [comment]
> * systemctl restart packagekit.servic

with the error the service was indeed inactive. restarting it fixed the issue!

**Comment by castorfou** [comment]
deb tab non visible.
`sudo systemctl start packagekit`
then restart shop and now deb is visible.

**Comment by alculete** [comment]
seems restarting packagekit also solves issue [#1219](https://github.com/ubuntu-flutter-community/software/issues/1219)

**Comment by d-loose** [comment]
Found a workaround: explicitly calling `org.freedesktop.DBus.StartServiceByName` for `org.freedesktop.PackageKit` before invoking any well-known methods seems to work.

**Comment by joezhouchenye** [comment]
Why is this issue closed? Newly installed Ubuntu 23.10 and I still have this problem.

**Comment by alculete** [comment]
@d-loose maybe this could be reopened since app center is not supporting debs

**Comment by joezhouchenye** [comment]
Nevermind. I just encountered some icon-related problems with this app suddenly. I decided to use gnome-software instead and completely remove snap things.
