### ISSUE TITLE
Where is this on the Snap Store?

### ISSUE THREAD

**Issue by Konglomneshued** [ubuntu-flutter-community/software#1228]
Been looking for it and cannot find it.  The install section is vague.  I'm installing flutter and running what?  The app?

**Comment by madsrh** [comment]
> Where is this on the Snap Store? Been looking for it and cannot find it.

Where is what?

> ...The install section is vague. I'm installing flutter and running what? The app?

Did you follow the installation guide at the bottom of [this](https://github.com/ubuntu-flutter-community/software) page? What is it that you are missing there? It doesn't seem vague too me.

**Comment by AsciiWolf** [comment]
"Test Ubuntu Software in the preview/edge channel of the snap-store snap"

However, when looking at the Snapcraft page, it looks like that the latest/edge version is still 41.3-71-g709398e, so it more likely is under preview/candidate as a slightly older version 0.2.7-alpha.

**Comment by Feichtmeier** [comment]
preview/edge is the most up to date branch for this flutter based snap store frontend
preview/candidate was not updated in a long time

**Comment by AsciiWolf** [comment]
Oops, I did overlook the preview/edge channel. Sorry!

**Comment by Feichtmeier** [comment]
npz 👍 :)

**Comment by Feichtmeier** [comment]
> Been looking for it and cannot find it.  The install section is vague.  I'm installing flutter and running what?  The app?

1) open a terminal
2) killall snap-store
3) sudo snap refresh snap-store --channel=preview/edge
