### ISSUE TITLE
Use appstream.dart for packagekit icons and screenshots

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#128]
Unlike snapd, packagekit does not provide any icons or screenshots of the apps.
So to get those we need appstream.dart, which should be used in the package_service.dart here to fetch the metadata for X packages ad store them

IMO since snapd is so very fast with getting icons and screenshots I would not slow this app down by using appstream for snaps - Opinons ?  @oSoMoN @jpnurmi @Jupi007 

Depends on https://github.com/canonical/appstream.dart/issues/15

**Comment by Jupi007** [comment]
Maybe a stupid question, but can't you just conditionally fetch the app icon: false for snap, true for other?

**Comment by oSoMoN** [comment]
I haven't looked in the implementation details, but from your description of the problem I would indeed recommend using appstream only for packages where the icons/screenshots are not available otherwise (i.e. not snaps).
