### ISSUE TITLE
Using snap for installing flutter

### ISSUE THREAD

**Issue by guyluz11** [ubuntu-flutter-community/software#145]
For install flutter section in readme 
https://github.com/ubuntu-flutter-community/software#install-flutter

we can also recommend simpler and more elegant way of installing by using the [snap version](https://snapcraft.io/flutter)

`sudo snap install flutter --classic`

**Comment by Feichtmeier** [comment]
The snap version *had* it's problems when my_application.cc uses stuff that is not provided in the snap. However, I didn't check for months tbh. I'll give it another try :)

**Comment by guyluz11** [comment]
Thanks

Update me if it is working and I will be happy to commit that.

**Comment by Feichtmeier** [comment]
@guyluz11 I think you could add them to README.md, as our CI test works for flutter snap.
