### ISSUE TITLE
Using snapd version from pub.dev

### ISSUE THREAD

**Issue by guyluz11** [ubuntu-flutter-community/software#146]
https://github.com/ubuntu-flutter-community/software/blob/b96857ae0e09e29553fc5e72c4301b75c5215b80/pubspec.yaml#L36

I think it will be better to use the packages versions from pub.dev instead of directly from the GitHub repo
https://pub.dev/packages/snapd

This can help a number of ways, the first one that come to my mind is more organized version control.
New versions will need to be updated manually inside pubspec.yaml but the app version can be directly connected to specific package version for issues and to know if a new feature has arrived.

**Comment by Feichtmeier** [comment]
You are right, I just used the git version because things changed so much and frequently :) Will def. switch to pub versions for all used libs

**Comment by guyluz11** [comment]
Can I take this one?

**Comment by Feichtmeier** [comment]
Sure :) !
Please use the most recent version because robert added another feature to getConnections
https://github.com/canonical/snapd.dart/commit/b2c54d903e06f4bada382a29ef9f4efa9485e4c0

**Comment by guyluz11** [comment]
I can also update all other packages in another commit, would that be ok?.

**Comment by Feichtmeier** [comment]
No please not yet, things currently change too much and we/I did not make releases for yaru_widgets/yaru and yaru_icons.dart for some weeks :)
