### ISSUE TITLE
Feature Discussion: Can the Pacstall support be added?

### ISSUE THREAD

**Issue by soumyatheman** [ubuntu-flutter-community/software#159]
There is this store called Pacstall where software packages from third party maintainers and users. The concept is similar to the concept of AUR in Arch Linux. Can this be added in the store to enhance the availability of softwares.

**Comment by Feichtmeier** [comment]
Maybe in the future who knows
The focus is on snap and Deb because this is what Ubuntu uses by default.
;)
Packagekit is used for debs. I know that it's a universal approach to solve to problem of too diverse package standards in the Linux desktop world. And I know that packagekit can also be used to install rpm packages. I think in theory this should also work on arch Linux. Packagekit itself uses dbus

**Comment by soumyatheman** [comment]
> The focus is on snap and Deb because this is what Ubuntu uses by default. ;) Packagekit is used for debs. I know that it's a universal approach to solve to problem of too diverse package standards in the Linux desktop world. And I know that packagekit can also be used to install rpm packages. I think in theory this should also work on arch Linux. Packagekit itself uses dbus

I think you don't know about Pacstall, it's a repository of packages which are not in the official repositories. All of them are supported in Ubuntu and have deb files. Please check this out for more info [Pacstall](https://github.com/pacstall/pacstall)

**Comment by Feichtmeier** [comment]
@soumyatheman oh - sorry! Indeed this is very different.

I fear this might not fit into the concepts of this app (snap & packagekit (deb/rpm)). But I let the issue opened for discussion.
Also this app here is a flutter frontend for snapd and packagekit. Snapd can be accessed via snapd.dart and packagekit can be accessed via packagekit.dart. For your packstall a flutter frontend would first require a dart library if you want to have a clean approach without any "call bash from flutter"-tricks (which is ofc possible) 😺

**Comment by soumyatheman** [comment]
Let me elborate more about that. Example I'm taking is Pamac, It can support, Repo packages, Snap, Flatpak and AURs all under one hood. Though there is a thing, the PKGBUILD is same for Repo Packages and AURs, but in case of this pacstall, the packages are in .pacstall format, that might be a problem in calling things from the app. Why I'm enforcing to add pacstall is because it enables a lot of packages not available for Ubuntu/Debian. Also there is this project from the lead dev of Ubuntu Mate called [deb-get](https://github.com/wimpysworld/deb-get). This enables packages from third-party ppas or via static websites available. These two needs to be merged under one hood. I am also thinking to raise new issues in both these two projects, Until then, add flatpak asap please 😅

**Comment by soumyatheman** [comment]
Hi devs, here after some dart learning. I will give a try to make a dart file for pacstall, to fetch packages, but how can I test if it's able to fetch packages or not? I am totally novice and just started learning today. Thanks in advance.

**Comment by Chadano** [comment]
I think it might be a good idea to speak with the Pacstall maintainers to see if it actually feasible. If I recall correctly the Pacstall maintainers were creating a graphical user interface at one point. @henryws can comment further on whether this is possible.

**Comment by Feichtmeier** [comment]
Sorry guys, but this won't happen for this project.

1) We use snapd.dart for snaps and packagekit.dart for debian packages
Those libraries are needed to communicate with the snapd and packagekit services/demons/processes running on the system.
There is no such thing for pacstall available as a dart library on [pub.dev](pub.dev)
2) To get the best performance and user experience we focus on the two package formats useable on ubuntu by default. (actually with packagekit there would be potentially more package formats)

I hope you understand this and do not interpret this as a criticism of your package format. Thanks for your request and happy installing
