### ISSUE TITLE
Clicking hyperlinks in the about dialog does nothing

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu-flutter-community/software#164]
The hyperlinks for the names of the contributors in the about dialog do nothing when clicked. I would expect the links to open in the default web browser.

**Comment by Feichtmeier** [comment]
Yes! This is definitely a new bug 🐱 maybe something changed in the meantime

**Comment by oSoMoN** [comment]
There was a flutter stable update recently, maybe that broke flutter_markdown? But I'm not seeing any related issue (neither open nor closed) in [the bug tracker](https://github.com/flutter/flutter/issues?q=is%3Aissue+label%3A%22p%3A+flutter_markdown%22).

**Comment by oSoMoN** [comment]
Another potential suspect is e839e8751e5fcf5a8e0579ab1278195716e7bbff, where the dependency on flutter_markdown was updated from 0.6.10+4 to 0.6.10+5.

**Comment by Feichtmeier** [comment]
No sorry, I just used the mardown package wrong and didn't provide an onLinkTap callback :) fixing this in the linked pr

**Comment by oSoMoN** [comment]
This issue was about hyperlinks in the about dialog, not in the packages' changelogs. Can you please re-open?

**Comment by Feichtmeier** [comment]
Sorry 🤦 😄
