### ISSUE TITLE
Enhancement: Add more featured app

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#165]
I came across [this ](https://dribbble.com/shots/9392577-Ubuntu-App-Store-Productivity-Screen)nice mockup from Lena Tsybulenko. I really like the idea of more than one freatured app.

![image](https://user-images.githubusercontent.com/3986894/188219946-2bffab62-2743-4799-90de-5e3acc6c2614.png)

The current featured app banner works 100% fine, but it isn't the best use of space. Anyway, just a nice to have enhancement.

![image](https://user-images.githubusercontent.com/3986894/188220504-998b9620-9b46-46dc-b9bc-27f0f93980da.png)

**Comment by Feichtmeier** [comment]
Very nice idea

**Comment by Feichtmeier** [comment]
@madsrh is this issue resolved with the recent change to the explorepage?
