### ISSUE TITLE
Update git version of widgets and icons

### ISSUE THREAD

**Issue by Jupi007** [ubuntu-flutter-community/software#171]
Related to https://github.com/ubuntu/yaru_widgets.dart/pull/197

**Comment by Feichtmeier** [comment]
We need new releases then :) it's about time. Been some weeks

**Comment by Jupi007** [comment]
I just updated the git ref, but if you want I can't publish a new release and use it here :)

**Comment by Feichtmeier** [comment]
We got this issue and PR about pub versions. Eventually he could update his PR after you released the new versions?

**Comment by Jupi007** [comment]
Oh, indeed you're right let's do this :+1: 
I'll release new versions.
