### ISSUE TITLE
Add Indonesian Translation

### ISSUE THREAD

**Issue by WildanGarviandi** [ubuntu-flutter-community/software#178]
as Indonesian user, i would like to have it on Bahasa Indonesia

**Comment by madsrh** [comment]
Can you help with the translations? You'll need to submit a pull request (after you've signed the contributor agreement in order to let the first test pass) 😃 
https://ubuntu.com/legal/contributors/agreement

**Comment by WildanGarviandi** [comment]
Hello @madsrh sure i'd love to, on my way to submit the PR for this
