### ISSUE TITLE
Pin flutter at 3.0.x because of rendering issues with 3.3

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu-flutter-community/software#189]
Flutter 3.3 has severe raster cache rendering issues due to fractional translation i.e. removal of pixel snapping: https://github.com/jpnurmi/flutter_raster_cache_bug.

**Comment by Feichtmeier** [comment]
This flutter version does not include the theme listening fix of JP. We need to find a beta releasev that includes the theme listening before any change to the engine happened that introduces the raster bug

**Comment by oSoMoN** [comment]
What is the "theme listening fix"? Is it 56fc72d6f832f9365d740c5fac65ef06993772af ?

**Comment by Feichtmeier** [comment]
No, I meant a commit by JP in flutter for dark and light theme detection inside flutter

**Comment by jpnurmi** [comment]
This is the Flutter engine change @Feichtmeier means:
- https://github.com/flutter/engine/pull/33100

It was included in the Flutter framework in:
- https://github.com/flutter/flutter/pull/103665

You could try your luck with `3.1.0-9.0.pre` and hope that it doesn't have the raster cache bug :)
```
$ git tag --contains 157c1f900f9feda468342eac444eb211873e0458
3.1.0-9.0.pre
3.3.0
3.3.0-0.0.pre
3.3.0-0.1.pre
3.3.0-0.2.pre
3.3.0-0.3.pre
3.3.0-0.4.pre
3.3.0-0.5.pre
3.4.0-18.0.pre
```

**Comment by Feichtmeier** [comment]
jp wins :) this version has the theme sync feature and misses the raster cache bug


https://user-images.githubusercontent.com/15329494/188641871-b286c56b-f729-44b1-8a4d-fe532c5d32b1.mp4

But I better test this on a big screen... sec

**Comment by Feichtmeier** [comment]
Yep this version looks good :+1:  
Tested on a 2,5k screen where the raster issue is easier to reproduce

https://user-images.githubusercontent.com/15329494/188643005-66312379-19cc-4565-84b5-f3880c97449a.mp4

**Comment by Feichtmeier** [comment]
jeez... aftter a bit more testing in different dialogues.... sadly it is also in this tag :sob: 


https://user-images.githubusercontent.com/15329494/188646610-fd7fc133-324e-4091-bd9f-b950dfe12823.mp4

testing other tags...
