### ISSUE TITLE
Window rendering problems

### ISSUE THREAD

**Issue by ParkerStones** [ubuntu-flutter-community/software#201]
**the main window is GLITCHING.......**

**Comment by ParkerStones** [comment]
[proof.webm](https://user-images.githubusercontent.com/38376474/189801829-0bd263f4-5a09-4d34-871a-cd0db00a0f99.webm)

**Comment by Feichtmeier** [comment]
Is this run from vscode?

**Comment by ParkerStones** [comment]
No, ran in shell prompt!

**Comment by Feichtmeier** [comment]
Did you run it via ```flutter run``` in the terminal or did you start the binary from the build/Linux dir from the terminal?

**Comment by ParkerStones** [comment]
no flutter just binary from terminal! ----- "./software"

**Comment by Feichtmeier** [comment]
That's strange. Never happened to me before. Could you post more information about your system? Thanks in advance

**Comment by ParkerStones** [comment]
![Screenshot from 2022-09-20 11-19-40](https://user-images.githubusercontent.com/38376474/191177387-3fe00475-741d-49e4-8b70-b3c9f7508a20.png)

**Comment by hotlittlewhitedog** [comment]
@ParkerStones Is there a debug mode in the app and some output logs with errors ;)

**Comment by whiskeyPeak** [comment]
Experiencing the same issue on master for both software and flutter. The flicker is mainly tricked when scrolling through the application list.

**Comment by Feichtmeier** [comment]
Hm, I fear it must be something specific to a host configuration that eventually has problems with the flutter rendering engine skia

The only real difference I see on your system might be a relatively low resolution? No idea other wise
@whiskeyPeak do you also have 1,3k resolution?

[Bildschirmaufzeichnung vom 22.09.2022, 07:47:00.webm](https://user-images.githubusercontent.com/15329494/191667972-488e2cac-b6be-477b-8f06-fbd9e844ceb9.webm)

![grafik](https://user-images.githubusercontent.com/15329494/191668218-cfe8dd9f-5f85-48bf-962b-fd9047c4b596.png)

**Comment by jpnurmi** [comment]
@ParkerStones Any chance you could try installing the latest Flutter stable manually and try running the software app with that?

@Feichtmeier You had some nice ~one-liner instructions right? :)

**Comment by Feichtmeier** [comment]
Remove the flutter snap if installed
```
sudo snap remove flutter
```

Then

```
sudo apt -y install git curl cmake meson make clang libgtk-3-dev pkg-config && mkdir -p ~/development && cd ~/development && git clone https://github.com/flutter/flutter.git -b stable && echo 'export PATH="$PATH:$HOME/development/flutter/bin"' >> ~/.bashrc && source ~/.bashrc
```

**Comment by ParkerStones** [comment]
Okay 👌🏾

**Comment by jpnurmi** [comment]
After that, clone the software app repo and run the app with `flutter run`
```
git clone https://github.com/ubuntu-flutter-community/software.git
cd software
flutter run
```

**Comment by ParkerStones** [comment]
Everything is now working just fine !
