### ISSUE TITLE
Add open button to AppPage installed page tiles 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#209]
The open button won't work in the snap yet.  We have a branch of snapd that adds app launch from another snap capability, but that will take a while to land, it's huge.  Can you hide the open button if $SNAP is set in the environment?

_Originally posted by @kenvandine in https://github.com/ubuntu-flutter-community/software/issues/205#issuecomment-1247477123_

**Comment by Feichtmeier** [comment]
Reopend to check the status of this

@kenvandine can we show it again now?

**Comment by local-optimum** [comment]
I am also interested in us being able to have 'open' buttons on the snap pages and from the 'installed snaps' section of the store so if we can re-enable this that would be good.

**Comment by kenvandine** [comment]
The desktop-launch interface has landed in snapd now, maybe @robert-ancell can help us launch apps properly using that interface.

**Comment by robert-ancell** [comment]
I think the correct long term solution to this is to create a portal to launch apps - then software can just use that portal. The desktop-launch interface is quite powerful, so it's not something that most snaps will be able to easily get. However, the process for creating a new portal will take time, so we might consider using desktop-launch before switching to portals at a later stage.
