### ISSUE TITLE
Accents and some other characters in text are not rendered

### ISSUE THREAD

**Issue by fthx** [ubuntu-flutter-community/software#210]
Hi,

Congrats for the design, especially for the very clear snap/deb separation. (If I can remember the Way, there will be another flutter Ubuntu Firmware snap package along this one?)

Well:

![image](https://user-images.githubusercontent.com/23138504/190334393-77686599-4733-4e73-b7a9-b94c87c6a114.png)

**Comment by Feichtmeier** [comment]
Hi @fthx :)
 Thanks!
 
Yes, this is a bug in packagekit.dart
We got this issue linked in #120 
Can you close this one here in fav of the other one?
