### ISSUE TITLE
Enhancement for arrows on image carousel

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#224]
The difference between the active and deactivated arrows in the image carousel are too subtle IMHO. I think a better solution would be if the images could just loop ♾️ or alternatively, to hide the left arrow on the first image (and right arrow for the last ofc).

![image](https://user-images.githubusercontent.com/3986894/190789164-82a8fc1f-0524-456b-8e4c-9fcaa2cbf99e.png)

For accessibility the keyboard left/right arrows should work when I click the arrows, the dots and when the image is enlarged.

**Comment by Feichtmeier** [comment]
Could you move this issue to yaru_widgets? 
It is a component from there (thanks to paul!) :)

**Comment by madsrh** [comment]
Moved to https://github.com/ubuntu/yaru_widgets.dart/issues/208
