### ISSUE TITLE
SoftwareStoreApp: add a widelayout

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#226]
For bigger windows the current layout of the storeapp is not perfect

Add wide layouts for

- [X] navigation
- [X] AppPage
- [x] ExplorePage
- [x] MyAppsPage
- [x] UpdatesPage

**Comment by Feichtmeier** [comment]
How Windows 11 handles app pages depending on screenwidth

![win11](https://user-images.githubusercontent.com/15329494/190974806-4bb1f116-58e4-400e-ab57-9f574d5034ec.gif)

I like the idea of giving each tile a background (or a border in our design "Language") to prevent the visual effect of elements "free-floating" too much

**Comment by elioqoshi** [comment]
Thanks @Feichtmeier,

I think how Windows handles it is pretty elegant. The mockup you mentioned is an improvement already. How would it look like in the view of an app?

**Comment by Feichtmeier** [comment]
Sorry @elioqoshi for not updating this issue

We've tried the following for the new snap page (no more dialog) - this is how it looks:

[Bildschirmaufzeichnung vom 26.09.2022, 13:49:18.webm](https://user-images.githubusercontent.com/15329494/192269139-1addcb13-6a93-4e4b-b64e-3f681a33fcb4.webm)

you can try this is if you like in the snap-store snap from preview/edge

**Comment by elioqoshi** [comment]
I really like this, great stuff!

Something for @anasereijo to have a look at eventually as well.

**Comment by Feichtmeier** [comment]
[tadah.webm](https://user-images.githubusercontent.com/15329494/193265531-c0fe3893-e538-44ef-a85d-c2f872a4cbe6.webm)

This is the status-quo for the AppPage widelayout

let's keep this open for the other pages
