### ISSUE TITLE
Provide a link to project's github page

### ISSUE THREAD

**Issue by keshavbhatt** [ubuntu-flutter-community/software#232]
It will be nice to have a link to project's Github page in Application's about section.
It will increase project's reach to developers who are interested in contributing.

I think the ideal place to put the link would be App's about section.

Thanks for nice work :)

**Comment by Feichtmeier** [comment]
Thank you @keshavbhatt for the idea!

Wow you have lots of snaps in the store :partying_face: 
![image](https://user-images.githubusercontent.com/15329494/191908866-88ee112b-9cd9-426f-997c-ed3952ae917d.png)
