### ISSUE TITLE
Don't color icon and label in nav bar

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#234]
ATM active selections have both icon and label colored:
![image](https://user-images.githubusercontent.com/3986894/190929709-90fd37c3-7962-4562-a213-d99ecdf0f945.png)

We should only add color to the "pill" background and change the text weight.

https://api.flutter.dev/flutter/material/NavigationBar-class.html

![image](https://user-images.githubusercontent.com/3986894/190929681-b72abd93-25d9-4c45-ae94-358e33901086.png)

**Comment by Feichtmeier** [comment]
Yeah this is a strange thing because the navigation rail is already in material 3 but the flutter version we use here does not have the complete migration to m3 yet
So I suppose once that happened the appbar shouls look like the navirail

**Comment by Feichtmeier** [comment]
I've temporarily increased the max width of the window until I've fixed this in yaruwidgets
So we "only" have three navigation steps now

**Comment by Feichtmeier** [comment]
So this is actually also an issue in yaru_widgets, where the navigation comes from
