### ISSUE TITLE
Prevent update interruptions more gracefully on app close

### ISSUE THREAD

**Issue by oyajun** [ubuntu-flutter-community/software#235]
[Screencast from 2022年09月19日 18時59分45秒.webm](https://user-images.githubusercontent.com/81346541/190994089-6055e415-2cd9-4a4e-bcd1-222a7d7166c7.webm)
[Screencast from 2022年09月19日 19時08分34秒.webm](https://user-images.githubusercontent.com/81346541/190995393-0ca44516-f265-400b-9e5c-e4888a29d90a.webm)

Version: 0.1.2-alpha from SnapStore
Language:Japanese
OS:Ubuntu22.04.1
Wayland

**Comment by Feichtmeier** [comment]
Hi @oyajun  :)

Japanese letters look so cool in the app :D 

On topic: yes, I disabled the close buttons when the app is checking for updates to not leave packagekit in any error state. I agree that this could or should be handled more gracefully. Just do not want to crash anyones system when he is running updates :)

**Comment by oyajun** [comment]
Hi @Feichtmeier 😁
I am glad to hear that ＼(^o^)／

This is a my idea.
The message (ex. Don't close this app now) is displayed on title bar.
But, I don't think this is good idea. Please tell me other idea better than mine.

Mock up
![Screenshot from 2022-09-19 22-05-51](https://user-images.githubusercontent.com/81346541/191025003-e4a67067-1f47-4656-bdda-8d7ce8ad097e.png)

**Comment by swann-martin** [comment]
Hi @Feichtmeier,

I agree with @oyajun. I thought the disappearing of the buttons was a bug at first. I did not wait and closed the app via a right click in the dock in gnome. Maybe leaving the expand and minimize buttons and only replacing the close button by a circular loader would help.
It is just an idea. 
I like the project though, keep up the good work !

**Comment by Feichtmeier** [comment]
Maybe I could leave them but open a dialogue to confirm

**Comment by jpnurmi** [comment]
What kind of operations can leave packagekit in an error state? I'd imagine it's ok to interrupt a read operation because packageki.dart operates over D-Bus so there's no child process being abruptly killed.

**Comment by Feichtmeier** [comment]
Well, even if packagekit only sends a message to apt to update x packages
and then you close the app and shut down the computer
I have no idea what happens then

Checking for updates is ofc less dangeous than updating. I disabled the buttons for both cases but I agree that it is a weird choice
