### ISSUE TITLE
Re-add installtion date, but without weekday

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#237]
There's no need to show the weekday (friday) from installation date. Just remove it **29. apr. 2022** or show it in a tooltip.

![image](https://user-images.githubusercontent.com/3986894/191089953-8677db2b-197e-426e-a98d-5494e6736572.png)

**Comment by Feichtmeier** [comment]
I replaced it with the seleceted or installed version in  #262 

We could put it somewhere else, maybe far down in the description or something.
It is "a nice info" but really not so super important, imo
