### ISSUE TITLE
Updating one package returns "everything is up to date"

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#238]
When you only install one package the text implies that there are no more updates. It should just say something like "Update installed / install finished / done! / ..."

![image](https://user-images.githubusercontent.com/3986894/191104387-75a90938-d0f1-4cc2-9096-9dd21beabeef.png)

**Comment by Feichtmeier** [comment]
I've reread the issue described but I fail to understand what you mean 😃 😺

**Comment by madsrh** [comment]
LoL, sorry 😆

I have 34 updates. I deselect all, and only select 1 update. When the install is finished, I'm prompted with "_EVERYTHING_ is up to date", but really I'm missing 33 updates before my system is up to date. It's just that one package that has finished installing.

#nitpicking
