### ISSUE TITLE
Doesn't run o ubuntu mate 22.04

### ISSUE THREAD

**Issue by neffscape** [ubuntu-flutter-community/software#245]
I'm not able to run the new snap store on ubuntu mate 22.04. When I try to run it I obtain this output:

`neff@WS00772:~$ snap-store
Gtk-Message: 17:15:45.424: Failed to load module "appmenu-gtk-module"
(software:9844): IBUS-WARNING **: 17:15:45.474: chmod failed: Permission denied
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.170" (uid=1000 pid=9844 comm="/snap/snap-store/604/bin/software " label="snap.snap-store.snap-store (enforce)") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.freedesktop.NetworkManager" (uid=0 pid=998 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1124)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityLinux._startListenConnectivity (package:connectivity_plus_linux/src/connectivity.dart:61)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.171" (uid=1000 pid=9844 comm="/snap/snap-store/604/bin/software " label="snap.snap-store.snap-store (enforce)") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.freedesktop.NetworkManager" (uid=0 pid=998 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1124)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityLinux.checkConnectivity (package:connectivity_plus_linux/src/connectivity.dart:24)
<asynchronous suspension>
`
What's wrong?

**Comment by Feichtmeier** [comment]
Hi @neffscape 

This issue seems similar to #202 as it outputs dbus errors and the network manager

@kenvandine could you take a look into both issues as they seem snap related to me 🐱

**Comment by kenvandine** [comment]
@neffscape is that all of the output?  Those errors shouldn't be fatal, is there anything output after that?  Is it actually crashing?

**Comment by kenvandine** [comment]
Does connecting the network-manager-observe interface help?

snap connect snap-store:network-manager-observe

**Comment by Feichtmeier** [comment]
@neffscape any update on this? Ken made the interface autoconnect now
