### ISSUE TITLE
Tabing on selected outer navigation should return to the first state of the page

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#254]
When you're on an app page within Explore, you should be able to click "Explore" in the sidebar to return to the previous page (like the back button **<** does).

Similarly if you open the app page from "My apps" you can't click "My apps" in the sidebar to return. 

I've made a beautiful illustration below:
![image](https://user-images.githubusercontent.com/3986894/191623564-20801d38-6c14-4eed-b00c-31811980eb65.png)

**Comment by Feichtmeier** [comment]
Hmmmm the back 🔙 button in the navbar is not enough?

**Comment by madsrh** [comment]
> the back 🔙 button in the appbar is not enough?

IDK 🤷‍♂️ IMO there's no reason to "disable" it. It seems a bit counterintuitive that you can't click it, but let's hear what others think ☺️

**Comment by Feichtmeier** [comment]
Nono it is not disabled : D I just did not think about this before. Needs a change in yaruwidgets, but should be no problem.
Maybe you have learned to navigate back like this, while my brain learned to focus on back-buttons. At least I should add this feature in yaruwidgets with an onTap callback which can be used or not

**Comment by jpnurmi** [comment]
Makes sense - this kind of shortcuts are common in mobile apps. Even though I wouldn't have realized to try to click the sidebar item either. :)

**Comment by Jupi007** [comment]
Imo, this is a good idea @madsrh :+1: 
_But honestly I never through about click again on the side bar to go back._

**Comment by anasereijo** [comment]
I actually just tried to go back to Explorepage by clicking on the icon :) I think it's quite a common pattern.

**Comment by Feichtmeier** [comment]
@d-loose could you check if you got a solution for this one? JP said we might need some sort of controller pattern forwarded top to bottom in the tree here

**Comment by d-loose** [comment]
I'll look into it :)

**Comment by d-loose** [comment]
I've played around a bit - some thoughts:
* The cleanest solution would probably be to switch to a completely declarative navigation and set a proper state in `YaruNavigationPage`'s `onSelected`. Currently the only parts that use imperative navigation are the App/Package/Snap pages, but it still looks like a decent amount of refactoring.
* Another solution would be to pass navigator keys to all pages of the `YaruNavigationPage` and simply call `popUntil((route) => route.isFirst)` on the respective navigator in `onSelected`. This could probably also be done directly in the yaru widgets instead.

**Comment by Feichtmeier** [comment]
@d-loose thanks for investigating, if you don't have a strong veto I would go for the second idea :)

**Comment by madsrh** [comment]
<Img SRC="https://media.tenor.com/_50i4w1FYCQAAAAM/hallelujah-thank-god.gif">

Thanks 👍

**Comment by Feichtmeier** [comment]
Thank you @d-loose !
