### ISSUE TITLE
AppPage: use gesture detector for navigating back and forth with mouse keys

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#259]
Don't know how these ones are called (mouse button 3 and 4, or 5?) but I use it frequently to navigate back and forth in browsers and file explorers. We need this in software too, should be possible when wrapping the whole app in a mouse listener

Edit: this needs to be implemented in flutter, currently only 1., 2. and 3. buttons are listenable
https://github.com/flutter/flutter/issues/115641

**Comment by whiskeyPeak** [comment]
I think this feature still has a few issues:
- Left clicking anywhere on the page that isn't a button pops the route
- Swiping horizontally with 2 fingers from left to right or right to left pops the route (should only be from left to right IMO)
- There is no indication that that swipe gesture will pop the route until it is popped.

I did a bit of research and creating a custom swipe gesture with multiple fingers support is actually quite easy with flutter! I can give a go at fixing the issues above over the next week if you want :) @Feichtmeier

**Comment by Feichtmeier** [comment]
> Left clicking anywhere on the page that isn't a button pops the route ?

 Hm does not happen for me though :thinking: 
only if I swipe the navi pops

>  I can give a go at fixing the issues above over the next week if you want

I planned to improve it after I am done with reviews, but if you have time now sure go ahead! I like how it is in firefox. WHen your swipe a OSD pops up and only if you release the gesture it is fired
In general please keep the changes as small as possible so it become easy to review and less conflicts etc

**Comment by whiskeyPeak** [comment]
> Hm does not happen for me though thinking
only if I swipe the navi pops

https://user-images.githubusercontent.com/73116038/203024957-39a42ce7-4713-488c-8cd5-544d820b9415.mp4

The first click pops the route, but when my mouse hovers over the license text, clicking/tapping does nothing, although swiping horizontally still pops the route.

> I planned to improve it after I am done with reviews, but if you have time now sure go ahead! I like how it is in firefox. WHen your swipe a OSD pops up and only if you release the gesture it is fired
In general please keep the changes as small as possible so it become easy to review and less conflicts etc

Awesome! Yeah the firefox idea is what I had in mind as well.

**Comment by Feichtmeier** [comment]
yeah you are right. let me revert this for now, then after you can create a branch, so I will not get a conflict in the other branch I work on

**Comment by whiskeyPeak** [comment]
Hey! I have implemented the back gesture with all of the afro-mentioned issues fixed.
- Tapping no longer pops the page
- swiping up or down no longer pops the page
- a circular button comes out from the side using 1 to 1 gestures!

Additional features:
- The circular button will stop moving further to the right/left once it has reached the max offset
- The circular button always comes out of the middle of the screen and is hidden when no gesture is in progress.
- The page will be popped if the button is extended more than half of the max extent constant.

https://user-images.githubusercontent.com/73116038/204098260-d445824d-5dad-4298-a562-8e3523b65bd5.mp4

I haven't yet implemented this in the store yet (though it should be pretty straightforward), just wanted to get feedback on styling :)

**Comment by Feichtmeier** [comment]
> Hey! I have implemented the back gesture with all of the afro-mentioned issues fixed.
> - Tapping no longer pops the page
> - swiping up or down no longer pops the page
> - a circular button comes out from the side using 1 to 1 gestures!
> 
> Additional features:
> - The circular button will stop moving further to the right/left once it has reached the max offset
> - The circular button always comes out of the middle of the screen and is hidden when no gesture is in progress.
> - The page will be popped if the button is extended more than half of the max extent constant.
> 
> https://user-images.githubusercontent.com/73116038/204098260-d445824d-5dad-4298-a562-8e3523b65bd5.mp4
> 
> I haven't yet implemented this in the store yet (though it should be pretty straightforward), just wanted to get feedback on styling :)
> 
> 

Awesome work!
