### ISSUE TITLE
AppPage Design

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#260]
Normal window size layout:

![grafik](https://user-images.githubusercontent.com/15329494/191793273-9273c44f-9933-4418-959e-ffe8b9c94bba.png)

Medium window size layout:

![grafik](https://user-images.githubusercontent.com/15329494/191793707-4f7197f7-6957-4b26-9ef5-235de1073164.png)

Wide window size layout:

![grafik](https://user-images.githubusercontent.com/15329494/191793473-5bd07ac0-5b08-48cd-91dd-752e52557e4e.png)

Slim window size layout:

![grafik](https://user-images.githubusercontent.com/15329494/191793355-92143b7d-fd6d-47ad-9e79-e31274adb8d3.png)

**Comment by Feichtmeier** [comment]
Yeah the menu  is horrible, I am working right now on a replacement :)

**Comment by fthx** [comment]
Also I don't see the app version in app page.
Maybe display the channel and the version (without having to trigger the channel menu)?

**Comment by Feichtmeier** [comment]
Idea 1 - style the context menu better:

[Bildschirmaufzeichnung vom 22.09.2022, 22:47:29.webm](https://user-images.githubusercontent.com/15329494/191847991-293ae20f-cb78-43e1-8243-baaf279e0cf2.webm)

Idea 2 - show the channel in it's own container to give all information enough space so you see everything at once:

![grafik](https://user-images.githubusercontent.com/15329494/191849130-161f3491-5da6-4c2c-b7b1-3974f5bdf7de.png)

**Comment by fthx** [comment]
My opinion: keep the channel menu in top container (modify-the-snap container) and display the current installed version + date in your new container or maybe in the existing confinement's one? And I find the confinement container layout (one line with separators) look better than the two lines one.

The context menu is somewhat better like that. :-))

Also: I would like that, when I see an app page, the 'my apps' button will take me back to the apps homepage?

**Comment by Feichtmeier** [comment]
You mean like this?
![grafik](https://user-images.githubusercontent.com/15329494/191853132-9d4833d3-a413-40ae-919d-8a5d2190ceba.png)
![grafik](https://user-images.githubusercontent.com/15329494/191853429-53562845-d530-4aaf-923a-acf1a53ae661.png)

On your "Also" - I think you mean ExplorePage right? There is an issue for this #254

**Comment by madsrh** [comment]
> Also: I would like that, when I see an app page, the 'my apps' button will take me back to the apps homepage?

Great, then it wasn't just me 😅 

I tested the context menu branch and it's such an improvement @Feichtmeier 🎉 Looks great, except for Inkscape 🙈 


How about including the version number in the dropdown like they do on snapcraft.io ? You would ofc need to shorten it sometimes.

![image](https://user-images.githubusercontent.com/3986894/191872604-09ca0af6-d37d-4c7c-873c-787082706c06.png)

WDYT of switching the placement of the date and the version in the menu? This way the version number would have more space. IMO you should hide the weekday here. 

![image](https://user-images.githubusercontent.com/3986894/191875683-8ae066ce-0ce3-4de0-a7f3-ce2776a20f89.png)





A quick snapcraft style mockup I did before I tried your excellent branch:
![image](https://user-images.githubusercontent.com/3986894/191874001-87127477-62c7-4012-9fed-fc15741e8b0f.png)

**Comment by Feichtmeier** [comment]
> How about including the version number in the dropdown like they do on snapcraft.io ? You would ofc need to shorten it sometimes.

The problem is that even the version strings can be really long. Even the average of them is really long.

**Comment by Feichtmeier** [comment]
A horizontal design for the menu won't work in the small window size
![grafik](https://user-images.githubusercontent.com/15329494/191899705-2bfe75d3-07e9-4b99-a432-436a62e08974.png)

How about removing the icon again, making the ListTile dense?
![grafik](https://user-images.githubusercontent.com/15329494/191900783-d5c062a5-5cf3-4764-ade6-d7285b403920.png)

You can not cut the versions because they are not standartized they are just Strings. THe publisher can name them whatever they want (Lokomotivführerkinderführerschein :clown_face: ?)

Those infos can be so weird you won't believe it.
I show you another extreme in terms of channel amount:
![grafik](https://user-images.githubusercontent.com/15329494/191901003-b11e038e-daac-4799-b9df-a7c5023fd1ea.png)

**Comment by madsrh** [comment]
What about this one @Feichtmeier ? 👍 / 👎 

> WDYT of switching the placement of the date and the version in the menu? This way the version number would have more space. IMO you should hide the weekday here.

![image](https://user-images.githubusercontent.com/3986894/191948632-89899562-19c6-4e7e-9252-65a7fd06c93f.png)


> When the user selected a channel that has different version than the version installed the button becomes green

This only happens in the orange 🟠 color scheme is selected in appearance

**Comment by Feichtmeier** [comment]
> What about this one @Feichtmeier ? 👍 / 👎 
> 
> > WDYT of switching the placement of the date and the version in the menu? This way the version number would have more space. IMO you should hide the weekday here.
> 
> ![image](https://user-images.githubusercontent.com/3986894/191948632-89899562-19c6-4e7e-9252-65a7fd06c93f.png)
> 
> 
> > When the user selected a channel that has different version than the version installed the button becomes green
> 
> This only happens in the orange 🟠 color scheme is selected in appearance
> 

The version is more important imo
So on the right it doesn't get so lost for me

**Comment by Feichtmeier** [comment]
![](https://user-images.githubusercontent.com/15329494/192134194-889a443b-0245-4876-81ca-b4eeca1613f7.png)

@madsrh removed the weekday as you suggested wdyt to the look?

**Comment by fthx** [comment]
(I like it.)
If the version ref is long, is the pop-up menu not too wide for small window?

**Comment by Feichtmeier** [comment]
The listtiles can expand and resize their text children but I need to limit the sizes a bit

![grafik](https://user-images.githubusercontent.com/15329494/192146341-918dee53-d401-45b0-b200-afdb81ee1df2.png)
![grafik](https://user-images.githubusercontent.com/15329494/192146370-48d0df7b-2106-41b3-b462-6c107019b9d6.png)
![grafik](https://user-images.githubusercontent.com/15329494/192146410-87f4c74a-39b9-455f-afd8-e44638618558.png)
Some extremes
I made everyting except the tooltips have a limited size now

**Comment by Feichtmeier** [comment]
Updated with #312 

But I feel like those discussion issues are by design outdated :) Maybe we move discussions to either discussions or to the discord channel

**Comment by madsrh** [comment]
@Feichtmeier I'm not sure I understand why the popup isn't using the full available width of the window - screenshot below :point_down: (sorry, if you've already explained it above - I did re-read this thread).

I really find the current layout not easy to read. Is there any way we can improve it? You had such a nice layout [here](https://user-images.githubusercontent.com/15329494/191853429-53562845-d530-4aaf-923a-acf1a53ae661.png) or could you [reconsider the order](https://user-images.githubusercontent.com/3986894/191948632-89899562-19c6-4e7e-9252-65a7fd06c93f.png)?

![image](https://user-images.githubusercontent.com/3986894/203653635-fde259e1-2c66-475e-a099-9da27ca4d462.png)
