### ISSUE TITLE
Make restart button work in the snap 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#266]
![image_2022-09-23_14-46-05.png](https://user-images.githubusercontent.com/15329494/191963397-3fe7cbef-3ac0-42cf-954d-58558b41f4f4.png)

We display a restart button in the app if the system requires a restart after updating it with packagekit
It works fine outside of the snap but does nothing inside

Do we miss any plug @kenvandine ?

The restart button runs

```dart
  void reboot() { 
     Process.start( 
       'reboot', 
       [], 
       mode: ProcessStartMode.detached, 
     ); 
   } 
```

**Comment by kenvandine** [comment]
I don't think we want to trigger the host reboot from within the app, this is probably best left to the host OS.  For example, we need to ensure the session closes in such a way that apps have the opportunity to prompt the user to save unfinished work, etc.  Ubuntu already has a mechanism to do that, we should look at how we can ensure that is properly integrated.  I would hope PackageKit would do the right thing to trigger the notification on the host, which I think is handled via update-notifier.

**Comment by jpnurmi** [comment]
Would [`org.freedesktop.login1.Manager.Reboot()`](https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html) do the right thing?

**Comment by Feichtmeier** [comment]
> I don't think we want to trigger the host reboot from within the app, this is probably best left to the host OS.  For example, we need to ensure the session closes in such a way that apps have the opportunity to prompt the user to save unfinished work, etc.  Ubuntu already has a mechanism to do that, we should look at how we can ensure that is properly integrated.  I would hope PackageKit would do the right thing to trigger the notification on the host, which I think is handled via update-notifier.
> 
> 

We listen to the requires update signal 🚦
Which has the sub signals system reboot required, session or app. But I didn't see how to forward this correctly to the system so I stopped with displaying this to the user.
What you said sounds better though.
And the dbus method could be a better option of there is no such thing in package kit

**Comment by jpnurmi** [comment]
org.gnome.SessionManager.Reboot() works
[Screencast from 2022-09-23 18:29:50.webm](https://user-images.githubusercontent.com/140617/192008772-84262c6a-e8dd-42f3-9b9f-9b1d1d721ee1.webm)
