### ISSUE TITLE
Failed to start Flutter on wayland 

### ISSUE THREAD

**Issue by Ethran** [ubuntu-flutter-community/software#267]
After installing via snap: 
```
 sudo snap install snap-store --channel=preview/edge
 ```
 on Ubuntu 22.04 with all updates applied app is throwing error:
   ```
 ** (software:127930): WARNING **: 19:58:06.101: Failed to start Flutter renderer: No GL implementation is available
 ```
and displays empty window:
![image](https://user-images.githubusercontent.com/77555700/192031048-202fa481-2284-4107-bedd-0011370de875.png)

Issue does not appear using X11, there is one error, and everything is ok:
```
/usr/share/libdrm/amdgpu.ids: No such file or directory
```
Using version v0.1.3-alpha downloaded from github there is no errors thrown into terminal, and application is working ok. 
I also tested on Ubuntu 22.10 wayland,  with application installed via snap and it is working ok.

I am using laptop with dual graphics - integrated AMD and NVIDIA (ideapad 5 Pro-14ACN6 Laptop - Type 82L7)

**Comment by Feichtmeier** [comment]
Hi @Ethran 
Thanks for your report

So it could be assumed that the combination of the AMD GPU driver inside 22.04 and snaps using flutter could cause this error?

To be sure did you have your integrated AMD graphics or the Nvidia graphics active when the snap version of this app had this error at start?

**Comment by Ethran** [comment]
I was using AMD graphics to lunch application, turning off Nvidia graphics in bios does not help.

I don't know how to lunch it using Nvidia GPU:
I have tried lunching it using dedicated Nvidia graphics: right click on application and option "lunch using discrete graphics card". Same result - empty window. But checking in nvidia-smi it shows: "No running processes found". 


### It might be related:
Sometimes during update it throws warning about AMD GPU. Here are those warning running prime-select commend: 

```
wiktor@wiktor-IdeaPad-5-Pro-14ACN6:~$ sudo prime-select nvidia
[sudo] password for wiktor: 
Info: selecting the nvidia profile
Deleting /lib/modprobe.d/nvidia-runtimepm.conf
Updating the initramfs. Please wait for the operation to complete:
/W: Possible missing firmware /lib/firmware/amdgpu/yellow_carp_gpu_info.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vangogh_gpu_info.bin for module amdgpu
\W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_rlc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_mec2.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_mec.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_me.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_pfp.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_ce.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_sdma1.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/cyan_skillfish_sdma.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_mes.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/navi10_mes.bin for module amdgpu
Done
```

**Comment by Feichtmeier** [comment]
Thanks for the additional information.
To further decrease the amount of potential reasons for this problem could you try to install one of the following snap apps built with flutter?

```bash
sudo snap install flutter-gallery
sudo snap install elements
``` 

![grafik](https://user-images.githubusercontent.com/15329494/192111381-b6d39b43-9d12-429e-a421-89f2ce7b5869.png)

and see if the app starts with your amd gpu?

**Comment by Ethran** [comment]
Same effect:
![image](https://user-images.githubusercontent.com/77555700/192112393-b9a16e86-af8a-4fb3-9fe5-2e90d4db70a5.png)

## flutter-gallery
```

(flutter_gallery:37020): Gtk-WARNING **: 20:03:21.500: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(flutter_gallery:37020): Gtk-WARNING **: 20:03:21.502: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(flutter_gallery:37020): Gtk-WARNING **: 20:03:21.503: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name

** (flutter_gallery:37020): WARNING **: 20:03:23.025: Failed to start Flutter renderer: No GL implementation is available
```

## elements
[elements.txt](https://github.com/ubuntu-flutter-community/software/files/9639314/elements.txt)

**Comment by Feichtmeier** [comment]
Okay, even this is a horrible bugs it seems to be related to snaps and amd gpus with flutter
see https://github.com/flutter/flutter/issues/76178

In my opinon this is a really bad problem for this and future flutter snaps
CC @kenvandine @jpnurmi

**Comment by kenvandine** [comment]
@Ethran can you please test the latest build in the preview/edge channel?

**Comment by Ethran** [comment]
I did a fresh install on external drive. I chose minimal installation, and didn't install nvidia drivers. After running command to update snap-store i got error message:
```
test@test-IdeaPad-5-Pro-14ACN6:~$ sudo snap refresh snap-store --channel=preview/edge
[sudo] password for test: 
error: cannot perform the following tasks:
- Run configure hook of "snap-store" snap if present (run hook "configure": 
-----
cannot update snap namespace: cannot create symlink in "/usr/share/libdrm/amdgpu.ids": existing file in the way


snap-update-ns failed with code 1
-----)

```
[amdgpu.ids](https://github.com/ubuntu-flutter-community/software/files/9693141/amdgpu.ids.txt)

removing all snaps and reinstalling snapd have fixed problem. 
After that snap-store (on Wayland) lunched without problems.

I suppose that error that I have on main Ubuntu system might be related to fact that in first place I installed Ubuntu 21.10 and then updated to Ubuntu 22.04 LTS.

**Comment by Feichtmeier** [comment]
Wow, thanks @Ethran for your deep investigation! Let's see how we can make other avoid this situation 😸
