### ISSUE TITLE
ExplorePage: Packagekit search is slower than snap search

### ISSUE THREAD

**Issue by soumyatheman** [ubuntu-flutter-community/software#270]
The app search speed is very slow for debian packages, compare to the snap packages. ~~It takes almost a minute or more to load.~~

**Comment by Feichtmeier** [comment]
Hi @soumyatheman 
I agree that it is slower than the snap search
But I can not say that it takes minutes
While the snap search is 1-2 seconds, packagekit search is like 2-5 seconds

[Bildschirmaufzeichnung vom 25.09.2022, 08:53:05.webm](https://user-images.githubusercontent.com/15329494/192132006-71af1c6c-b113-4e4f-98a5-3d0153ae547e.webm)

**Comment by soumyatheman** [comment]
You're right sir, but is that fixable?

**Comment by Feichtmeier** [comment]
Well well, we use packagekit.dart which "only" uses packagekit on the system, which uses dbus.
The deb search here is already much faster from *my* impression than in gnome software
It is ofc not ideal that the snap search is much faster than the packagekit search
But searching can't be really cached if you search online. I mean how do you want to predict what the user will type in?
I fear this is max search performance for packagekit :shrug: 
I personally think that 2-3 seconds for basically random input is quiet fast, even if snap search is kinda lightning fast

Eventually the author of packagekit.dart could say something more intelligent than me :)
CC @robert-ancell

**Comment by soumyatheman** [comment]
I am sorry, I was in brave forum, discussing about the native messaging, that now works in firefox-snap very well. BTW, can you give me some detailed sources about dart programming and the learning curb for it.

**Comment by jpnurmi** [comment]
A couple of commonly used techniques that may help:
- debounce searches to avoid spinning off a new search operation for every key store
- cancel a previous transaction that may be still ongoing to avoid piling up search operations

**Comment by jpnurmi** [comment]
## Current
<details><summary>diff</summary>

```diff
diff --git a/lib/services/package_service.dart b/lib/services/package_service.dart
index 31e9b09..1228a42 100644
--- a/lib/services/package_service.dart
+++ b/lib/services/package_service.dart
@@ -604,6 +604,9 @@ class PackageService {
     Set<PackageKitFilter> filter = const {},
   }) async {
     if (searchQuery.isEmpty) return [];
+    print('searching "$searchQuery"...');
+    final sw = Stopwatch();
+    sw.start();
     final List<PackageKitPackageId> ids = [];
     final transaction = await _client.createTransaction();
     final completer = Completer();
@@ -621,6 +624,8 @@ class PackageService {
       filter: filter,
     );
     await completer.future;
+    print(
+        'searched "$searchQuery" (${ids.length} packages) in ${sw.elapsedMilliseconds}ms');
 
     return ids;
   }
```
</details>

```
flutter: searching "p"...
flutter: searching "py"...
flutter: searching "pyt"...
flutter: searching "pyth"...
flutter: searching "pytho"...
flutter: searching "python"...
flutter: searched "p" (36962 packages) in 2606ms
flutter: searched "py" (6343 packages) in 3370ms
flutter: searched "pyt" (5963 packages) in 4030ms
flutter: searched "pyth" (5945 packages) in 4514ms
flutter: searched "pytho" (5945 packages) in 5186ms
flutter: searched "python" (5945 packages) in 5789ms
```

## With cancel
<details><summary>diff</summary>

```diff
diff --git a/lib/services/package_service.dart b/lib/services/package_service.dart
index 31e9b09..3677257 100644
--- a/lib/services/package_service.dart
+++ b/lib/services/package_service.dart
@@ -599,28 +599,44 @@ class PackageService {
     setReposChanged(true);
   }
 
+  PackageKitTransaction? _search;
+
   Future<List<PackageKitPackageId>> findPackageKitPackageIds({
     required String searchQuery,
     Set<PackageKitFilter> filter = const {},
   }) async {
     if (searchQuery.isEmpty) return [];
+    await _search?.cancel();
+    print('searching "$searchQuery"...');
+    final sw = Stopwatch();
+    sw.start();
     final List<PackageKitPackageId> ids = [];
-    final transaction = await _client.createTransaction();
+    _search = await _client.createTransaction();
     final completer = Completer();
-    transaction.events.listen((event) {
+    _search!.events.listen((event) {
       if (event is PackageKitPackageEvent) {
         final id = event.packageId;
         ids.add(id);
       } else if (event is PackageKitErrorCodeEvent) {
       } else if (event is PackageKitFinishedEvent) {
+        switch (event.exit) {
+          case PackageKitExit.cancelled:
+            print('cancelled "$searchQuery" in ${sw.elapsedMilliseconds}ms');
+            break;
+          case PackageKitExit.success:
+            print(
+                'searched "$searchQuery" (${ids.length} packages) in ${sw.elapsedMilliseconds}ms');
+            break;
+        }
         completer.complete();
       }
     });
-    await transaction.searchNames(
+    await _search!.searchNames(
       [searchQuery],
       filter: filter,
     );
     await completer.future;
+    _search = null;
 
     return ids;
   }
```
</details>

```
flutter: searching "p"...
flutter: searching "py"...
flutter: searching "pyt"...
flutter: cancelled "py" in 55ms
flutter: cancelled "p" in 442ms
flutter: searching "pyth"...
flutter: searching "pytho"...
flutter: cancelled "pyth" in 76ms
flutter: searching "python"...
flutter: cancelled "pytho" in 54ms
flutter: searched "pyt" (5963 packages) in 1056ms
flutter: searched "python" (5945 packages) in 1358ms
```

**Comment by Feichtmeier** [comment]
Nice! Thank you!
Would you like to make a pull request with this change?

**Comment by jpnurmi** [comment]
Hmm, the code is buggy. :) Multiple transactions may still get started in parallel because `createTransaction()` is asynchronous. It should be somehow [synchronized](https://pub.dev/packages/synchronized) so that only the last entry goes through.

**Comment by soumyatheman** [comment]
> Well well, we use packagekit.dart which "only" uses packagekit on the system, which uses dbus. The deb search here is already much faster from _my_ impression than in gnome software It is ofc not ideal that the snap search is much faster than the packagekit search But searching can't be really cached if you search online. I mean how do you want to predict what the user will type in? I fear this is max search performance for packagekit shrug I personally think that 2-3 seconds for basically random input is quiet fast, even if snap search is kinda lightning fast
> 
> @soumyatheman could you change your issue description? It is seconds, not minutes. :)
> 
> Eventually the author of packagekit.dart could say something more intelligent than me :) CC @robert-ancell

[Screencast from 26-09-22 09:49:17 AM IST.webm](https://user-images.githubusercontent.com/72045785/192193844-0d257c1d-b5b1-4628-954e-109df048deb2.webm)

**Check this out please**

**Comment by Feichtmeier** [comment]
> > Well well, we use packagekit.dart which "only" uses packagekit on the system, which uses dbus. The deb search here is already much faster from _my_ impression than in gnome software It is ofc not ideal that the snap search is much faster than the packagekit search But searching can't be really cached if you search online. I mean how do you want to predict what the user will type in? I fear this is max search performance for packagekit shrug I personally think that 2-3 seconds for basically random input is quiet fast, even if snap search is kinda lightning fast
> > @soumyatheman could you change your issue description? It is seconds, not minutes. :)
> > Eventually the author of packagekit.dart could say something more intelligent than me :) CC @robert-ancell
> 
> Screencast.from.26-09-22.09.49.17.AM.IST.webm
> 
> **Check this out please**

snap search is almost instant

[Bildschirmaufzeichnung vom 26.09.2022, 06:56:52.webm](https://user-images.githubusercontent.com/15329494/192196831-39322a32-ba95-48c5-903c-dac8985b3b9c.webm)

packagekit is def. slower, but still bearable imo

In terms of snap it must be something with your setup

As you could see from the conversation we are looking for ways to debounce the search input and cancel previous search on new input for packagekit

**Comment by soumyatheman** [comment]
> > > Well well, we use packagekit.dart which "only" uses packagekit on the system, which uses dbus. The deb search here is already much faster from _my_ impression than in gnome software It is ofc not ideal that the snap search is much faster than the packagekit search But searching can't be really cached if you search online. I mean how do you want to predict what the user will type in? I fear this is max search performance for packagekit shrug I personally think that 2-3 seconds for basically random input is quiet fast, even if snap search is kinda lightning fast
> > > @soumyatheman could you change your issue description? It is seconds, not minutes. :)
> > > Eventually the author of packagekit.dart could say something more intelligent than me :) CC @robert-ancell
> > 
> > 
> > Screencast.from.26-09-22.09.49.17.AM.IST.webm
> > **Check this out please**
> 
> snap search is almost instant
> Bildschirmaufzeichnung.vom.26.09.2022.06.56.52.webm
> 
> packagekit is def. slower, but still bearable imo
> 
> In terms of snap it must be something with your setup
> 
> As you could see from the conversation we are looking for ways to debounce the search input and cancel previous search on new input for packagekit

I got it now I guess. During any update of snaps, they'll not work. Cause back then firefox was updating in the background automatically.

**Comment by Feichtmeier** [comment]
> > > > Well well, we use packagekit.dart which "only" uses packagekit on the system, which uses dbus. The deb search here is already much faster from _my_ impression than in gnome software It is ofc not ideal that the snap search is much faster than the packagekit search But searching can't be really cached if you search online. I mean how do you want to predict what the user will type in? I fear this is max search performance for packagekit shrug I personally think that 2-3 seconds for basically random input is quiet fast, even if snap search is kinda lightning fast
> > > > @soumyatheman could you change your issue description? It is seconds, not minutes. :)
> > > > Eventually the author of packagekit.dart could say something more intelligent than me :) CC @robert-ancell
> > > 
> > > 
> > > Screencast.from.26-09-22.09.49.17.AM.IST.webm
> > > **Check this out please**
> > 
> > 
> > snap search is almost instant
> > Bildschirmaufzeichnung.vom.26.09.2022.06.56.52.webm
> > packagekit is def. slower, but still bearable imo
> > In terms of snap it must be something with your setup
> > As you could see from the conversation we are looking for ways to debounce the search input and cancel previous search on new input for packagekit
> 
> I got it now I guess. During any update of snaps, they'll not work. Cause back then firefox was updating in the background automatically.

I don't think this is related to snap changes in progress. I can refresh snaps and still search:

[Bildschirmaufzeichnung vom 26.09.2022, 08:25:05.webm](https://user-images.githubusercontent.com/15329494/192207409-b39e8354-9f3f-43cb-8d1f-a24f201b128b.webm)

**Comment by Feichtmeier** [comment]
@soumyatheman 

that packagekit search is slower than snap search is a fact I can not change in this app
Could you check if the recent improvements by JP brought it to a performance you would accept? Otherwise we might need to transfer this issue to packagekit.dart instead I think

**Comment by soumyatheman** [comment]
Okay, I am trying to build that version and check that out

**Comment by soumyatheman** [comment]
So, after a lot of searches, I found out the best solution. The solution by JPnurumi, may have some changes, but on every test I got that changed one was taking 4.85s to search as to 2.43s in the existing one. The main culprit, is the auto check for updates. Stop the auto check for updates, until someone clicks on the update button, the check for update should not be triggered. For slow speed internets, that is a real deal.

**Comment by Feichtmeier** [comment]
> So, after a lot of searches, I found out the best solution. The solution by JPnurumi, may have some changes, but on every test I got that changed one was taking 4.85s to search as to 2.43s in the existing one. The main culprit, is the auto check for updates. Stop the auto check for updates, until someone clicks on the update button, the check for update should not be triggered. For slow speed internets, that is a real deal.

you are correct! Can reproduce this. The package_service is not able to open multiple streams to packagekit it seems :thinking: 

Thank you for your persistence
