### ISSUE TITLE
unable to install/open software app on kde Neon 5.25 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by srkrishnan1989** [ubuntu-flutter-community/software#280]
unable to install/open software app on kde Neon 5.25 (Ubuntu 20.04)

terminal output is  
```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./software.sh)
```
I try to install libc6 by
```
 sudo apt-get install libc6

```
terminal output is  

```
libc6 is already the newest version (2.31-0ubuntu9.9).
libc6 set to manually installed.
```

**Comment by Feichtmeier** [comment]
Hi @srkrishnan1989 

Did you use the snap or from the build?

For 20.04 I would rather use this app from snap as eventually the flutter Linux deps are different in 20.04 compared to 22.04

```
killall snap-store
sudo snap refresh snap-store --channel=preview/edge
```

**Comment by srkrishnan1989** [comment]
hi @Feichtmeier 

Just I  downloaded from https://github.com/ubuntu-flutter-community/software/archive/refs/tags/v0.1.2-alpha.zip

unzip it and opened software_v0.1.2-alpha folder 

double clicked software file nothing happed

rename software as software.sh and open konsole( kde terminal) run ./software.sh

terminal output is
```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./software.sh)
```

**Comment by Feichtmeier** [comment]
> 

Please don't if you use 20.04
Use the snap-store snap to test the app in 20.04

```
killall snap-store
sudo snap refresh snap-store --channel=preview/edge
```
