### ISSUE TITLE
No themeing is available

### ISSUE THREAD

**Issue by hsbasu** [ubuntu-flutter-community/software#294]
This is probably a long due issue of `snapd`. Still I am mentioning here. I cannot change the theme for snap-store. For example, I tried installing the theme `dg-adw-gtk3-theme` from store followed by the command `for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i dg-adw-gtk3-theme:gtk-3-themes; done`. But nothing happened.

**Comment by Feichtmeier** [comment]
This is really not for the repositories

This is a flutter app
It uses yaru.dart
Which makes this app adapt to the themes available in Ubuntu 22.04+ by default

You could add this to yaru.dart if you want even though I'm not sure we can handle it the way you like
What's possible is to read the primary colour of gtk themes and create a yaru based flutter theme on the fly

Closing
