### ISSUE TITLE
[Feature Request] Flatpak support

### ISSUE THREAD

**Issue by hsbasu** [ubuntu-flutter-community/software#30]
Please add flatpak support for better UX.

**Comment by Feichtmeier** [comment]
I don't think this would improve the user experience for Ubuntu users, if you mean this with UX.

This app should stay as performant as possible, adding more package formats than snap and deb/rpm is eventually one of the reasons why gnome software is so slow. Flatpak is also out of scope for me currently and I am personally not interested in this package format. So TL,DR: not going to happen currently, sorry.

**Comment by Adithyan007hack** [comment]
Bro add flatpak support because most of user prefer flatpak over snap and they need to use this software other than Ubuntu, like for Ubuntu derivatives also 
you are just favouring the Ubuntu core users only saying Ubuntu just default over snap

**Comment by madsrh** [comment]
@Adithyan007hack Please read the comment above 👆 
It's already a huge challenge to support two package formats (debs and snaps), adding a third, no matter if it's flatpak or whatever, would be a nightmare.

You are ofc welcome to fork the project 😃

**Comment by Feichtmeier** [comment]
> Bro add flatpak support because most of user prefer flatpak over snap and they need to use this software other than Ubuntu, like for Ubuntu derivatives also you are just favouring the Ubuntu core users only saying Ubuntu just default over snap

1) I am not your bro.
2) We created this application specifically for Ubuntu. So prio 1 were snaps, and prio 2 are debs. 
3) I don't think you have any valuable statistics about what Ubuntu users fav, no matter in how many comment sections you were sucked into.
4) This is open source.

👋
