### ISSUE TITLE
ExplorePage: add categories to frontpage

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#301]
Here's a few ideas (not sure if this belongs in _Discussions_). If any of these are worth keeping, let's split it into a separate issue.

- Add a few apps from each category to the explore frontpage
- Add a _Show more_ text button to each category
- Show a checkmark for already installed apps
- Rename **My Apps** in the sidebar to **Installed** because a snap doesn't have to be an application
- Rename the label in the searchbar: **All** refers to **search all categories** so perhaps this would be better
- Maybe add an additional filter: say you're in _Games_ and want them listed by Most downloaded, New releases, Last updated, Only from trusted developers

![image](https://user-images.githubusercontent.com/3986894/192650428-6d753c35-22da-48e5-8b8c-10ea936725ea.png)

**Comment by Feichtmeier** [comment]
On the myapps thing:

Before we change any of this we need to decide what we want to show
Even if some non apps slipped through filters I didn't use correctly, I would not show anything else than apps.
If one wants to fiddle with content snaps or Debian libs she can use the command line
IMO

The rest.... Yeah those gathering issues are really hard. As you can see even answering them is hard :/
