### ISSUE TITLE
PackageInstaller needs to work in the snap

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#302]
We do not discuss this very often :laughing: but the app also has the feature to install local debian files from the file manager
Looks like this... 
![grafik](https://user-images.githubusercontent.com/15329494/192797253-35ce985a-3d39-41b9-90d4-ae3262cb017d.png)

Install / Uninstall works fine

When I start the app from the snap-store command in the cli, packagekit gives an error:

![grafik](https://user-images.githubusercontent.com/15329494/192797567-8fed63a7-4af2-4728-bd3e-df56208a783a.png)

```bash
frederik@carbon:~/Downloads$ snap-store google-chrome-stable_current_amd64.deb 
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.PackageKit.Transaction.NoSuchFile: File google-chrome-stable_current_amd64.deb is not found or unsupported
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1131)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      PackageKitTransaction.getDetailsLocal (package:packagekit/src/packagekit_client.dart:1030)
<asynchronous suspension>
#3      PackageService.getDetailsAboutLocalPackage (package:software/services/package_service.dart:661)
<asynchronous suspension>

Unsupported modifier, resource creation failed.
XXX: resource creation failed
```

Any idea why this happens in the snap but not with the local binary?
CC @kenvandine 

Classes used for this are here:
https://github.com/ubuntu-flutter-community/software/tree/main/lib/package_installer

Here:
https://github.com/ubuntu-flutter-community/software/blob/ed77278b0e417997eb8a2757ddd8adb4846d8bbb/lib/services/package_service.dart#L643-L687

And in main.dart
https://github.com/ubuntu-flutter-community/software/blob/main/lib/main.dart

**Comment by Feichtmeier** [comment]
@oSoMoN any idea why the package installer is not starting as a snap?

**Comment by Feichtmeier** [comment]
Oh this works better - no errors are displayed
However it does not install the deb

https://user-images.githubusercontent.com/15329494/198837930-0ecd3ab0-b5d6-4d33-b687-5eaee75e9300.mp4

Hmmm, deb installation does not work anymore, even when built from snap
Maybe some  of the recent package service changes broke this

**Comment by oSoMoN** [comment]
It works for me here, when I test with the deb package in `integration_test/assets/`.
Does installing that deb work with `pkcon install-local`?

**Comment by Feichtmeier** [comment]
> It works for me here, when I test with the deb package in `integration_test/assets/`. Does installing that deb work with `pkcon install-local`?

asset works with the installer but not des that worked before the model/service rework, like 
https://tytel.org/helm/
or
https://harmonoid.com/downloads/

Yes I can install those debs with okcon or dkpg
