### ISSUE TITLE
[Feature Request] category sidebar

### ISSUE THREAD

**Issue by hsbasu** [ubuntu-flutter-community/software#31]
1. [x] Is it possible to add a categories sidebar for faster navigation?

**Comment by Feichtmeier** [comment]
Explore page in in explore mode
![grafik](https://user-images.githubusercontent.com/15329494/173398705-de7de7ce-c952-40b1-a287-dc4283148104.png)

Explore page in categories mode
![grafik](https://user-images.githubusercontent.com/15329494/173398826-34585755-f5ca-4bdd-b044-a54bccf922f0.png)

did you actually run the app? :thinking:

**Comment by hsbasu** [comment]
Pardon me for the brief and non-informative request. I meant putting the categories on the side. I think I saw such in Deepin maybe. But may be its better where they are. Another option I felt missing is the tool-tips on apps. As the app icons do not show app name its really tough to browse for the required app.

**Comment by Feichtmeier** [comment]
Tooltips is a nice idea

The main navigation moves to the bottom bar when the window widths moves under a threshold. I will try the sidebar categories for the wide layout and post a screenshot :)

**Comment by hsbasu** [comment]
Being a newcomer, I would list a few features that might be helpful.

**Comment by Feichtmeier** [comment]
Update: the categories selection is now merged with the searchbar.
![grafik](https://user-images.githubusercontent.com/15329494/183240516-c15be7e3-6d61-4f73-b7f8-ce92df69b4bd.png)
![grafik](https://user-images.githubusercontent.com/15329494/183240556-7d20929b-f234-4e90-bead-3996c708c6b2.png)
When you click it a scrollable popup with all categories appears where you can select the category /section (that's how they are called for snaps)

**Comment by hsbasu** [comment]
Looks pretty cool. I'll test it when I am free and give feedback. Thanks for the hard work.
