### ISSUE TITLE
Tweak responsive layout for app page

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#312]
On the "frontpage" the main container has a fixed position. On the app page the main container is moving right, down and is stretched as you resize the window.

Could we, like the frontpage, use a fixed position and after a certain width (in my example below it's 1220px) then center the content?

![image](https://user-images.githubusercontent.com/3986894/193155348-14a32fcb-edbb-40e6-bc42-85801d48b4f3.png)

It's a bad description of the issue, so I've made a very quick mockup 😁 Does this make sense @Feichtmeier ? I'll tag @anasereijo for comments

https://user-images.githubusercontent.com/3986894/193156542-dfd3f27a-c0e4-428d-b3c7-6a017b600e44.mp4

**Comment by madsrh** [comment]
Sorry for all the back and forth @Feichtmeier - I just discovered that you actually [posted a screenshot from Windows 10](https://github.com/ubuntu-flutter-community/software/issues/226#issuecomment-1250699070) 😃 this is exactly what I was trying to communicate.


https://user-images.githubusercontent.com/3986894/193338318-c7519562-b955-4ffe-8af0-ac667e0bce9d.mp4

This is the part that shouldn't be moving 👇 

https://user-images.githubusercontent.com/3986894/193339652-c1228b26-89eb-4fd4-a80b-e796e1f009d4.mp4

**Comment by Feichtmeier** [comment]
Maybe this is going down to personal preference, but I think I prefer the thing we did up there to windows11, even if we were heavily inspired by it :D The little space at the left and the huge space on the right looks weird to me

**Comment by madsrh** [comment]
> Maybe this is going down to personal preference...

Absolutely! 

>  The little space at the left and the huge space on the right looks weird to me

I wanted no space all the time 😄 I'm not sure what you mean here, but it's fine 👍

BUT I noticed that the latest master, switches to the wide view much later now - that worked better before. Perhaps it should switch at the same time as the wide sidebar (icons + label)?

I also noticed that there's a cut off here: 

![image](https://user-images.githubusercontent.com/3986894/193342105-003965a9-8472-4c89-bd66-a2870efba6e2.png)

And again, sorry for making you spend your time on makeup 💄 / no essential stuff.

**Comment by Feichtmeier** [comment]
is this a 4k screen with 100% scaling?

**Comment by madsrh** [comment]
> is this a 4k screen with 100% scaling?

yes

**Comment by Feichtmeier** [comment]
What I meant is that it looks weird that on the left there is this static one page header and on the right side everything expands to eternity. The text becomes really long and we also place the permission pane there so the space  between the text and the switches becomes really long
Anyways!
Please try it with 200% scaling in settings then
WE can't design the UI around those super crazy constraints of a 4k screen without UI scaling
I've gone almost too far by looking how it looks on a 2,5k screen without any scaling. That's when Paul saw that it started to look weird on FHD screen.
Is this master btw? Or an old screenshot from the PR?

**Comment by Feichtmeier** [comment]
Also it is cut of because the right side is a scoll pane where more stuff can be placed (like on your windows11 screenshot ;) )

**Comment by madsrh** [comment]
Yes, this is master.

>  it is cut of because the right side is a scroll pane where more stuff can be place

Yes it is scrollable and that's a bit weird because it (the containers) has the full height of the window when the window isn't as wide. Yeahhhh, I know, it's totally confusing to try and explain this 😄 ...and non critical, so let's leave it for now and revisit when we can point and a screen in the same room 😉

**Comment by Feichtmeier** [comment]
I am not insisting on this specific padding or layout. If you come up with a nice improvement to the current wide layout (left appheader, which has always the same amoutn of widgets, thus fixed edges top and bottom... right the scrollpane, which is needed because you neither know how long the description is nor how many permissions are needed, they are always different)

an alternative would be if both the description and the permission container would be scrollable themselves and the right pane could have pinned edges. But I am not really thinking that this is better than the current iteration

**Comment by Feichtmeier** [comment]
And did you try the gnome settings scaling on your 4k screen? :P please do!
