### ISSUE TITLE
Will this repo support Hacktoberfest?

### ISSUE THREAD

**Issue by guyluz11** [ubuntu-flutter-community/software#315]
Hacktoberfest 2022 has just started.

https://hacktoberfest.com

I was wondering if this repo will support Hacktoberfest, for that to happen it should just add `hacktoberfest` Topic

![image](https://user-images.githubusercontent.com/9304740/193067041-6e85ffa5-797f-40c8-8894-2d097e66e037.png)

And add the label `hacktoberfest-accepted` to accepted pull requests.

**Comment by Feichtmeier** [comment]
Hi @guyluz11 thanks for the idea, I fear this might not fit well into your current start of this project. We are currently sorting things out, building workflows and teams. Eventually next year if the design is more set in stone
