### ISSUE TITLE
Enhancement suggestion: Instead of libhandy or flutter window, use libadwaita

### ISSUE THREAD

**Issue by soumyatheman** [ubuntu-flutter-community/software#331]
Ubuntu officially ships Gnome and libadwaita is the latest toolkit from Gnome, So why not use that? It'll make the app more coherent with rest of the System, also libadwaita looks very good. The bindings are available for flutter.[
Libadwaita bindings for Flutter](https://pub.dev/packages/libadwaita)

**Comment by Feichtmeier** [comment]
It's not that easy
Flutter uses gtk3 as a child window (kinda)
The only thing we need libhandy for is the rounded bottom corners
Everything else you see in the UI is neither gtk3, gtk4 or anything, it's flutter with yaru.dart

You might want to check out some videos how this all works, for example this one
https://www.youtube.com/watch?v=996ZgFRENMs
👋
