### ISSUE TITLE
Scrolling sometime lags in the snap description page and other places

### ISSUE THREAD

**Issue by keshavbhatt** [ubuntu-flutter-community/software#332]
Ubuntu 20.04.5 LTS
Version: 0.1.4-alpha

How to reproduce:
- Open any snap from listing (make sure the snap has a long scrollable description)
- Try to scroll through the description widget several time (I tried with my laptop track-pad with two finger scroll)
- Notice the random lag, sometime the widget is not even responding to the scroll

I also noticed scroll lag on other scrollable widgets like list of Licenses and their content.

**Comment by Feichtmeier** [comment]
Performance will ofc not be as good as on my screen but here is a screen recording with no lag at all

https://user-images.githubusercontent.com/15329494/193401586-ddffa712-e173-4aa1-9dd4-5c97356e3567.mp4

I fear I need more information because I can not reproduce nor did I see such an issue
Maybe I need to check 20.04

Did you run it from the snap-store (preview/edge) snap? Or from source?

**Comment by keshavbhatt** [comment]
I will provide more details once i will be back home.

**Comment by keshavbhatt** [comment]
I run snap-store from snap install preview/edge channel version is 0.2.0-alpha

I found exactly when it happens. I am using my laptop track-pad dual finger scroll and **I noticed when I scroll over app's description it stop scrolling**, I need to move my mouse to other widgets to resume scroll the page.

**Comment by Feichtmeier** [comment]
> I run snap-store from snap install preview/edge channel version is 0.2.0-alpha
> 
> I found exactly when it happens. I am using my laptop track-pad dual finger scroll and **I noticed when I scroll over app's description it stop scrolling**, I need to move my mouse to other widgets to resume scroll the page.

Thanks. Yeah I've noticed it too
I think this is me messing up with the singlechild scrollview in one of our design iterations :D Will fix it next week

**Comment by keshavbhatt** [comment]
Another place where i noticed similar behaviour is: explore page

Steps to reproduce:
- Scroll the page where the snaps are listed
- Stop in the middle when your pointer is over a list item widget
- Try to resume the scroll -> here you will notice the scrolling wont resume.

  I don't know how this thing works on flutter, but I think we need to pass the mouse scroll event to scrollview instead of listitem widget.

**Comment by Feichtmeier** [comment]
It's just a thing they changed in flutter 3.3 and you need to be a bit more aware where and how to set the scroll controller.
