### ISSUE TITLE
Use shimmer effect for loading content

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#344]
For all pages (Explore, MyApps, AppPage) it would be nice to have a shimmer effect for loading content, instead of spinning indicators.
We could use this package for this

https://pub.dev/packages/shimmer

![](https://raw.githubusercontent.com/hnvn/flutter_shimmer/master/screenshots/loading_list.gif)

**Comment by jkerola** [comment]
I couldn't find any design examples, so I made a few quick suggestions using the linked package and taking preset values from `YaruBanner`. I'd like to try and implement this, if a design is agreed upon.

![white_blank](https://user-images.githubusercontent.com/44394305/193839492-73e23888-0e41-4f2c-8b2b-a1ac03da73c5.png)
![white_fill](https://user-images.githubusercontent.com/44394305/193839500-ef788875-15dd-4736-aa46-3168299acad6.png)
![white_outline](https://user-images.githubusercontent.com/44394305/193839503-af9eb6e0-4e3f-4bf4-8899-503e9899947d.png)

**Comment by Feichtmeier** [comment]
The first one looks solid!

Let's see what the design thinks 
CC @anasereijo @elioqoshi @madsrh

**Comment by Jupi007** [comment]
The loading banner should look as close as possible to the loaded one.
So imo, the second one is the best, but maybe with three thinner text like container.

**Comment by madsrh** [comment]
> The loading banner should look as close as possible to the loaded one...

+1 but there might still be design changes, so I would not spend a ton of time fine-tuning this - better just get it in the IMO

**Comment by Jupi007** [comment]
> > The loading banner should look as close as possible to the loaded one...
> 
> +1 but there might still be design changes, so I would not spend a ton of time fine-tuning this - better just get it in the IMO

You're right 👍

So maybe do the simplest model possible: the first one, and add a TODO comment (and an issue) to remember to make the placeholder looks like the target content, once the design is stabilised.

**Comment by Feichtmeier** [comment]
> As @Jupi007 mentioned above, the loading skeleton should be similar to the loaded content, as it gives users a visual cue that content is being loaded. 
> 
> @Feichtmeier – will it be possible to load progressively the content as it becomes available? I believe that's the purpose of having a skeleton screen.
> 
> 

Yes we could load the skeleton 🦴 thing first then slowly fill it up with results for example
Or we could use the skeleton for when the snap names are loaded but not yet the images (which is hardly visible with medium internet speed, but still. Maybe 1 second)
