### ISSUE TITLE
Controls in header bar disappear

### ISSUE THREAD

**Issue by fthx** [ubuntu-flutter-community/software#345]
Hi,

After start-up:

![image](https://user-images.githubusercontent.com/23138504/193551266-5bf858f8-292c-407e-bfd1-5480d5c8a40f.png)

Then after few seconds, they are back.

**Comment by Feichtmeier** [comment]
DUplicate of #235 :)

**Comment by fthx** [comment]
Okkkaaaayyyy, was not trivial to check this dup, hum?
^_^
