### ISSUE TITLE
Store is offline on VPN connection

### ISSUE THREAD

**Issue by d-loose** [ubuntu-flutter-community/software#361]
When connected to a VPN `connectivity_plus` falsely reports `ConnectionType.mobile` due to a [bug](https://github.com/fluttercommunity/plus_plugins/issues/1166) I just reported - this causes `StoreModel` to think we're offline since it requires either `ConnectionType.wireless` or `ConnectionType.ethernet`.

**Comment by Feichtmeier** [comment]
Thanks! Anything we could go here to band aid fix?

**Comment by jpnurmi** [comment]
you could use nm.dart directly :)

**Comment by d-loose** [comment]
Are you excluding `ConnectionType.mobile` in case it's a metered connection? In that case I'd also suggest using nm.dart, which can test that [directly](https://pub.dev/documentation/nm/latest/nm/NetworkManagerClient/metered.html).

**Comment by Feichtmeier** [comment]
> Are you excluding `ConnectionType.mobile` in case it's a metered connection? In that case I'd also suggest using nm.dart, which can test that [directly](https://pub.dev/documentation/nm/latest/nm/NetworkManagerClient/metered.html).

No just because I was being stupid :smile:
