### ISSUE TITLE
Set up Weblate for translations

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu-flutter-community/software#362]
This will make it easier for translators to contribute.

**Comment by oSoMoN** [comment]
I created https://hosted.weblate.org/projects/ubuntu-software/.

Can someone (@Feichtmeier ?) with admin access on this project [set up the Weblate webhook](https://docs.weblate.org/fr/weblate-4.14.1/admin/continuous.html#github-setup)?

**Comment by Feichtmeier** [comment]
@oSoMoN thanks!

I gave you admin rights - is it ok if you do it?

**Comment by oSoMoN** [comment]
Sure, thanks!

**Comment by oSoMoN** [comment]
This is done. I have added missing translations for French, and they are pending a push to github (in the form of a PR), but I haven't found how to request an ad-hoc push. So I'll wait until the push happens automatically to confirm that everything works as expected, and to close this issue.

I will also update the README.md and CONTRIBUTING.md documents to link to Weblate.

**Comment by Feichtmeier** [comment]
Thank you!

**Comment by oSoMoN** [comment]
It looks like this worked: #364

**Comment by Feichtmeier** [comment]
Very nice
