### ISSUE TITLE
No Auto updates refresh on start-up?

### ISSUE THREAD

**Issue by fthx** [ubuntu-flutter-community/software#369]
Hi,

I don't find auto refresh good.
That's all.
^_^
Well, maybe that's just my opinion. :-))

Maybe it would be interesting as an option in parameters tab?
Is this feature blocked using some metered connections?

**Comment by Feichtmeier** [comment]
Would you rather activate it if a user select the update tab?

**Comment by fthx** [comment]
Yes, or simply using the 'refresh' button?
Maybe that's my Synaptic-mind-depends!
Very often I open your software without the need to refresh repositories (e.g. just to searh some software).
Does this 'refresh' button refresh the snap updates too?

**Comment by Feichtmeier** [comment]
No it only refreshs packagekit packages

We are reworking the whole update trigger mechanism with #348 
You are right and this should probably only be done on system login or return from suspend or after a period of time

I add this to the other issue as a checkbox
