### ISSUE TITLE
PackageInstaller: add an open with option in nautilus

### ISSUE THREAD

**Issue by fthx** [ubuntu-flutter-community/software#371]
Hi,

I don't find Ubuntu Software in available apps to install a deb package?
Is this intended or not yet implemented?

**Comment by Feichtmeier** [comment]
It is implemented you currently need to run the app with a deb as the first argument
The snap has an issue though which is being tracked in #302 

Maybe we can rename this issue to 
"PackageInstaller: add an open with option in nautilus"?

**Comment by Feichtmeier** [comment]
Note to myself

https://askubuntu.com/questions/317392/how-to-add-a-custom-program-to-open-with-list-of-programs-in-xubuntu-13-04-ho
