### ISSUE TITLE
SnapService calls SnapdClient.loadAuthorization() too many times

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu-flutter-community/software#393]
This should probably be called only once, when the service is initialized.

**Comment by oSoMoN** [comment]
Get some rest, and get better soon!

The `loadAuthorization()` method loads an existing authentication macaroon from disk. By default macaroons [don't have an expiry date](https://dashboard.snapcraft.io/docs/reference/v1/macaroon.html#expiry) except for those that were created for specific, privileged API methods (in which case they expire one year after being created, unless specified otherwise).

In fact common snap operations (listing, finding, installing, removing) don't require such a macaroon at all. The policykit dialog you're getting that requests your password is a different mechanism.

**Comment by Feichtmeier** [comment]
Thanks for clarifying 😊
Then kill it with fire 🔥 😂
