### ISSUE TITLE
Disppose YaruCarouselControllerIssue Title

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#404]
════════ Exception caught by widgets library ═══════════════════════════════════
A YaruCarouselController was used after being disposed.
════════════════════════════════════════════════════════════════════════════════

**Comment by Jupi007** [comment]
I think I encountered the same issue some times ago.
But I have been unable to reproduce it after.
I was supposing it was a problem related to the hot reload thing.

Oh and I don't think it is related to this app, but more to the carousel widget, as I encountered it in `yaru_widgets`.
But do you know how to reproduce it?
