### ISSUE TITLE
PackageService leaks transaction event stream subscriptions

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu-flutter-community/software#411]
There's a recurring pattern in `PackageService` to listen to transaction events without ever closing the stream subscription:
```dart
final transaction = await _client.createTransaction();
transaction.events.listen(...);
...
```

I'd suggest enabling the [cancel_subscriptions](https://dart-lang.github.io/linter/lints/cancel_subscriptions.html) lint _and_ always handling the return value of `Stream.listen()`:
![image](https://user-images.githubusercontent.com/140617/196945014-a5a4f390-001c-45a9-a3aa-baa4a9e73810.png)

**Comment by Feichtmeier** [comment]
@oSoMoN since you are working also on the other issue in PackageService I thought it would be best to assign this one also to you to now create two conflicting PRs :) Hope this is ok?

**Comment by oSoMoN** [comment]
Sure!
