### ISSUE TITLE
Cannot refresh snap-store snap from preview/edge to latest revision

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu-flutter-community/software#420]
I'm at revision 655. When refreshing to the latest (revision 657), I consistently get this error:

    error: cannot perform the following tasks:
    - Exécuter la configuration du point d'accroche du paquet Snap "snap-store" s'il est présent (run hook "configure": 
    -----
    cannot update snap namespace: cannot create symlink in "/usr/share/libdrm/amdgpu.ids": existing file in the way
    snap-update-ns failed with code 1
    -----)

**Comment by Feichtmeier** [comment]
Updated on a different machine and me too!
Any idea what could have caused this from the last commits?

**Comment by marekmarecki** [comment]
Had the same issue today when tried to switch to preview/edge channel. Seems to be related: 07c5642b06fa9bfc61bace6e1850670716ad4104 ?
It seems the error is telling the truth. I have an existing file under that path

**Comment by Feichtmeier** [comment]
Oh hm
@kenvandine can we revert this commit?
