### ISSUE TITLE
[Feature Request] Updates page: compact list view

### ISSUE THREAD

**Issue by ricjcs** [ubuntu-flutter-community/software#424]
It would be nice if there was an option to show the list of updates more compactly. This facilitated the visualization, mainly when there are dozens of updates.

**Comment by Feichtmeier** [comment]
@ricjcs would you prefer if there would just be a "there are 35468 updates" + fancy image... ->update/ view details?
Or just a compact list of selectable tiles?

**Comment by ricjcs** [comment]
I thought of something like this:

![ubtuntu-software-mockup](https://user-images.githubusercontent.com/11923491/197825745-b3e0090f-e2bf-4d1c-a892-ea791943f74b.jpg)

**Comment by Feichtmeier** [comment]
@ricjcs could you refresh from snap and see if you think that the redesign of this page makes it still necessary to have a compact view?

**Comment by ricjcs** [comment]
I think this way is very good! The compact list was just an idea that I thought would look good, but I also like this redesign. I think the "select all" button is also much better this way! Thanks. Finally Ubuntu Software is going to be amazing!

**Comment by Feichtmeier** [comment]
Cool! Thank you! :)
Feedback like this is important to get the focus on UI parts that are not good to use
Closing for now 👍
