### ISSUE TITLE
Align text + icon when switching "page"

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#432]
#nitpicking #enhancement

When switching "page" the position of the icon and text changes. 

Current:
![before](https://user-images.githubusercontent.com/3986894/197644102-fac66595-bc65-40cd-a35e-de6cca288029.gif)

(better) Aligned:
![after](https://user-images.githubusercontent.com/3986894/197644149-98bf68d7-2c70-4c9b-a49c-84d54eec827b.gif)

**Comment by Feichtmeier** [comment]
@madsrh 

I can not move the title further to the back button than this
![grafik](https://user-images.githubusercontent.com/15329494/199522386-a094d9b8-fafb-4e69-9534-e2b1c600226f.png)

Is this okay or should we also move the search icon to the position the back button is?

**Comment by madsrh** [comment]
I think it's okay. Is there a branch I can try?
The current master just looks like it's jumping around for no reason - it's a bit disturbing / "chaotisch" IMO.

**Comment by Feichtmeier** [comment]
Yeah I just forgot to upload because I felt asleep @.@
This is a trivial non-critical change (1 line) so I merge and if it is not okay you can re-open :) :+1:
