### ISSUE TITLE
PackageInstaller: convert to be just an argument for PackagePage?

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#459]
@oSoMoN since you've merged the two models - WDYT about removing this "packageinstaller" dir alltogether and converting the package installer to be "only" a package as the argument for a PackagePage ?

**Comment by oSoMoN** [comment]
Sounds good to me. Does that mean getting rid of the `LiquidLinearProgressIndicator` widget?

**Comment by Feichtmeier** [comment]
> Sounds good to me. Does that mean getting rid of the `LiquidLinearProgressIndicator` widget?

That's np 😃
The fancy thing is still in the update view
