### ISSUE TITLE
Use appstream.dart to search for packages (instead of packagekit.dart)

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu-flutter-community/software#464]
This is related to #444.
I had a chat with @robert-ancell, and he advised to use [appstream.dart](https://pub.dev/packages/appstream) to search for packages, instead of packagekit.dart. This is how search is implemented in gnome-software.
This will allow us to perform search queries while a package is being installed/removed.

**Comment by Feichtmeier** [comment]
Ah, cool!

Also roughly related to
#128

**Comment by oSoMoN** [comment]
This is unfortunately blocked on https://github.com/canonical/appstream.dart/issues/15.

**Comment by Feichtmeier** [comment]
Yep : /  I guess we need to live without Icons for classic packages until its fixex

**Comment by Feichtmeier** [comment]
Fixed with #567 thanks to @oSoMoN :heart:
