### ISSUE TITLE
PackageInstaller: include version matching when checking if the package is installed

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#471]
When you load a package with the packageinstaller the app needs also to check if the app versions are different.
If the loaded package is an update of the currently installed version the button should show "update" rather than "remove"

This is also a very annoying problem with the current gnome software version in stable. You can only upgrade apps like discord that do not setup a ppa with the terminal.

@oSoMoN any idea how this can be done?

**Comment by oSoMoN** [comment]
I'll need to research it.
