### ISSUE TITLE
Updates page ideas

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#479]
### Discussed in https://github.com/ubuntu-flutter-community/software/discussions/357

<div type='discussions-op-text'>

<sup>Originally posted by **madsrh** October  5, 2022</sup>

- [x] #480

![_updates](https://user-images.githubusercontent.com/3986894/193939443-f29258eb-97b7-4b94-9a5e-b41a26dcc40b.jpg)

I've moved the checkboxes to the left side like [this example](https://material.io/components/checkboxes). Expanded:
![_updates2](https://user-images.githubusercontent.com/3986894/193939583-5159661e-fcb8-421f-a21e-513220107a12.jpg)

- [ ] #564

It would be really cool if new releases would get a "banner" by grabbing the latest artwork from the Ubiquity slideshow [here](https://bazaar.launchpad.net/~ubiquity-slideshow/ubiquity-slideshow-ubuntu/html/view/head:/slideshows/ubuntu/slides/screenshots/welcome.png). If it can't connect, there's would ofc be a fallback image.
![upgrade-available2](https://user-images.githubusercontent.com/3986894/193937857-c9cdadb1-3f9a-49f0-af01-7faa4545bc80.jpg)

- [x] #481

While installing updates, some advanced users may want to following along in the "command-line". Inside _Settings_ there should be an option to enable this (so the expand arrow > is really unnecessary here since the user have actively enabled this).

![updages-details](https://user-images.githubusercontent.com/3986894/193938874-d2e8b3a2-df3d-4633-8355-764ee6616ff6.jpg)
</div>

- [ ]  Keep terminal output after update has finished #502

**Comment by anasereijo** [comment]
@Feichtmeier with the merge of both pages, I think we can close this
