### ISSUE TITLE
Updates page: hide update list in expandable

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#480]

**Comment by Feichtmeier** [comment]
I think this also superseeds #424

**Comment by Feichtmeier** [comment]
@madsrh 

I took your mock-up and changed it a bit more:

![grafik](https://user-images.githubusercontent.com/15329494/199586612-e5530e20-7fe2-47f7-a66c-5d6d54534ae0.png)
![grafik](https://user-images.githubusercontent.com/15329494/199586667-2377f796-0042-4c4e-847f-ec27aeba0a9c.png)
![grafik](https://user-images.githubusercontent.com/15329494/199587021-340d668a-22d0-4004-ace9-922753785055.png)


https://user-images.githubusercontent.com/15329494/199587229-25c287d9-f27e-4975-9c46-a69ef7c0bf5b.mp4

WDYT?

**Comment by madsrh** [comment]
> ...and changed it a bit more:

What did you change?

This looks fantastic, BUT I'm missing the option to _select all_ without expanding the list. Is that what you've changed? 😺

**Comment by Feichtmeier** [comment]
Yes well maybe I can combine it to 

![grafik](https://user-images.githubusercontent.com/15329494/199599104-228af509-108b-48f7-b592-ee159bcec264.png)

Then you click the header

![grafik](https://user-images.githubusercontent.com/15329494/199599170-49fe7f97-5750-4a17-ae93-4825e6607367.png)

Otherwise the header has two meanings "expand to see" and "select all" which is a bit hard to understand

**Comment by Feichtmeier** [comment]
Ok maybe better english

1) 
![grafik](https://user-images.githubusercontent.com/15329494/199600981-789847eb-dae0-4f30-a7f2-ee299af20490.png)

2) 
![grafik](https://user-images.githubusercontent.com/15329494/199601021-c5f43b16-1213-4c51-9399-5c41209e616f.png)

**Comment by Feichtmeier** [comment]
okok I think now I got it :P 

![grafik](https://user-images.githubusercontent.com/15329494/199603582-34fe5b2d-bb8b-4022-9bee-38e0f243c14b.png)

![grafik](https://user-images.githubusercontent.com/15329494/199603623-829edf66-5f3c-4262-a394-328c6cdece76.png)

![grafik](https://user-images.githubusercontent.com/15329494/199603647-bcfff226-705e-4d44-b7d9-6f583e4fa1bc.png)

**Comment by madsrh** [comment]
I totally see your point with the being two meanings "expand to see" and "select all" 

This parent was what I had in mind
![image](https://user-images.githubusercontent.com/3986894/199604826-9dcbc030-c905-4ed4-850c-6899fe8873e5.png)

**Comment by Feichtmeier** [comment]
Yeah you are right - so you mean like this?


https://user-images.githubusercontent.com/15329494/199607187-6f48618b-27ff-4413-be84-76dbeb8cba15.mp4

**Comment by Jupi007** [comment]
One thing I think interesting in @madsrh screenshot is the undetermined checkbox when not all updates are selected :)

**Comment by madsrh** [comment]
Yeah, I think just changing the wording fixes this 👍

**Comment by Feichtmeier** [comment]
Even though logically everything makes sense now
Wasn't one of your ideas to display something fancy instead of boring 😜 details and then if the user wants he can click to see the details?

**Comment by madsrh** [comment]
> Wasn't one of your ideas to display something fancy instead of boring 😜 details and then if the user wants he can click to see the details?

I'm not sure what you mean 🤔 What fancy? Do you mean for the release upgrade?

It would be nice to have the total filesize (if possible) like in the initial mockup.

BTW I see that you've already changed the label, but it could also work with a mix: "11 available updates selected". Is that better or worse? 😆

**Comment by Feichtmeier** [comment]
Ok will do tomorrow
I feel that we're close ;p
Maybe some fancy image at the top also

**Comment by Feichtmeier** [comment]
Morning @madsrh @Jupi007 :coffee: 

Referring to mads intial mock-up I mean this fancy image

![grafik](https://user-images.githubusercontent.com/15329494/199677209-48d659fd-6111-4bc8-90cf-797b02f0ed03.png)

![grafik](https://user-images.githubusercontent.com/15329494/199677249-d2ccd17c-04af-4725-ad68-188cf22c3262.png)

![grafik](https://user-images.githubusercontent.com/15329494/199677299-881ecc73-375d-43e5-9355-a5d19a1c7c8a.png)

**Comment by Jupi007** [comment]
Honestly, the fullcolor icon + the large title looks really good. As you said it adds a bit of fancy, which makes the ui less boring 🙂

My only suggestions on these images are: increase a little the space between icon/title/updates, and add a mixed checkbox when not all updates are selected (yes I insist a little with that 😆).

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/199681094-37701c24-99e6-4f07-aa98-ee2a6b0b7c2f.png)

![grafik](https://user-images.githubusercontent.com/15329494/199681140-171162b8-850b-4d7c-bc96-f78a3bbac6ed.png)

![grafik](https://user-images.githubusercontent.com/15329494/199681515-5e6c010d-ddb9-4944-a184-05502392ccdc.png)


![grafik](https://user-images.githubusercontent.com/15329494/199681398-319e3eb7-71a3-4a95-b852-2a36d4905af4.png)

?

**Comment by Jupi007** [comment]
This looks fine imo 👌

**Comment by madsrh** [comment]
Nice @Feichtmeier I would prefer the horizontal style like in the mockup 👇  But I'm guessing you've changed it for a reason 😉 

♻️  _We've got updates for you_


And ofc a package with a checkmark when no updates

**Comment by Feichtmeier** [comment]
Ah when no updates are there, we have this fancy animated icon by Paul - don't you remember? :older_adult:

**Comment by madsrh** [comment]
> don't you remember?

I ALWAYS have updates so I've never seen it 😆

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/199683528-4a2712b3-09cc-4ed6-a47e-a6e4594a7096.png)

Made the slogan correct-mads-english :monocle_face: and a bit smaller?
Can we go with this?

**Comment by madsrh** [comment]
🎉👍

**Comment by madsrh** [comment]
> Then you can finally see Paul's animation!

I was only joking 🧡 

This looks good 👍  Can't wait to get home and giving it a try - I've never been this excited about installing updates 🤣

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/199690783-0cf3ee23-59ec-49a4-a8e6-365a9a1803ab.png)

?

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/199704079-15b0047d-65a1-4fe9-85cf-10f74d37e8d9.png)
