### ISSUE TITLE
Do not show Canceling the authentication popup error

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#488]
This error message is unnecessary in cases where the user presses cancel in the popup. Just return the window as before.

I'm not sure if there exists other use cases where packagekit can fail to obtain authentication and we do want an error message. If so, it would need some styling.

![image](https://user-images.githubusercontent.com/3986894/199787675-1bc5d2c4-74c4-4bb2-b647-be2cef6598a0.png)

![image](https://user-images.githubusercontent.com/3986894/199787699-9a970be2-b041-491b-b8e1-d539efd51c92.png)

**Comment by Feichtmeier** [comment]
> This error message is unnecessary in cases where the user presses cancel in the popup. Just return the window as before.
> 
> I'm not sure if there exists other use cases where packagekit can fail to obtain authentication and we do want an error message. If so, it would need some styling.
> 
> ![image](https://user-images.githubusercontent.com/3986894/199787675-1bc5d2c4-74c4-4bb2-b647-be2cef6598a0.png)
> 
> ![image](https://user-images.githubusercontent.com/3986894/199787699-9a970be2-b041-491b-b8e1-d539efd51c92.png)

Yeah this toast/snackbar just displays all errors related to packagekit :)
I did not yet filter unimportant (like this) from important errors!

**Comment by Feichtmeier** [comment]
Fixed with #504
