### ISSUE TITLE
Only load the featured apps tint colours one time after opening the app

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#5]
this tint color calculation for urls sounds like a heavy operation that involves both downloading images and probably reading through the image data pixel by pixel for the final calculation of unknown complexity? one could even break this down to a service-like unit of its own that internally maintains a [cache](https://pub.dev/documentation/quiver/latest/quiver.cache/MapCache-class.html) to avoid unnecessary recalculation. :)

_Originally posted by @jpnurmi in https://github.com/ubuntu-flutter-community/software/pull/4#discussion_r884131661_

**Comment by jpnurmi** [comment]
For example:
```dart
import 'package:palette_generator/palette_generator.dart';
import 'package:quiver/collection.dart';

class SurfaceTintColorGenerator {
  final _cache = Cache<String, Color>();

  Future<Color?> generate(String url) {
    return _cache.get(
      url,
      ifAbsent: (url) async {
        final image = NetworkImage(url);
        final generator = await PaletteGenerator.fromImageProvider(image);
        return generator.dominantColor?.color;
      },
    );
  }
}
```
