### ISSUE TITLE
Don't color caret 

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#500]
The caret should use the text color, rather than the selection color.

<img width="295" alt="Skærmbillede 2022-11-10 kl  14 32 04" src="https://user-images.githubusercontent.com/3986894/201105000-f075ba9e-6dba-4bb4-8295-251c0af78ef1.png">

**Comment by madsrh** [comment]
Issue 500 🎉

**Comment by Feichtmeier** [comment]
You feel ready for this after the flutter workshop @madsrh ? :)

It's 

https://github.com/ubuntu-flutter-community/software/blob/b729567e21b0dfa81648f0fa23a69f2ff0119422/lib/store_app/explore/search_field.dart#L67

setting the _color_ property to Theme.of(context).colorScheme.onSurface should do it :)

**Comment by Jupi007** [comment]
I thought we had already fixed that in yaru.dart 🤔

**Comment by madsrh** [comment]
:sob: I can't make your code work :-1: 

I can set it like this: ```color: Color.fromARGB(255, 170, 222, 25),``` but that really isn't the right solution :/

**Comment by Feichtmeier** [comment]
> :sob: I can't make your code work :-1: 
> 
> I can set it like this: ```color: Color.fromARGB(255, 170, 222, 25),``` but that really isn't the right solution :/

Yes I've read your issue wrong. Caret should be fixed in yaru.dart

**Comment by madsrh** [comment]
> Yes I've read your issue wrong. Caret should be fixed in yaru.dart

Actually IMO it's both the caret and the icon that shouldn't be colored. Look at Nautilus, search in VScode or GitHub and so on, it's always just black/white :)

**Comment by Feichtmeier** [comment]
I personally don't look at nautilus as design references
I think the color is a great indication that you currently focus the text input
But since some of the yaru colors are problematic on the dark theme, like this olive, feel free to change it with the code snippet above

**Comment by madsrh** [comment]
> I personally don't look at nautilus as design references

I knew you were going to say that 😆 What I meant to say was, that I can't think of any other search that does this.

> I think the color is a great indication that you currently focus the text input

Right, but isn't the big orange line acting as a "focusring" for the text field? The icon is actually stronger (easier to see) when it is deselected because of the color. The caret feels odd to me, but let's leave the icon for now.

>  feel free to change it with the code snippet above

I've spent sooooo much time today trying to do a color that respects the theme variant (which the ```Color.fromARGB``` ofc doesn't) 💩 😿 

I'll leave it to the professionals, so feel free to close this issue, change the color only if you agree, or you can assign the issue to @Jupi007 😆

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu/yaru.dart/pull/229
