### ISSUE TITLE
Update checking reports an error with a file:// URL

### ISSUE THREAD

**Issue by mz2** [ubuntu-flutter-community/software#503]
Clicking on "Refresh" on the Updates page results in the following error message on my Kinetic system with 0.2.0-alpha installed:

 ![image](https://user-images.githubusercontent.com/71363/201399436-64ef59e0-19eb-4433-aeb6-049e26efe296.png)

I am guessing this is because of the apt repo with a file:// URL

Let me know if you want more info from my system! Thanks for an awesome app.

**Comment by Feichtmeier** [comment]
@mz2 thanks for the report :smiley_cat: 

Did the refresh still work?
Might be just our packagekit service to be a bit too verbose

**Comment by Feichtmeier** [comment]
@mz2

could you refresh snap-store to 0.2.2-alpha and see if you still have this problem?

**Comment by mz2** [comment]
Works great now! Thank you for such a fast response.

**Comment by Feichtmeier** [comment]
Yw!
