### ISSUE TITLE
SnapPage: show what change is in progress

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#517]
It would be better to show the user what change is in progress.
One question I have to designers is how verbose we should be here.

Snapd has a localized summary of the snap change, which is cool, but maybe this is too much? Especially the connect summaries can be really long, because they include the interfaces, plugs and slots :smile: 

![grafik](https://user-images.githubusercontent.com/15329494/201705036-2732cb7e-db79-43bc-9bd1-6abb7bf63fc2.png)

Simple version would be 
![grafik](https://user-images.githubusercontent.com/15329494/201705794-585c4fdd-56fd-4913-8bba-6998f8f3ecab.png)

it's german, but it says "Changing permissions"

For remove it would just say "Remove"
![grafik](https://user-images.githubusercontent.com/15329494/201706077-7b5fdd66-18c7-4f18-9665-9b4d8e443173.png)

WDYT @madsrh @anasereijo ?

**Comment by whiskeyPeak** [comment]
Very small nit, but wouldn't it conform better if instead of "remove" it said "removing"? This makes it use the same tense as "changing permissions".

**Comment by madsrh** [comment]
IMHO the simple output is better indeed. 

> Very small nit, but wouldn't it conform better if instead of "remove" it said "removing"? This makes it use the same tense as "changing permissions".

+1 I had the same exact thought.

**Comment by Feichtmeier** [comment]
> Very small nit, but wouldn't it conform better if instead of "remove" it said "removing"? This makes it use the same tense as "changing permissions". 

Absolutely!

**Comment by madsrh** [comment]
The advanced info would be helpful if someone was trying to debug an issue, like the install freezing, but I'm guessing there will be a log somewhere for that?

**Comment by Feichtmeier** [comment]
> The advanced info would be helpful if someone was trying to debug an issue, like the install freezing, but I'm guessing there will be a log somewhere for that? 

Yeah let's not leak development into the UI 🙂

**Comment by Feichtmeier** [comment]
Merged it with @whiskeyPeak recommended translations
