### ISSUE TITLE
Clicking within an app listing page causes snap-store to navigate back

### ISSUE THREAD

**Issue by Nightmayr** [ubuntu-flutter-community/software#547]
This is pretty easy to reproduce, if you go into any app page and click on the app icon for example, you should see that you will be returned to the previous page. This happens in other parts of the page as well, or even when unsuccessfully doing a text selection in the app description.

I suspect this bug came about with the introduction of the gesture to navigate back https://github.com/ubuntu-flutter-community/software/commit/a68987d614526b2cc2893dfa0c14d957916874c9. The gesture is a good idea but I guess some more work might be needed on the implementation.

**Comment by Feichtmeier** [comment]
Fixed in preview/edge, please refresh your snap
