### ISSUE TITLE
Switch text on updating page

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#548]
Could we switch these? IMO the action (decompressing) is more important than the name of the file.

![Ikke-navngivet-1](https://user-images.githubusercontent.com/3986894/203171314-0e965427-740d-4e24-8c19-644986f806cf.gif)

**Comment by madsrh** [comment]
> Feichtmeier assigned madsrh

Now this won't be fixed 😅

**Comment by Feichtmeier** [comment]
Remember the workshop :P
