### ISSUE TITLE
Improve dropdown titles for explorepage

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#549]
Rename "The package format of applications" to "All package types" (when both debs and snaps are selected).

Rename "Search all" to "All categories"

<img width="398" alt="Skærmbillede 2022-11-21 kl  23 36 10" src="https://user-images.githubusercontent.com/3986894/203171983-05e896c1-e465-4ccd-8a5f-022c9708745e.png">

**Comment by Feichtmeier** [comment]
This string comes from when it was inside the search 🔍 input
Replacing the translations is not good for our translators
But we can create a new string for this

**Comment by madsrh** [comment]
> Replacing the translations is not good for our translators
But we can create a new string for this

Alright, let's create a new one 👍

BUT wouldn't that just mean that we leave an unused string? Which would be annoying for new translators that spend time translating a string that isn't used anywhere. I think it would be best to remove it, to keep the file as small/clean as possible. A change like this must be expected when translating alpha software.

**Comment by Feichtmeier** [comment]
It's already translated
Plus I thought about adding it back to the search input

**Comment by madsrh** [comment]
> Plus I thought about adding it back to the search input

In that case it makes totally sense ☺️

**Comment by Feichtmeier** [comment]
In general it's nice to have a bunch of options
Often I can reuse some when we try new things
