### ISSUE TITLE
Quit confirm dialog could be improved

### ISSUE THREAD

**Issue by Jupi007** [ubuntu-flutter-community/software#551]
![Capture d’écran du 2022-11-21 20-48-32](https://user-images.githubusercontent.com/36476595/203262928-c9eee208-6355-4cd4-b44f-fdef19564945.png)

In this situation, an user which doesn't read the dialog (we all know there's a lot like this 😅), will surly click on the **Confirm** button, which is the dangerous action, because only the **Cancel** button is red.

Imo, this dialog can be improved in many ways to avoid that kind of mistake from the user:
- Make the **Confirm** button red, and rename it in **Quit** ;
- Remove red accent from **Cancel** button ;
- Disable the **Confirm/Quit** button during a short time, so the user will be forced to read the dialog content.
- Maybe also invert the buttons positions, as an "user which doesn't read" will automatically click on the right button, maybe it is a good idea to put the **Cancel** button at this position.

**Comment by madsrh** [comment]
**+1**

> Disable the Confirm/Quit button during a short time, so the user will be forced to read the dialog content.

This one I'm a little skeptical about 🤔 This would be highly annoying 😆 

Like this?

![Ikke-navngivet-1](https://user-images.githubusercontent.com/3986894/203269498-a3ee5823-9931-4417-8f39-e882d9682d3d.gif)

**Comment by Jupi007** [comment]
Yes, just like this :)
And it is annoying, but it is the goal.

You have the same behaviour on firefox, when you want to open a downloaded file. The **open** button is disabled during about 2s so the user will not instantly click on it.
Same on the nintendo switch, if you want to remove a save or a software, the confirm red button is disabled during a few second.

**Comment by Feichtmeier** [comment]
Good idea
I copy pasted it from settings

**Comment by madsrh** [comment]
@Jupi007 What do you think about centering the layout, using a filled button and removing the headerbar line?
I would have liked the _Attention_ to be larger, but that would mean creating another string for translations. WDYT?


![image](https://user-images.githubusercontent.com/3986894/204061268-7bdb0dde-2953-4718-b906-34cc864d3b42.png)

Two strings and no title in the headerbar 👇 

![image](https://user-images.githubusercontent.com/3986894/204061470-add50575-d6c3-44ec-a1b3-b329d1ab2836.png)

**Comment by Jupi007** [comment]
I think I have the same opinion as you @madsrh.
I really prefer you second proposal :)

**Comment by Jupi007** [comment]
@Feichtmeier Do we really need a generic confirm dialog widget?
Because, I currently modified the current widget to still be generic, but it adds a lot of complexity to have different level of dialog action (positive, neutral, negative, dangerous...).
As this dialog is only used one time in the project, I think it would be better to just have a `QuitConfirmDialog` widget.
WDYT?

**Comment by Feichtmeier** [comment]
I personally don't care how it is named or parameterized I just didn't want the users to break their system when updating :D
Don't let the size of the changes in one pr escalate though please

**Comment by Jupi007** [comment]
Closed by #570
