### ISSUE TITLE
Add an option to return to the other packageformat if it exists from the Snap/Packagepage

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#561]
Even if I do not like this idea semantically, I see no other room on the pages other than the dropdown for SnapPage

![grafik](https://user-images.githubusercontent.com/15329494/203487729-0865849f-66a3-47dd-9d3d-463e7aca7203.png)

For PackagePage a simple button "Switch to Snap" would be enough
![grafik](https://user-images.githubusercontent.com/15329494/203488051-19901776-9ac1-40ef-87bb-ffbc291d84ba.png)

**Comment by madsrh** [comment]
Do you mean like this? or perhaps [with a label](https://user-images.githubusercontent.com/3986894/203498254-55123dbf-eea7-499f-a329-01df0f852601.jpg)

![change-format](https://user-images.githubusercontent.com/3986894/203498241-42d85f2a-d7bf-4f89-bcae-f0653650b752.jpg)

If possible, I think it would be best no to have a button on one page and a popup/dropdown on the other. Can we use a popup/dropdown on the PackagePage too?

![image](https://user-images.githubusercontent.com/3986894/203498164-6e431e13-1764-41bb-ba3f-bd9f4de2f1fb.png)

**Comment by madsrh** [comment]
> Or just a normal button that forwards you to the deb page. So you can keep the navigation intact

Toggle buttons / [segmented buttons](https://m3.material.io/components/segmented-buttons/overview)

![image](https://user-images.githubusercontent.com/3986894/203848331-8681c9f5-7def-4538-88ea-ae17b025b443.png)

**Comment by Feichtmeier** [comment]
Woops, it's not really closed unless you guys say so, but the functionality is there. But I started with an outlined button because this is much easier with the navigator because it is now

banner > snap + deb > click > snap page first > switch to deb button > deb page
                                                                                   
then
                               
                                                 appbanner  <   snap page   <    back button

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/207702281-210b3f71-93fb-4c73-a2d7-10f795370a9f.png)

**Comment by anasereijo** [comment]
> ![grafik](https://user-images.githubusercontent.com/15329494/207702281-210b3f71-93fb-4c73-a2d7-10f795370a9f.png)

Hey @Feichtmeier thanks for sharing the screenshot. I wonder if it's not possible to do the switch button as we [proposed](https://github.com/ubuntu-flutter-community/software/discussions/523#discussioncomment-4285840)?

**Comment by Feichtmeier** [comment]
It is possible but it does not make so super much sense since you navigate from page to page. It's not really a state of one page but a navigation from one page to the other. If you really insist on the toggle I can do it but in my humble opinion it does not make too much sense from the feel of navigation

**Comment by madsrh** [comment]
> It is possible but it does not make so super much sense since you navigate from page to page. It's not really a state of one page but a navigation from one page to the other. If you really insist on the toggle I can do it but in my humble opinion it does not make too much sense from the feel of navigation

Good point @Feichtmeier. I think @anasereijo wants to give the illusion that the content is loaded dynamically (even if it's an entirely different page) so the container (with the name, icon,...) stays the same. Or at least what was what I understood 😁

**Comment by anasereijo** [comment]
> > It is possible but it does not make so super much sense since you navigate from page to page. It's not really a state of one page but a navigation from one page to the other. If you really insist on the toggle I can do it but in my humble opinion it does not make too much sense from the feel of navigation
> 
> Good point @Feichtmeier. I think @anasereijo wants to give the illusion that the content is loaded dynamically (even if it's an entirely different page) so the container (with the name, icon,...) stays the same. Or at least what was what I understood 😁

yes @madsrh that's exactly it! As we show the apps as one banner (on search results and explore page), it makes it look like it's one 'page' dedicated to the same app and then the user can select to see either the snap or deb.

**Comment by anasereijo** [comment]
@Feichtmeier is this already available to try it out?

**Comment by Feichtmeier** [comment]
Yes, should be usable after

sudo snap refresh snap-store

**Comment by Feichtmeier** [comment]
I would like to add that package formats are no secret in Linux land and we soldz not try to hide them or abstract them away

**Comment by Feichtmeier** [comment]
Another reason to not give the illusion that both apps are the same ( which they are not by any means ), is that you can also install the snap and not the deb, or both, or none, or the deb but not the snap. Little video demonstrating this (where I also found a little layout issue with the button :P )


https://user-images.githubusercontent.com/15329494/208296629-de8c0c8a-d357-4661-aec7-58cdf9cbe5c7.mp4

**Comment by whiskeyPeak** [comment]
There should probably also be a "switch to Snap" button if the user is currently on the deb version of a package. :D

**Comment by Feichtmeier** [comment]
Yeah def a good idea to show the format on the AppPage - maybe in the AppBar?

GIMP (snap)
GIMP (debian)

or with icons?

Anyways, those buttons are also unfinished I just wanted to point out that I think that the illusion of "one app" is a bad idea and we need the navigation for "muscle memory" that you switch the app format

**Comment by Feichtmeier** [comment]
https://user-images.githubusercontent.com/15329494/208445340-c05db3ec-749a-4510-a9d5-c386d35fef13.mp4

**Comment by anasereijo** [comment]
Hi @Feichtmeier, first of all, happy new year!

I am sorry, but I don't understand why we can't have the 'switch' button as proposed. Might be easier/quicker to schedule a quick call to discuss this.

**Comment by Feichtmeier** [comment]
@madsrh @anasereijo 

Now in main to test:

![grafik](https://user-images.githubusercontent.com/15329494/210844668-09e5ba1b-b746-4872-b3b9-3b14c75f5e3d.png)

![grafik](https://user-images.githubusercontent.com/15329494/210844698-f0bc9e6d-693c-42b5-ae2b-a892884f44dc.png)

![grafik](https://user-images.githubusercontent.com/15329494/210844803-5a15f025-dfa1-4771-8509-8ccd634a6f61.png)


![grafik](https://user-images.githubusercontent.com/15329494/210844742-765c3472-866a-4321-920d-3b7277602230.png)


![grafik](https://user-images.githubusercontent.com/15329494/210844634-442c89a5-319a-43bd-adc7-df5deb05feea.png)

![grafik](https://user-images.githubusercontent.com/15329494/210844579-26544241-0c0a-4415-be0e-2c3478d96ede.png)

**Comment by Feichtmeier** [comment]
also increased default window size and reduced padding to avoid overflow of the buttons in the "default" size of the window
![grafik](https://user-images.githubusercontent.com/15329494/210879808-70aa2eab-b713-4154-a482-d6afd74a4668.png)

**Comment by madsrh** [comment]
This looks very busy. Too many buttons IMHO. 

![image](https://user-images.githubusercontent.com/3986894/210876327-f57bfeb2-63e3-4e9c-a120-4ee5ae9501e5.png)

I think I would still have preferred a dropdown here (not the _latest/stable_ dropdown though 😉)
Shouldn't the Debian label be white?

I know this is just a test, but switching between the two packageformats has a short blank page (shimmer). Is that fixable somehow (caching the other page)?

**Comment by anasereijo** [comment]
Hey! I am having issues with the update – I don't see the changes. I will try again Monday. 

In the meantime, I have some questions/feedback from what I can see on the screenshots:

- We [prosed moving reviews](https://github.com/ubuntu-flutter-community/software/discussions/523#discussioncomment-4285840) down below, next to the information about the package. So all the content that changes when we switch between Snap and Deb will be below those buttons. We also proposed moving the publisher as well, but we then [agreed](https://github.com/ubuntu-flutter-community/software/discussions/523#discussioncomment-4324153) that it can stay at the top down below the app name.

- I don't see a reason why we display the 'update' button when there are no updates available. Is there a reason why?

- @madsrh is right - the Dedian label should be in white as well

- this is more visual related, but isn't the font for the app name way too big and disproportional with the rest of the content? Maybe if we reduce it a bit, it will help to tidy up the layout.

- 'Uninstall' button should be after the channel dropdown. The same when we have an 'update' button. I have ordered items when I did this [mockup](https://github.com/ubuntu-flutter-community/software/discussions/523#discussioncomment-4285840). 

thank you and have a nice weekend!

Hopefully I can test this on Monday (fingers crossed!)

**Comment by Feichtmeier** [comment]
> This looks very busy. Too many buttons IMHO. 
> 
> ![image](https://user-images.githubusercontent.com/3986894/210876327-f57bfeb2-63e3-4e9c-a120-4ee5ae9501e5.png)
> 
> I think I would still have preferred a dropdown here (not the _latest/stable_ dropdown though 😉)
> Shouldn't the Debian label be white?
> 
> I know this is just a test, but switching between the two packageformats has a short blank page (shimmer). Is that fixable somehow (caching the other page)?
> 
> 

I agree. The more of I use this the more I'm almost sure we should return to the tab approach of snap/deb

But let's keep this approach for now maybe we find something that looks good and is useable for Ubuntu users

On the other points, let's keep this focused on the part that let's you switch between the app format. I'm already getting confused by all the notifications xD

I can remove the update button if there is no update and then we get a bit more space, but as soon as there is an update we still get the crowded row

**Comment by Feichtmeier** [comment]
yes I try this! This super long line is horrible

**Comment by Feichtmeier** [comment]
Even if this looks somehow "ok"

![grafik](https://user-images.githubusercontent.com/15329494/211095272-8f1f9d98-f085-430f-9498-6b477ed23826.png)

This looks really not ok
![grafik](https://user-images.githubusercontent.com/15329494/211095366-681f0f54-edb7-4a5c-8654-bd72d1d764ee.png)
![grafik](https://user-images.githubusercontent.com/15329494/211095448-d66617b1-1ca8-4490-97cd-16239ea0903b.png)

Any other idea than the (snap|deb) button?

**Comment by madsrh** [comment]
> This looks really not ok

Indeed that looks 💩  Could you try centering it below the website link?

![image](https://user-images.githubusercontent.com/3986894/211117730-7fbf8163-cccd-45cc-af93-5b1a58afb32e.png)

**Comment by whiskeyPeak** [comment]
> > This looks really not ok
> 
> Indeed that looks hankey Could you try centering it below the website link?
> 
> ![image](https://user-images.githubusercontent.com/3986894/211117730-7fbf8163-cccd-45cc-af93-5b1a58afb32e.png)

Yeah I agree, this looks much better. Though by positioning those buttons on a new line, we run into this issue again https://github.com/ubuntu-flutter-community/software/issues/688

**Comment by Feichtmeier** [comment]
> > This looks really not ok
> 
> Indeed that looks hankey Could you try centering it below the website link?
> 
> ![image](https://user-images.githubusercontent.com/3986894/211117730-7fbf8163-cccd-45cc-af93-5b1a58afb32e.png)

this is good - any idea for the sm0l window?

**Comment by Feichtmeier** [comment]
eventually we need an exception for these kind of windows anyways
![grafik](https://user-images.githubusercontent.com/15329494/211141432-719c9b28-a4c5-4f85-88c5-3e6184d7af98.png)
I mean, this is a really rare case and I dont know why you would want to do this.
We could prevent this by increasing the min height of the window to for example this size
![grafik](https://user-images.githubusercontent.com/15329494/211141463-561eb882-8ee7-4c4f-a644-630d775688da.png)

**Comment by madsrh** [comment]
> any idea for the sm0l window?

Well, I took the liberty of removing the "Installed date", because this information may be available in the "Additional information" section/widget (if we decide to go with that idea) AND as you said this is a really rare use case.
If this isn't enough space, I would, as already suggested, resize the icon and the title.

![image](https://user-images.githubusercontent.com/3986894/211142001-287fa33a-9243-4cdc-b42d-ed320de8524f.png)

**Comment by Feichtmeier** [comment]
Resizing is good and also move the Infos to their own section on the right, right?

**Comment by madsrh** [comment]
> ...Infos to their own section on the right, right?

🤔 I'm unsure about moving ALL the info. Wouldn't you want some information available without scrolling like version, filesize, ???
 
If there's room I would leave these three and we can revisit when the "additional info" section is done.

**Comment by Feichtmeier** [comment]
depends where we place this. we could place it above the media. currently working on this - looks good - I am optimistic

**Comment by whiskeyPeak** [comment]
Increasing the min window height feels more like placing a bandaid of the issue than actually fixing it head on. It's also worth keeping in mind that a large portion of users still use low resolution displays:

![Screenshot_20230107-101355.png](https://user-images.githubusercontent.com/73116038/211145344-3d490364-131f-49a7-a7bd-8ee541cabd6b.png)

By making the minimum height 870, we basically alienate all these users.
I don't think that changing the size of the title and icon would be enough here. IMO the best solution would be to either place the additional information on the right, or make it scrollable.

**Comment by Feichtmeier** [comment]
yes, it was a band-aid fix just for now, as I said in the PR, no need to diverge this discussion even more ;)

currently working on the app page makeover, please do not panic, everyone relax and drink some beer. Thank you.

**Comment by madsrh** [comment]
@whiskeyPeak Just for reference: telemetry in Ubuntu https://ubuntu.com/desktop/statistics

> ... please do not panic, everyone relax and drink some beer. Thank you.

Still a bit too early for beer 🤣  but I'm completely relaxed ☺️

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/211149168-dea91234-2f69-47e6-903a-a2b40f57f93c.png)

![grafik](https://user-images.githubusercontent.com/15329494/211149348-c23472fe-d2b6-43e4-8c15-7926eb489b47.png)



![grafik](https://user-images.githubusercontent.com/15329494/211149202-94303a50-9316-424a-b442-6d30067c044f.png)

**Comment by madsrh** [comment]
Nice @Feichtmeier ! Much improved 😄  I think you should move the publisher back below the title.

**Comment by Feichtmeier** [comment]
but then the grid is always uneven :) Need to pull some other infos out of the toilet then :flushed: :hankey:

**Comment by madsrh** [comment]
I have no problem with the publishername being shown both places. Yes, please push

There's a lot of spacing, so perhaps we should make it a bit tighter? But then again, this is an unusual huge window 😅 
![image](https://user-images.githubusercontent.com/3986894/211149976-a478b5c0-421c-4b23-8d7a-c3ef54687c6d.png)

**Comment by Feichtmeier** [comment]
@madsrh still did not figure out how to keep scaling but move the elements a bit more to the center, but here is the publisher name for wide and narrow windows

![grafik](https://user-images.githubusercontent.com/15329494/211169700-9404056c-df85-48d0-a1dc-9f9908898d89.png)

![grafik](https://user-images.githubusercontent.com/15329494/211169707-c7707a3f-8cdc-4b74-8301-4ae4eedfac49.png)

Let's wait for ana on monday and see if we can go with this (snap|deb) button now and then we can talk about all of this somewhere else

**Comment by Feichtmeier** [comment]
Fixed by several PRs
