### ISSUE TITLE
UpdatePage: support Ubuntu release upgrades

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#564]
It would be really cool if new releases would get a "banner" by grabbing the latest artwork from the Ubiquity slideshow [here](https://git.launchpad.net/ubiquity-slideshow-ubuntu/tree/slideshows/ubuntu/slides/screenshots/welcome.png). If it can't connect, there would ofc be a generic fallback image.
![upgrade-available2](https://user-images.githubusercontent.com/3986894/193937857-c9cdadb1-3f9a-49f0-af01-7faa4545bc80.jpg)

**Comment by Feichtmeier** [comment]
Note to myself
org.apt.Debiab
Dbus interface

**Comment by Feichtmeier** [comment]
We can now use https://github.com/ubuntu-flutter-community/apt.dart
for this :smile_cat:

**Comment by Feichtmeier** [comment]
I think this would be a good use case for tests ☺️ I didn't think I would ever say this, but here we go. Because upgrading your system is kind of rare and I don't feel like creating X vms

**Comment by Feichtmeier** [comment]
We decided to keep system updates out of the app for the first release and maybe forever so I'd say this has no place as well here, right? @madsrh @anasereijo

**Comment by madsrh** [comment]
> I'd say this has no place as well here, right?

👌 okay

> ... and maybe forever...

I thought this was the plan eventually, but I'm not up to date with the Canonical master plan 🤷‍♂️

**Comment by anasereijo** [comment]
> We decided to keep system updates out of the app for the first release and maybe forever so I'd say this has no place as well here, right? @madsrh @anasereijo

Yes you are right @Feichtmeier. System updates will not be present on this app 👍 thanks for flaggint this
