### ISSUE TITLE
Explorepage: selecting no package format gives error

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#572]
In the popup you can set a checkmark for either Snaps or Debs, but you can also select non which gives an error.
A solution would be to add a thrid option for both package formats and use radiobuttons or use a menu with a checkmark 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/3986894/204146531-099b3ea0-75f9-49aa-9df1-d0fe26ee2fe2.png)
![image](https://user-images.githubusercontent.com/3986894/204148150-168cee3d-105f-42e1-912e-0748df637bc1.png)

<img width="651" alt="error" src="https://user-images.githubusercontent.com/3986894/204146679-77d3614e-bf8d-4fe7-85e9-cc7ca7b18c3d.png">

**Comment by Feichtmeier** [comment]
He woops!
Can be also fixed without the radio but checking the set length. Will fix, sorry about that
