### ISSUE TITLE
Window controls missing on Ubuntu Budgie

### ISSUE THREAD

**Issue by samlane-ma** [ubuntu-flutter-community/software#581]
When installing on Ubuntu Budgie (tested on Kinetic, Lunar, and fresh Jammy install), there are no visible maximize, minimize, or close buttons on the title bar. I have tried multiple themes just in case this was the issue.  I saw other similar issues (https://github.com/ubuntu-flutter-community/software/issues/345, https://github.com/ubuntu-flutter-community/software/issues/330) but they appear to have been resolved.

While I have this problem on every Ubuntu Budgie install, I did not run into this issue on Ubuntu 22.04.

![snapstore2](https://user-images.githubusercontent.com/67085765/204804853-bf020504-925d-4adb-9226-8dc940af495c.png)

**Comment by Feichtmeier** [comment]
HI @samlane-ma thanks for this issue
We've the same problem in mate and linux mint. this is related to the library libhandy which is used inside handy_window

@jpnurmi any idea if this is fixable at all?

**Comment by jpnurmi** [comment]
I'll install Budgie later and give it a try to get a better understanding of what's going on there.

**Comment by samlane-ma** [comment]
Thanks for the fast replies.  Looking into the libhandy comment and playing around a bit, I can make the controls appear if I run it:

`env GTK_CSD=0 snap-store`

**Comment by jpnurmi** [comment]
The missing close button has been fixed in handy_window 0.1.9

- https://github.com/ubuntu-flutter-community/handy_window/pull/13

**Comment by Feichtmeier** [comment]
Awesome, thank you JP!

**Comment by samlane-ma** [comment]
Thanks for the fast fix!  I just did a snap refresh and tested on Budgie (Jammy, Kinetic, and Lunar).  I can confirm that the window controls are present now!
