### ISSUE TITLE
Rename package format dropdown

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#619]
Nitpicking: The wording on the dropdown that says "All types of packages" should be changed to "All package types". This would also match the [wireframes](https://github.com/ubuntu-flutter-community/software/discussions/526#discussioncomment-4255426).

TBH I'm not sure if it's best to ~~create a new string~~ or if changing the current english string is enough. Eg. if you look at the german translation "Alle Pakettypen", that actually already fits with "All package types", so we should be good only changing the english string.

<img width="957" alt="Skærmbillede 2022-12-05 kl  13 01 40" src="https://user-images.githubusercontent.com/3986894/205751164-7bd30795-8d92-4ad9-af3d-c8f93af070bd.png">

**Comment by Feichtmeier** [comment]
change the english string that exist, because the meaning is not changed
