### ISSUE TITLE
On systems without PackageKit, hide deb UI

### ISSUE THREAD

**Issue by robert-ancell** [ubuntu-flutter-community/software#620]
On a system without PackageKit, it would be nice if software would gracefully degrade and remove all the UI elements that aren't necessary if only snaps are used. This occurs on Core Desktop, which doesn't support packages other than snaps.

The existence of PackageKit can be detected by the `DBusServiceUnknownException` exception thrown when calling `PackageKit.Client.connect()`.

**Comment by robert-ancell** [comment]
We could make this clearer by making a `PackageKitNotAvailable` exception in packagekit.dart - does that seem useful?

**Comment by robert-ancell** [comment]
Also technically D-Bus services can come and go. We could detect that but I suspect in this case checking once on startup is sufficient. You can restart the software app in the rare case you decide to enable/disable PackageKit.

**Comment by Feichtmeier** [comment]
Ok we can do this. I would first do #

**Comment by Feichtmeier** [comment]
> We could make this clearer by making a `PackageKitNotAvailable` exception in packagekit.dart - does that seem useful?

yes sounds good :)

**Comment by kenvandine** [comment]
Adding the network-manager plug did fix the specific issue, but we do need to look at making the UI adapt when packagekit isn't available.  For example, we shouldn't display a way to filter on package type since snap is the only package type on that system.

**Comment by Feichtmeier** [comment]
Yeah I was confused when you linked the PR to this issue :P  

I can fix this, just not super fast, since packagekit and appstream started to leak all around into the pages since the design requested to give the illusion of package formats not existing 😸
