### ISSUE TITLE
Add a dark theme toggle and accent colour button in the settings page.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#623]
Some distros don't have a system-wide dark mode implementation (eg: linux mint cinnamon) so the software store ends up in light mode with no way to modify it.

We should add an appearance section in the settings page where those 2 options are customizable. I was thinking it looking somewhat similar to the ubuntu flutter settings app?

![Screenshot from 2022-12-07 00-16-29](https://user-images.githubusercontent.com/73116038/206054297-446403ca-1494-4407-9cca-8a64ba5d0c48.png)

@Feichtmeier Can you assign this to me if it's a feature we want to implement? Thank you :D

**Comment by Feichtmeier** [comment]
@whiskeyPeak ok. But there needs to be an option that says follow system theme

**Comment by madsrh** [comment]
So every app will have their own dark mode settings? 🤔

**Comment by Feichtmeier** [comment]
> So every app will have their own dark mode settings? 🤔

no, but either opt-in to system dark or light

what is common sense on android and some gtk apps is:

- [ ] use what the system uses
- [ ] dark
- [ ] light
