### ISSUE TITLE
Card design tweaks

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#642]
Comment regarding the "cards" from @anasereijo https://github.com/ubuntu-flutter-community/software/discussions/634#discussioncomment-4399142

Publisher name:
- [x] Add publisher name
- [x] Publisher name in italics and lighter grey

Summary:
- [x] Darker text color for summary text

Ratings:
- [x] Add number of ratings is missing from your proposal (still just dummy data)
- [x] Use lighter gray for unselected stars (and ofc darker gray in dark mode)

Packageformat icons:
- [ ] Display icons only for available packageformats. Color the icon that provides the card info. Use disabled light grey for the other (see Ana's comment below)

**Comment by anasereijo** [comment]
@madsrh thanks for creating the issue!

One thing we need to amend in your list:
>Packageformat icons:  Always display both icons and use disabled light grey if one is not available

We only display the available packageformat icons. So, display 3 different options:
- app banner with Snap and Deb available;
- app banner with just Snap available;
- app banner with just Deb available

As I mentioned [here](https://github.com/ubuntu-flutter-community/software/discussions/634#discussioncomment-4399231): 
>The issue here is that, when it's an app banner with both packages (both snap and deb icons) the info we display in the banner (publisher name, summary, and ratings) is from the Snap, not the Deb. We wanted to somehow make it clear for the user that the information is about the snap and not necessarily about the Deb. Imagine if the deb doesn't have such good ratings? That said, we tried to somehow make it clearer that it's about the Snap hence using colour.

I can already see this is confusing, so we should iterate on this. I will bring this up again on the next meeting with the team.

**Comment by Feichtmeier** [comment]
Thanks for the issue
I currently am a little bit less active than usual as you know
I'll do the following things next:

- merge the search banners to look like the mockups
- align all banners to look like the search banners

**Comment by madsrh** [comment]
I just tested master and this looks great @Feichtmeier but there's a few things missing. I'm sorry if this is WIP, but I'll reopen the issue as a reminder 👼

**Comment by Feichtmeier** [comment]
Honestly I think the colouring of the package format icons is too complicated

Make it simple:

- available as a snap: show snap icon
- available as a deb: show deb icon

The snap backend always has more Infos anyways.

**Comment by Feichtmeier** [comment]
We can't always display both icons because there is a package format popup at the top which provides the feature of filter and knowingly deselect one of the package formats.
