### ISSUE TITLE
On systems with no Snaps installed, the Installed Page will load indefinitely.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#657]
There should be a "No Snaps installed" message coming up if no Snaps are installed. We could maybe do the same for the deb page? :grin:

https://user-images.githubusercontent.com/73116038/208285925-3dcdd2b9-1a48-4460-bcd4-28fbc08082fe.mp4

**Comment by whiskeyPeak** [comment]
I'm planning of tackling this again (minus the snapd issue). @Jupi007 Could you roll the latest YaruIcons.dart changes in here? Thanks! :D

**Comment by Feichtmeier** [comment]
@whiskeyPeak please do not waste too much energy on this one, as I am not even sure this is actually wanted by ubuntu designers/managers. As far as I designed this application in the beginning, this should be a snap-store front end. The debian feature is needed because debian packages can be installed and are very common to be installed on the default ubuntu installation

**Comment by whiskeyPeak** [comment]
> Edit: and remember... You can't install this application here (snap-store) without snapd being installed. So I would go so far and say that this is a "non-issue".

Yeah, I agree that the snapd is a non-issue now. 
Does the software centre snap show up in the installed page? Because if it doesn't and a user decides to remove every single snap on their system, we get the infinite loading issue I described originally here.

**Comment by Feichtmeier** [comment]
> > Edit: and remember... You can't install this application here (snap-store) without snapd being installed. So I would go so far and say that this is a "non-issue".
> 
> Yeah, I agree that the snapd is a non-issue now. 
> Does the software centre snap show up in the installed page? Because if it doesn't and a user decides to remove every single snap on their system, we get the infinite loading issue I described originally here.
> 

Oh sorry I need to check. I never ran into this before as I always have snaps installed. Maybe we could even show some cute "nothing to see here" like stuff is there aren't any snaps yet installed

**Comment by whiskeyPeak** [comment]
> Oh sorry I need to check. I never ran into this before as I always have snaps installed. Maybe we could even show some cute "nothing to see here" like stuff is there aren't any snaps yet installed

Sounds good 👌
