### ISSUE TITLE
Inconsistent padding throughout the entire app.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#676]
In a lot of areas of the software store, the padding seems to alternate between being 20 and 25 pixels. IMO it should either be one or the other. I have a branch for this, just need to know if we wanna go with 20 or 25 pixels for the padding.

25px on the left, top and right:
![Screenshot from 2022-12-31 13-18-13](https://user-images.githubusercontent.com/73116038/210138129-d5656abc-a739-455c-84ff-f0849002ad14.png)

20px on the left, top and right:
![Screenshot from 2022-12-31 13-18-52](https://user-images.githubusercontent.com/73116038/210138159-e8f6dc05-a395-4306-8ab5-2a9ba997bbb8.png)

25px on the left, 20px between the snap packages button and the textfield:
![Screenshot from 2022-12-31 13-19-22](https://user-images.githubusercontent.com/73116038/210138178-93d710c8-3aa0-4d05-9dbe-428592cee0ea.png)

25px on the left, 20px at the top:
![Screenshot from 2022-12-31 13-19-48](https://user-images.githubusercontent.com/73116038/210138209-2306da7b-12ff-42a6-866a-e81a73e22232.png)

20px on the left and top:
![Screenshot from 2022-12-31 13-20-01](https://user-images.githubusercontent.com/73116038/210138227-c5435310-fc67-4a94-a1a1-e0d029ef5435.png)

20px on the left, top and right:
![Screenshot from 2022-12-31 13-20-13](https://user-images.githubusercontent.com/73116038/210138250-ff34ea3b-324e-4406-981b-a38e0451545b.png)

The left/right padding is also different from the top padding when resizing the window in the my apps page:

https://user-images.githubusercontent.com/73116038/210138377-2fe9bcbf-3725-48d9-bcc5-59d6939a10f3.mp4

It would look better if the layout changed right as the left/right padding were equal to the top padding

**Comment by Feichtmeier** [comment]
Indeed. Reason is that yaru banner draws a 5px border on hover. With this banner design which I personally like, I see no other way to keep this "inconsistent" padding (in numbers). Visually it should be consistent, if not we need to change this ofc

**Comment by whiskeyPeak** [comment]
> Indeed. Reason is that yaru banner draws a 5px border on hover. With this banner design which I personally like, I see no other way to keep this "inconsistent" padding (in numbers). Visually it should be consistent, if not we need to change this ofc

Ah, so the current padding for a yaru banner is 20px, which ends up looking like 25px because of the 5px invisible border (unless on hover). I take it that the default padding size (visually) should be 20px?

**Comment by Feichtmeier** [comment]
No because the banner is not used everywhere ☺️
But you are right if the padding is visually wrong we need to change it.

**Comment by whiskeyPeak** [comment]
> No because the banner is not used everywhere ☺️
> But you are right if the padding is visually wrong we need to change it. 

Just so I got this right, we would need to change the padding to 15px so that it looks visually like 20px (for the yaru banner)? So it would be a padding of 20px for all of the other afro mentioned issues above.
