### ISSUE TITLE
No way to sort tiles

### ISSUE THREAD

**Issue by hsbasu** [ubuntu-flutter-community/software#680]
Currently there is no means to sort the snap packages in a category. Adding an option to sort by **Name** or **Rating** would be useful.

**Comment by Feichtmeier** [comment]
???
there is a popup to sort by name and more
???

**Comment by madsrh** [comment]
Do you mean on the Explore page @hsbasu ?

**Comment by hsbasu** [comment]
> Do you mean on the Explore page @hsbasu ?

Yes. But I think this feature is WIP.

**Comment by madsrh** [comment]
> Yes. But I think this feature is WIP.

Indeed. There's no rating to sort by - yet 😅 

Would you really sort by name here? 🤔 I believe these three options would be sufficient:

- Relevance
- Downloaded
- Rating

**Comment by madsrh** [comment]
@Feichtmeier do you want to close this issue until the backend is ready or leave it open? IMO this will be addressed in one of the UI mockups later.

**Comment by anasereijo** [comment]
The explore page will be my next focus, I will take this into consideration. 👍

**Comment by madsrh** [comment]
> The explore page will be my next focus, I will take this into consideration. 👍

Then let's close this for now. I hope this is okay @hsbasu
