### ISSUE TITLE
Pixel Overflow in PanedPageLayout when height is set to the smallest possible size (30px overflow)

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#688]
![Screenshot from 2023-01-04 19-57-06](https://user-images.githubusercontent.com/73116038/210638964-2ea0b5b1-b658-4a0c-87b7-0c09d09537c4.png)

Possible solutions:
- Make the smallest window height larger
- Make the PageAppHeader scrollable.
- Reduce the size of the PageAppHeader Icon and Title

**Comment by whiskeyPeak** [comment]
Personally, making the PageAppHeader scrollable makes the most sense. The smallest size the window can be is already quite big and reducing the size of the title and icon might not amount to much if the tittle happens to be long and span multiple lines.

**Comment by Feichtmeier** [comment]
no please dont make it scrollable

this is happening since I added this "Snap" under the title. I'll fix it a bit different plus this "(SNAP)" "(DEBIAN)" is not really a good solution and too spamy

**Comment by anasereijo** [comment]
I think the icon and title are way too big anyway, making it look disproportionate compared to the rest of the content. Reducing both will make the layout look better and also fix the issue with the pixel overflow.

(@Feichtmeier I only noticed just now that we have the snap icon next to the app icon - why don’t we display the switch button as agreed before? I can comment about this on a more appropriate issue, if there’s one.)

**Comment by Feichtmeier** [comment]
problem with the button is that it might not fit in the not wide layouts (normal and small window) but I test it in the next days :crossed_fingers:

**Comment by anasereijo** [comment]
> problem with the button is that it might not fit in the not wide layouts (normal and small window) but I test it in the next days 🤞

I see. Let’s see how it looks and then I will help finding a solution for those layouts if needed. Thanks!

**Comment by Feichtmeier** [comment]
Fixed with #704
