### ISSUE TITLE
Description on "cards" shouldn't be gray

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#702]
Currently the text color for descriptions on the app cards/banners (what's the correct name here 🤷‍♂️) is gray. This should be black.
Although the mockup doesn't match 100%, this issue is only about the text color 😃 

Current master:
<img width="538" alt="Skærmbillede 2023-01-07 kl  10 03 28" src="https://user-images.githubusercontent.com/3986894/211142722-d889a1fa-f45c-41b6-b1d1-699f5841e097.png">

Mockup:
<img width="538" alt="Skærmbillede 2023-01-07 kl  10 03 28" src="https://user-images.githubusercontent.com/3986894/211142832-37a72e60-af53-4f53-96fc-3976c8e0308b.png">

Can I assigned this to you @whiskeyPeak ?

**Comment by whiskeyPeak** [comment]
Sure thing :D
