### ISSUE TITLE
Add tooltip for featured banners

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#703]
![image](https://user-images.githubusercontent.com/3986894/211147513-af9b1926-d865-439f-8350-3f6260ce86dd.png)

The title says it all. Add a tooltip with the app name on hover for featured banners. 

Is this also something I can assign you to @whiskeyPeak 👼 or do you have enough on your plate?

I had a look in the [update_dialog.dart](https://github.com/ubuntu-flutter-community/software/blob/ec6e298926746efd4836f48d9bde01a46d3b554a/lib/app/updates/update_dialog.dart#L161) and [app.dart](https://github.com/ubuntu-flutter-community/software/blob/ec6e298926746efd4836f48d9bde01a46d3b554a/lib/app/app.dart#L213) where there's also a tooltip mentioned, but I could make it work with the app name.

Once the UI is (more) stable we should ofc have a look at the other places that doesn't currently have a tooltip, but this one is particularly notable.

**Comment by whiskeyPeak** [comment]
Yup, I can take this one on as well. Thanks!
