### ISSUE TITLE
Deb Apps: show dependency

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#718]
Debian packages can have a horrendous bunch of dependency being installed if you install a certain package.
For example a KDE app with pull in many kde/qt dependencies if not even the whole desktop

![grafik](https://user-images.githubusercontent.com/15329494/211219428-f0999c04-f158-4204-a47f-81767446b5dc.png)

No idea where to show this, but the info would look kind of like 

"those packages will also be installed if you install app 1234:
- package abc
- package def
- package ghj"

(also maybe we could go so far and check for KDE and gnome components and just give a note that this app might not fit very good into the desktop)

Needs design, CC @madsrh @anasereijo

**Comment by anasereijo** [comment]
Could it be some kind of new section at the top (before the info) that it looks like a notification? I couldn't find anything like that on [Yaru](https://ubuntu.github.io/yaru_widgets.dart/#/)  (maybe I am now looking at the correct place), but we do have something like that on [Vanilla](https://vanillaframework.io/docs/patterns/notification). I can wireframe something if it helps

**Comment by Feichtmeier** [comment]
There are material snackbars like for example here

![](https://user-images.githubusercontent.com/15329494/204924774-1a2d45df-c5c6-414c-9e92-2c92ca9a8d3c.png)

But we could put anything inside the border container widget we use here or we can just make a new widget

**Comment by madsrh** [comment]
> ...looks like a notification...

That's a solution, but there are dependencies for every application, right @Feichtmeier ? If that's true, I think the notification/snackbars is a bit too attention grabbing.

From my VM, this is (almost) all of the dependencies for the plasma-desktop. So as you can see, it can be long list, sometimes. 

![image](https://user-images.githubusercontent.com/3986894/211343058-5558306c-a228-43ec-ba3b-d33517717a7f.png)

**Comment by Jupi007** [comment]
What about just add a new section, like the snap connections, but for dependencies?

**Comment by Feichtmeier** [comment]
holy crap, yeah xD notification might not fit, even if one can make the content scrollable

**Comment by anasereijo** [comment]
> > ...looks like a notification...
> 
> That's a solution, but there are dependencies for every application, right @Feichtmeier ? If that's true, I think the notification/snackbars is a bit too attention grabbing.
> 
> From my VM, this is (almost) all of the dependencies for the plasma-desktop. So as you can see, it can be long list, sometimes.
> 
> ![image](https://user-images.githubusercontent.com/3986894/211343058-5558306c-a228-43ec-ba3b-d33517717a7f.png)



> > ...looks like a notification...
> 
> That's a solution, but there are dependencies for every application, right @Feichtmeier ? If that's true, I think the notification/snackbars is a bit too attention grabbing.
> 
> From my VM, this is (almost) all of the dependencies for the plasma-desktop. So as you can see, it can be long list, sometimes.
> 
> ![image](https://user-images.githubusercontent.com/3986894/211343058-5558306c-a228-43ec-ba3b-d33517717a7f.png)

Oh wow, that is a long list indeed.


> That's a solution, but there are dependencies for every application, right @Feichtmeier ? If that's true, I think the notification/snackbars is a bit too attention grabbing.

ah I see. sorry, I thought this would only display on some apps, not for all of them

**Comment by anasereijo** [comment]
What if is a notification section, but with a link to 'see list of dependecies" ?

**Comment by anasereijo** [comment]
> What about just add a new section (which would be small by default, but could be extendable), like the snap connections, but for dependencies?

that could work, I think!

**Comment by Jupi007** [comment]
> Edit: I usually don't like to hide content, but as this can be a very long list and I wonder how many users will _care_ to actually check it all, maybe this can work?

We could name the section like `Dependencies (30)`, so the user is aware of the fact there is a lot of deps. So the section can be folded by default.

**Comment by Feichtmeier** [comment]
How about we just show a dialogue when you press install if the package you want to install has deps? I will show you when i removed 12434234 kdevelop deps I accidentally  installed when testing this :crying_cat_face:

**Comment by Jupi007** [comment]
I also had the dialog idea, and I found it a bit too intrusive.
But with your little experience of install a kde app 😅 maybe it is not that a bad idea to warn the user that it will install many deps with a popup.

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/211361025-aca20dee-efaa-42e9-90bc-e49806708279.png)

**Comment by madsrh** [comment]
@Feichtmeier Check out how this is done in Synaptic. It uses the expanders (like we have on the update page). I'll try to do a mockup later tonight, but you probably have already solved this by then 😅

**Comment by Feichtmeier** [comment]
I am fiddling with what could work but first you guys need to tell me if you want a dialogue or not, independent what's above " Cancel | Install "

**Comment by anasereijo** [comment]
just to confirm: will this show up in all applications?

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/211367636-be3e4c67-c289-4c5f-a315-59fa13025871.png)

?

**Comment by anasereijo** [comment]
just did something super quick (never mind the colours and text needs improvement)

<img width="704" alt="Screenshot 2023-01-09 at 17 20 06" src="https://user-images.githubusercontent.com/36884067/211368561-0056a694-1b35-446a-80be-7828874f18cb.png">

**Comment by Feichtmeier** [comment]
ok good idea will do!

(we could also have general discussion about how our dialogues should look in https://github.com/ubuntu/yaru_widgets.dart/)

**Comment by anasereijo** [comment]
@madsrh I'm curious about your idea 🙂
also, feel free to propose a (nicer) design for my suggestion, as it's basically a very rough wireframe and needs some love 😀

**Comment by Feichtmeier** [comment]
We could additionally should a dependency section IMO. The dialogue does not reduce the need to show this when you view the app page

**Comment by Feichtmeier** [comment]
Under the description?

![grafik](https://user-images.githubusercontent.com/15329494/211398434-80c588ed-f834-4962-aafe-155134bb1203.png)
![grafik](https://user-images.githubusercontent.com/15329494/211398453-427425bf-dace-4d7c-9e84-3c0e62d89ca9.png)

**Comment by Jupi007** [comment]
Looks good 🙂
Can you add the number of dependencies in the title?

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/211400778-ade56b54-c093-4e5c-8f10-0184f9934ca5.png)
yes

**Comment by Jupi007** [comment]
Perfect 👌

**Comment by madsrh** [comment]
I just tried the master and 👍 

Can I just ask two questions: 
1. is browsing through such a dependencies list something you actually do when installing something @Feichtmeier @Jupi007 ? I think I fall in the category of an everyday mom/dad user here. I would not know what too look for on that list. Would you agree that this is for the more technical users?

2. Besides the new packages that gets installed, there's also some upgrades (replacements or potential breaks) and some suggested packages. Would you care about these or should I ask, would you want these marked/tagged?

I love the work @Feichtmeier did with [the update page](https://github.com/ubuntu-flutter-community/software/issues/480#issuecomment-1301819085). Could we do something to give this list a bit more context? Besides the filename, there's also a tagline and a description available for each package.

![image](https://user-images.githubusercontent.com/3986894/211429961-d8e57590-ed24-4e57-8b0b-091f4c6fdc4f.png)

**Comment by Jupi007** [comment]
@madsrh to answer your questions:

1. It depends on what I install, but I sometimes take care of the dependencies when I install a programs. So yes, it is something really related to "power users" who want to know exactly what they're going to do by installing a program.
2. Same about dependencies, sometimes the related packages who are recommended can be very useful to know, while sometimes they are completely useless for you. But I think it is a good idea to show them, just for the case that the user takes care of them. That could be shown in a sub-section of the dependencies block, which would be renamed in something like "dependencies and recommends (9)".

Also, I like the idea of showing a summary of the related dependencies and recommends packages 👍

**Comment by Feichtmeier** [comment]
I actually changed the pr description from closes to ref but I forgot the commit that still had closes xD

To your questions mads I honestly think this is a perfect example why inexperienced users should seriously not use debs but just snaps because the design of snaps avoids this dependency hell

But when we ship a store with Debian support we should not hide this information

**Comment by anasereijo** [comment]
> I just tried the master and 👍
> 
> Can I just ask two questions:
> 
> 1. is browsing through such a dependencies list something you actually do when installing something @Feichtmeier @Jupi007 ? I think I fall in the category of an everyday mom/dad user here. I would not know what too look for on that list. Would you agree that this is for the more technical users?
> 2. Besides the new packages that gets installed, there's also some upgrades (replacements or potential breaks) and some suggested packages. Would you care about these or should I ask, would you want these marked/tagged?
> 
> I love the work @Feichtmeier did with [the update page](https://github.com/ubuntu-flutter-community/software/issues/480#issuecomment-1301819085). Could we do something to give this list a bit more context? Besides the filename, there's also a tagline and a description available for each package.
> 
> <img alt="" width="556px" src="https://user-images.githubusercontent.com/3986894/211429961-d8e57590-ed24-4e57-8b0b-091f4c6fdc4f.png">

I really like your proposal, @madsrh!

**Comment by madsrh** [comment]
> I really like your proposal, madsrh!

🎉 

Let's see what @Feichtmeier thinks 😸

**Comment by Feichtmeier** [comment]
sure will do, maybe not today, not much time 👍

**Comment by Feichtmeier** [comment]
Closes with #724 

New issues #738
