### ISSUE TITLE
SnapUpdates page throws exceptions when resizing

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#719]
Other visual inconsistencies include:
- Snap update page doesn't show the "everything is up to date" page
- When checking for updates, the "check for updates" button disappears for the Snap page but not for the Debian page.
- snap page always re-checks for updates when switching to it whilst debian page doesn't.

https://user-images.githubusercontent.com/73116038/211224417-d8dd3b23-8957-46d2-bde4-56dbb72c746a.mp4

I'm currently working on this so you can assign this issue to me :) @Feichtmeier

**Comment by Feichtmeier** [comment]
You can work on the exception please. The button thing needs a restructuring of the widgets I would prefer to do
