### ISSUE TITLE
Publisher star icons are too big

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#728]
Latest master. TBH this could be something I messed up. Can someone confirm? 
The green  checkmark aren't affected 

<img width="899" alt="Skærmbillede 2023-01-09 kl  23 32 45" src="https://user-images.githubusercontent.com/3986894/211421654-c8fb540e-fe39-45ea-9f09-566b2fe7eaba.png">

**Comment by Feichtmeier** [comment]
Yep, I messed this up 😅 will fix
