### ISSUE TITLE
SectionBanner: wrap inkwel lin material

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#746]
> @d-loose test succeeds locally, no idea whats the issue here, I create a new issue for the test and merge this one

Doesn't work for me locally - throws an exception when simply running the App. The issue seems to be that there is an `InkWell` in `SectionBanner` that doesn't have a `Material` ancestor. This is caused by switching from `YaruNavigationPage` to `YaruMasterDetailPage`, although I don't quite see what exactly causes the problem there.

_Originally posted by @d-loose in https://github.com/ubuntu-flutter-community/software/issues/745#issuecomment-1380025675_

**Comment by d-loose** [comment]
Just left a comment seconds ago - I'll fix it in yaru_widgets

**Comment by Feichtmeier** [comment]
Ok, I think this does not hurt though and I often if you mindlessly use inkwell more issues can happen (overlays in scroll views for example) :)
