### ISSUE TITLE
Reviews and ratings - Version 2

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#751]
# Reviews and ratings

Please keep in mind that these are wireframes, focused mainly on functionality. It will be using yaru theme and some things will need visual design input.

## app not installed
([high-res version](https://zpl.io/5EM0LJr))

![23 04 v2 - Reviews and ratings - app not installed](https://user-images.githubusercontent.com/36884067/211051039-d294b216-707e-444d-a9c0-de011569c58a.jpg)

## app installed
([high-res version](https://zpl.io/8lBzL9d))

![23 04 v2 - Reviews and ratings - app installed](https://user-images.githubusercontent.com/36884067/211051206-ec9f89b3-f774-4b69-abdb-e4f2eee8270d.jpg)

## app installed - star rating
([high-res version](https://zpl.io/qyGPNYZ))

![23 04 v2 - Reviews and ratings - app installed (star rating)](https://user-images.githubusercontent.com/36884067/211051335-b8e16875-8ac2-4212-9e3b-98eaaec2e801.jpg)

## useful / not useful feedback
([high-res version](https://zpl.io/MdD8ep7))

![not useful feedback](https://user-images.githubusercontent.com/36884067/211051669-9a01dafb-16e8-4d26-b039-7ac150b3d922.jpg)

## report abuse
([high-res version](https://zpl.io/B1e9LKe))

![23 04 v2 - Reviews and ratings - report abuse](https://user-images.githubusercontent.com/36884067/211051793-0acf2eee-86d5-49b3-b16c-4ba2c03c3af2.jpg)

## app installed - write a review
([high-res version](https://zpl.io/YYmZeoJ))

![23 04 v2 - Reviews and ratings - app installed (write a review)](https://user-images.githubusercontent.com/36884067/211051934-779d53a2-32bf-4d4c-a387-a88c9aa7e343.jpg)

## app installed - write a review - submitted
([high-res version](https://zpl.io/ewr5QkY))

![23 04 v2 - Reviews and ratings - app installed (review submitted)](https://user-images.githubusercontent.com/36884067/211052116-d040a788-9c31-405b-9c7b-409b33b6df19.jpg)

## see all reviews
([high-res version](https://zpl.io/3X7yLRl))

![23 04 v2 - Reviews and ratings - see all reviews](https://user-images.githubusercontent.com/36884067/211052720-78518904-4334-4d71-a429-550bce74f230.jpg)

_Originally posted by @anasereijo in https://github.com/ubuntu-flutter-community/software/discussions/523#discussioncomment-4613780_

**Comment by Feichtmeier** [comment]
@anasereijo how should the not-expanded look like? Should the header only show "Reviews and ratings" or also the bar chart?

**Comment by anasereijo** [comment]
> @anasereijo how should the not-expanded look like? Should the header only show "Reviews and ratings" or also the bar chart?

@Feichtmeier I think it makes sense to only show the header when collapsed 👍
