### ISSUE TITLE
Searchbar look

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#752]
I would propose the searchbar to have a background and make it less long and move it into the middle of the title

Edit: screenshot is outdated, please look into #753 

@mads and/or @anasereijo do you agree with this?

**Comment by madsrh** [comment]
Adding the background makes it much more distinct 👌 

I've taken the liberty of "forwarding" this suggestion by @jpnurmi 

> does the app title and separator add any value in the top-left corner? what if the search box hint text was "Search Ubuntu Software" so you don't need a separate title? 🙂

![image](https://user-images.githubusercontent.com/3986894/212159932-3ee9b550-3abf-42e0-976a-979fcc19e95d.png)

**Comment by Feichtmeier** [comment]
I am quoting myself

> the longer description seems nice, but the "paned" look feels more natural and easier on the eyes, in my opinion
