### ISSUE TITLE
Navigation rebuild should not rebuild the app page to be dismissed

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#761]
With yaru master details view the whole app is rebuild but the detail on the right should not when the layout switches from landscape to portrait. I think I remember this might be fixable with a Key

**Comment by Feichtmeier** [comment]
@d-loose any help here would be appreciated

**Comment by d-loose** [comment]
I'm looking into this - I think this is an unintended side effect of #723. When the layout switches from landscape to portrait the navigator state is lost, because the page doesn't have it's own navigator any more :(

**Comment by Feichtmeier** [comment]
Thank you

**Comment by d-loose** [comment]
I doesn't look like a side effect of #723 after all. Seems like it's just a shortcoming of `YaruMasterDetailPage`.
