### ISSUE TITLE
AppInfos: improve reaction to available space

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#763]
The app info section currently behaves badly when the space changes they are drawn in which can result in strange situations

![grafik](https://user-images.githubusercontent.com/15329494/212266421-cb85bcd2-4738-4022-8094-5114b96a0de6.png)
![grafik](https://user-images.githubusercontent.com/15329494/212266514-de0fc62b-62f5-4d89-99e8-08d4040643d0.png)

I propose to use a gridview instead which also makes it possible to "skip" elements:

https://user-images.githubusercontent.com/15329494/212267148-f530b774-761e-43e7-912a-4b848bc90efc.mp4

**Comment by madsrh** [comment]
👍 I think this is a good idea. 

Maybe this sections content will be trimmed  when we finalize the additional information section https://github.com/ubuntu-flutter-community/software/discussions/729 but having things in a grid is good in any case 👍

**Comment by anasereijo** [comment]
yes yes yes to the grid view 👍
