### ISSUE TITLE
White separator in dark theme

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#766]
Since the [big layout change](https://github.com/ubuntu-flutter-community/software/commit/f24f84a052c64b3f4ebccb034c4c898ba6094c0d), I've had this line when using the dark theme. I've tried 3 different virtual machines and every version has this issue. 

<img width="840" alt="Skærmbillede 2023-01-12 kl  23 22 47" src="https://user-images.githubusercontent.com/3986894/212305004-506571c2-a3ac-4fd5-9d66-2b87a574cad1.png">

**Comment by jpnurmi** [comment]
How did you install Flutter? What does `flutter doctor -v` output?

**Comment by madsrh** [comment]
> How did you install Flutter? What does flutter doctor -v output?

This is even on a clean system, no flutter, just switching the app store to the preview channel 🤷‍♂️ Am I really the only one seeing this? 🤔

**Comment by Feichtmeier** [comment]
https://user-images.githubusercontent.com/15329494/212412140-274da1cf-6d88-42d1-922f-86af1a7e86e2.mp4

This sounds not good but I am not experiencing this. Ubuntu 22.04, snap store from preview/candidate

**Comment by madsrh** [comment]
Okay. Let's not spend time investing this if it's just me 😃

**Comment by Feichtmeier** [comment]
Hm does not sound like it is only you if this is the snap :)

**Comment by Feichtmeier** [comment]
Maybe it is preview/edge ? Try to switch to preview/candidate, which is build from main branch

**Comment by madsrh** [comment]
> Maybe it is preview/edge ? Try to switch to preview/candidate, which is build from main branch

No both :/

![image](https://user-images.githubusercontent.com/3986894/212414411-8fb370b5-a478-4bac-ad17-20810b161c44.png)

**Comment by Feichtmeier** [comment]
Oo strange!- I am setting up a VM tomorrow, since I can not reproduce this on both of our linux laptops at home (22.04)

**Comment by Feichtmeier** [comment]
aaaaaaaaaaaaaaah I have an idea :brain: 

This could actually be a bug in this not-updated VM :) I think  there was a bug in the beginning of 22.10 which did not swtch the gtk theme correctly when you switch ligh-> dark and vice versa :) Could you try to update those Vms?

**Comment by jpnurmi** [comment]
Oh, snap! I thought you were using the Flutter SDK to run the app :)

![image](https://user-images.githubusercontent.com/140617/212420041-c0047617-92ed-4bc7-a16d-2003fd093739.png)

**Comment by whiskeyPeak** [comment]
hmm, I'm also experiencing this on Linux mint debian edition:

https://user-images.githubusercontent.com/73116038/212425638-156bda1e-74f4-4571-a3ef-0f832af1ca7f.mp4

Loving the new UI btw :D

**Comment by madsrh** [comment]
> Oh, snap! I thought you were using the Flutter SDK to run the app :)

Yes @jpnurmi, but same issue. Doctor says:

```
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.10 5.19.0-23-generic, locale
    en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/mads/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.2-1
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] VS Code (version 1.73.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Ubuntu 22.10 5.19.0-23-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

> hmm, I'm also experiencing this on Linux mint debian edition:

Looks like you have the opposite issue @whiskeyPeak

**Comment by jpnurmi** [comment]
@Feichtmeier didn't we have this issue on web before?

**Comment by whiskeyPeak** [comment]
Issue isn't reproducible when running the latest example from yaru_widgets.dart

**Comment by whiskeyPeak** [comment]
![Screenshot from 2023-01-14 03-26-50](https://user-images.githubusercontent.com/73116038/212448699-8d7db074-79b8-4003-8e13-999c85671f6b.png)

The colours should be the same, according to what the terminal is spewing out. This is really weird...

**Comment by whiskeyPeak** [comment]
Oh wait, I figured it out. The pages in the routes are not using a Scaffold, so there was no general background colour set for that route. Wrapping YaruMasterDetailPage() (in app.dart) with a scaffold widget fixes this issue for me :D

@madsrh Does this fix your issue?

**Comment by Feichtmeier** [comment]
I am also interested to see if this happens only with a not-updated 22.10, since I know there was a bug about dark/light switching in GTK in Ubuntu for a period of time after 22.10 and I dont know if they fixed it yet, because I am on 22.04 all the time

**Comment by Feichtmeier** [comment]
@madsrh could you open the issue on yaru widgets?

**Comment by madsrh** [comment]
> Oh wait, I figured it out. The pages in the routes are not using a Scaffold, so there was no general background colour set for that route. Wrapping YaruMasterDetailPage() (in app.dart) with a scaffold widget fixes this issue for me :D madsrh Does this fix your issue?

Wayyyyyy to technical for me 😆 

> could you open the issue on yaru widgets?

Sure, but you'll have to fill out all the technical mumbo jumbo
