### ISSUE TITLE
Wording: exchange all occurences of "refresh" with "update"?

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#771]
Some of the wording of the snap API still leaks via code via my brain in the beginning with the first translations into the UI. Snap API names permissions connections as we know (we'll fix this too) and another thing I found not intuitive is "refresh" and friends.

:monocle_face: :magic_wand: I propose (sounds like a casting spell from harry potter) to exchange all occurrences of "refresh" with "update". 

Refresh occurs on an snap inside anAppPage if it has an update and in the AppPage with a package that has an update [if the store is started by clicking on a deb from your file manager.](https://twitter.com/fluttermeier/status/1614162088569479175)

WDYT about this @madsrh @anasereijo ?

**Comment by madsrh** [comment]
Absolutely, I had the same thought 👍
