### ISSUE TITLE
AppIcons: always use a BasePlate?

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#788]
Even if the "store hygiene" could eventually make some store publishers change their mind and create high quality icons, we will never catch them all.

So how about presenting all app icons on a baseplate?

Here is a very horrible example
![grafik](https://user-images.githubusercontent.com/15329494/212562501-068c683a-17b9-4682-a632-ee0112eb68db.png)

With a baseplate
![grafik](https://user-images.githubusercontent.com/15329494/212562945-692e5302-04e4-4e32-8623-4f51ac7e21f1.png)

![grafik](https://user-images.githubusercontent.com/15329494/212562925-63dbb91f-400f-443d-b9e4-2d112b2cda89.png)
![grafik](https://user-images.githubusercontent.com/15329494/212563292-f56ec52b-f001-41cf-bdb0-0f71543856b0.png)
![grafik](https://user-images.githubusercontent.com/15329494/212563458-0f678976-1fca-4b72-b8b7-85ba6e971c5c.png)

**Comment by Jupi007** [comment]
Looks like a great improvement.

Some like spotify shouldn't have a baseplate. So the best would be to do like android, and allow the app publisher to add metadata about the app icon.

**Comment by madsrh** [comment]
I was expecting the return of the squircle 😅

I like this idea 👍

**Comment by Jupi007** [comment]
> I was expecting the return of the squircle sweat_smile

We had the same thought 😆

**Comment by Feichtmeier** [comment]
Wow, I think this was the first time I proposed something and it went right through you all 

![](https://media.giphy.com/media/zmRa0J4k30faE/giphy.gif)

Eventually this needs improvements let's see
