### ISSUE TITLE
Split Infos into Infos and Additional Information + Improve design

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#796]
Here goes a proposal – let's focus on the information displayed and not on how it looks, as this is just a wireframe.

At the top, we have the Reviews, Confinement, Version, and Download size.

At the bottom, we have the Additional information section (we can call it something else) where we have:  Publisher, Publication date, License, Category, Age rating, Installation date, Languages, Links, and Terms and conditions.

I checked with @kenvandine, and we currently don't support languages and age rating, but this is something we would like to have in the future, so I am keeping it on the wireframes.

I couldn't check if we can get all the items from Debs, so couldn't fill out the table above.

Furthermore, I would like to know everyone's opinion on what should be at the top and bottom.

![23 04 v2 - App page - additional information](https://user-images.githubusercontent.com/36884067/212695973-2862a36b-916f-4432-8879-8945a17dd9fa.jpg)

_Originally posted by @anasereijo in https://github.com/ubuntu-flutter-community/software/discussions/729#discussioncomment-4697637_

**Comment by Feichtmeier** [comment]
@anasereijo little update on the progress

![grafik](https://user-images.githubusercontent.com/15329494/213680096-5e5be9e4-260d-4d56-b651-8f7084b46c7c.png)

- as far as I know snaps do not have an age rating, at least it's not in snapd.dart
- the category is currently not given by the snap api, I talked to @robert-ancell to this and he forwarded me to this issue to explain the importance of this property for our design https://bugs.launchpad.net/snapd/+bug/1838786
- temps and conditions & privacy policy / license agreement : what's this? :) Where should we get this information from? License could come from the license ofc but the rest :shrug:  ?
- languages are also not forwarded by the API as far as I know
- Links: I need to find a way to align this tripple column inside this grid of double columns

Apart from those things this design works pretty great IMO!

**Comment by Feichtmeier** [comment]
@anasereijo @madsrh 

I fixed the links. I left a TODO in the code to wait for the API to change and include the categories if a snap was found by name and disabled this info fragment for now.

Could we go with this improvement until we have the other fragments ready? I feel this is already a big improvement? WDYT?
![grafik](https://user-images.githubusercontent.com/15329494/213771098-7eced93f-a0cc-4a7b-97df-6dc4e612a02e.png)
![grafik](https://user-images.githubusercontent.com/15329494/213771199-770cada9-beb3-4c95-be01-e32ee6ce2487.png)
![grafik](https://user-images.githubusercontent.com/15329494/213772119-8ab094bf-3822-46fe-86be-f08f1cbfd9dc.png)

**Comment by madsrh** [comment]
> Could we go with this improvement until we have the other fragments ready? I feel this is already a big improvement? WDYT?

This looks amazing @Feichtmeier 🕺 Please merge.

**Comment by Feichtmeier** [comment]
You need to approve. This pr doesn't close this issue. It's just a ref

**Comment by Feichtmeier** [comment]
You need to approve. This pr doesn't close this issue. It's just a ref

**Comment by Feichtmeier** [comment]
I'm too slow. Whole day working from hot spot in trains xD

**Comment by anasereijo** [comment]
whoop whoop this is looking great!

> as far as I know snaps do not have an age rating, at least it's not in snapd.dart

You are right! We do not have that info but, as I mentioned before, it is something we want to have in the future, hence I included it on the wireframes. Hopefully we will manage to get that in the near future :)

> the category is currently not given by the snap api, I talked to @robert-ancell to this and he forwarded me to this issue to explain the importance of this property for our design https://bugs.launchpad.net/snapd/+bug/1838786

Thanks for doing that! @Lukewh is this something you can help us with?

> temps and conditions & privacy policy / license agreement : what's this? :) Where should we get this information from? License could come from the license ofc but the rest 🤷 ?

@local-optimum any idea where we can get the license agreement from? or @Lukewh?

> languages are also not forwarded by the API as far as I know

Same as age rating – we don't have it now, but plan to have it in the future.

>Links: I need to find a way to align this tripple column inside this grid of double columns

Yes please! :D

**Comment by anasereijo** [comment]
Not sure if @Lukewh or @local-optimum will get notifications? Do we need to add them to the project, or is that just for the discussions?

**Comment by Feichtmeier** [comment]
> 

it depends how they configured their github notifications. Since I have a burning github obsession I disabled github email notifications but since I am after feierabend on github all the time I always see the blue dot.
:)

> You are right! We do not have that info but, as I mentioned before, it is something we want to have in the future, hence I included it on the wireframes. Hopefully we will manage to get that in the near future :)

I am still sad we don't see some naughty 18+ snaps 😢 😆

**Comment by Lukewh** [comment]
Looks like @robert-ancell has opened a PR for the categories issue, https://github.com/snapcore/snapd/pull/12513.

As for privacy policy / licence agreement. Individual snaps have a licence field, but no licence agreement, and there is no concept or field for a privacy policy per snap.

We do have Canonical-wide pages, though:
Data privacy page: https://ubuntu.com/legal/data-privacy
Snap store Terms of Service: https://ubuntu.com/legal/terms-and-policies/snap-store-terms
But as always with things like this, your best bet is to check with the Canonical legal team.

**Comment by Feichtmeier** [comment]
@Lukewh cool, thanks for the info

Is information about the amount of downloads of a snap available on the store?
![grafik](https://user-images.githubusercontent.com/15329494/214330954-da0f2390-d377-47c7-9e01-ceaf970938e3.png)

**Comment by Lukewh** [comment]
> @Lukewh cool, thanks for the info
> 
> Is information about the amount of downloads of a snap available on the store?
> ![grafik](https://user-images.githubusercontent.com/15329494/214330954-da0f2390-d377-47c7-9e01-ceaf970938e3.png)
> 

The only indication that could be used for a snaps popularity would come from the metrics endpoint in the form of logarithmic data for active devices for each OS. These could be combined to show a rough ranking, but there's noal accurate numbers publicly available. This is definitely something we should investigate with the store team for future cycles.

The number of downloads is a difficult one, all metrics are based on the number of "active" installs normalized over a set period (7 days I believe), we've never exposed (or even tracked, I don't think) downloads. And currently this data is only available to snap publishers.

**Comment by Feichtmeier** [comment]
> Looks like @robert-ancell has opened a PR for the categories issue, https://github.com/snapcore/snapd/pull/12513.
> 
> As for privacy policy / licence agreement. Individual snaps have a licence field, but no licence agreement, and there is no concept or field for a privacy policy per snap.
> 
> We do have Canonical-wide pages, though:
> Data privacy page: https://ubuntu.com/legal/data-privacy
> Snap store Terms of Service: https://ubuntu.com/legal/terms-and-policies/snap-store-terms
> But as always with things like this, your best bet is to check with the Canonical legal team. 

This looks also very snap specific to me. What should we show for Debian packages then?

**Comment by Feichtmeier** [comment]
> Looks like @robert-ancell has opened a PR for the categories issue, [snapcore/snapd#12513](https://github.com/snapcore/snapd/pull/12513).
> 
> As for privacy policy / licence agreement. Individual snaps have a licence field, but no licence agreement, and there is no concept or field for a privacy policy per snap.
> 
> We do have Canonical-wide pages, though: Data privacy page: https://ubuntu.com/legal/data-privacy Snap store Terms of Service: https://ubuntu.com/legal/terms-and-policies/snap-store-terms But as always with things like this, your best bet is to check with the Canonical legal team.

I don't have any contact to the Canonical legal team ;) But I guess you have since you work there? 😸 

On-Topic: I think we are missing only now
- category (external issue)
- legal links  for snap.... and deb? 

I will create new issues for those two things as the initial issue to split those infos and redesign it is done

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu-flutter-community/software/issues/941
