### ISSUE TITLE
Add clear icon to searchbar

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#801]
From @anasereijo https://github.com/ubuntu-flutter-community/software/pull/753#issuecomment-1384287838

> I still need to look into this with more detail, so bear with me! But one thing that caught my attention and might be a _quick thing to do_ (designers love saying this, right? hehe) is that the clear search icon (x) is missing. I think it would be nice to have it again as a quick way to clear the search and also to go back.

![image](https://user-images.githubusercontent.com/3986894/212728829-25d54314-b24b-49e8-97cb-986f6f804baf.png)

EDIT: clear icon only visible after the user starts typing

**Comment by whiskeyPeak** [comment]
Hmm a few other things about the text-field. It doesn't seem to be exactly centered in the app bar. The caret and "search" label also aren't exactly vertically centered either.

Text-field alignment is reeeeally weird with flutter. The verticalAlignement property is completely broken unfortunately.

**Comment by Feichtmeier** [comment]
Yep text field alignment is horrible. I focused on centering the caret. But I can try to align the text size to the titles
