### ISSUE TITLE
Improve app icon baseplate border

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#802]

**Comment by Feichtmeier** [comment]
@anasereijo @madsrh @Jupi007 

How about a suuuuuuper soft shadow? 

![grafik](https://user-images.githubusercontent.com/15329494/212846554-1af45549-d00e-4471-a380-f556d48247b7.png)

**Comment by Jupi007** [comment]
@Feichtmeier honestly a soft shadow doesn't look bad at all.

**Comment by anasereijo** [comment]
Hey all, just had a catch-up with the Design team and asked this, I will try to post the feedback here later today, I just want to confirm something first. Bear with me :)

**Comment by anasereijo** [comment]
As I mentioned previously, today I brought this issue to my team of designers, and we discussed what the best approach would be.
I think a better approach would be to educate the publisher on how to improve their logos and what the best practice is, similar to how other app stores do it. In that way, the better designed logos won’t be affected. We can provide a preview of how it will look on light and dark themes. We can easily have it done on the snapcraft.io listing page (see screenshot below).

<img width="1161" alt="Screenshot 2023-01-17 at 14 08 00" src="https://user-images.githubusercontent.com/36884067/212927163-8aa8b216-c5c5-439e-809f-12dd46073ea2.png">


What do you think?

**Comment by Feichtmeier** [comment]
> As I mentioned previously, today I brought this issue to my team of designers, and we discussed what the best approach would be. I think a better approach would be to educate the publisher on how to improve their logos and what the best practice is, similar to how other app stores do it. In that way, the better designed logos won’t be affected. We can provide a preview of how it will look on light and dark themes. We can easily have it done on the snapcraft.io listing page (see screenshot below).
> 
> <img alt="Screenshot 2023-01-17 at 14 08 00" width="1161" src="https://user-images.githubusercontent.com/36884067/212927163-8aa8b216-c5c5-439e-809f-12dd46073ea2.png">
> 
> What do you all think?

I totally agree. Those baseplates feel like a band-aid fix and look worse than just a good logo!

**Comment by Jupi007** [comment]
I really think you should take inspiration from the [manifest.json](https://web.dev/maskable-icon/) maskable icon stuff.
This would allow apps logo like spotify to be displayed without baseplate.

**Comment by Feichtmeier** [comment]
> I really think you should take inspiration from the [manifest.json](https://web.dev/maskable-icon/) maskable icon stuff. This would allow apps logo like the spotify one to be displayed as it, and leave the option for app publisher to require a baseplate.

when you say "you" do you mean ana or me?

**Comment by Feichtmeier** [comment]
Alright so the consense after this experiment in preview/candidate, is to remove the baseplate again?

**Comment by madsrh** [comment]
👍  I think adding the dark preview to the upload page is key in this education.

> ...educate the publisher on how to improve their logos...

This is a good solution, but this ofc won't help with the many icons for the debian packages - which is fine, just saying.

**Comment by anasereijo** [comment]
> Alright so the consensus after this experiment in preview/candidate, is to remove the baseplate again?

I'd say so! 
I will bring what @Jupi007 shared with the team, but if it takes a bit longer for them to do it, we can have the preview as I suggested as an MVP.
