### ISSUE TITLE
Search field becomes unfocused when its contents become empty.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#804]
It should stay focused even where there are no characters inside it.

https://user-images.githubusercontent.com/73116038/212779403-eb1b5164-2ed3-4c60-8ae7-497e7215a8e6.mp4

@Feichtmeier I can work on this as well

**Comment by madsrh** [comment]
This might be a separate, but if you're working on the focus state, it would be great if the user could just start typing when the app launched (or after clicking _Explore_), without having to click the searchbar first.

**Comment by whiskeyPeak** [comment]
Yeah that makes sense, will do!

**Comment by whiskeyPeak** [comment]
Ah, we probably also want to add this functionality to the installed page 😅
