### ISSUE TITLE
Explore header is gone from start page.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#811]
Before:

![Screenshot from 2023-01-18 02-30-00](https://user-images.githubusercontent.com/73116038/213067485-48a5da88-2599-4959-9d38-2956d9a3c58b.png)

Now:

![Screenshot from 2023-01-18 02-30-33](https://user-images.githubusercontent.com/73116038/213067501-7fbfdb3b-d13e-4f38-ad2c-711a1cf3fa4f.png)

Is this intended?

**Comment by Feichtmeier** [comment]
Yes this is intended and acked by the other designers
