### ISSUE TITLE
PackagePage: fill all infos with data or fallback string

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#852]
I recently found that `relasedAt` can be indeed received via appstream (sometimes).
The developer/publisher name can also be found sometimes.
We also got package kit left to eventually fill up more infos.
If neither works for getting the infos we should include a placeholder string like "Unknown" or "Not available".

@madsrh @anasereijo @Jupi007 any preference on the placeholder string?

**Comment by Jupi007** [comment]
`Unknown` seems a good one for me.
Imo, the info title and string should also use a disabled grey, to make this more obvious.

**Comment by madsrh** [comment]
I would prefer "Not available" but both are good 😊

**Comment by Jupi007** [comment]
I had think about both for a while, and it seems to me that `Not available` may sounds like "not available - for now". While `Unknown` seems obvious for me :)

We could also make it longer like: "This info is unknown", or something else.

**Comment by anasereijo** [comment]
Hey! To make sure I understand, this info won't be showing up because the publisher didn't get provide that info? Could they go back and update it? As in, is this reversible?

**Comment by madsrh** [comment]
> Hey! To make sure I understand, this info won't be showing up because the publisher didn't get provide that info? Could they go back and update it? 

It's only if no data is provided.

> I had think about both for a while, and it seems to me that Not available may sounds like "not available - for now". While Unknown seems obvious for me :)

I don't agree 😸 but let's go with _unknown_ for now since we already have a string in the translations ;)

**Comment by Jupi007** [comment]
> I don't agree smile_cat but we can go with unknown for now since we already have that string in the translations ;)

Honestly, I don't have any strong opinion on the string :D
Imo, if the data looks disabled, the string itself doesn't matter that much ;)

**Comment by anasereijo** [comment]
This might not be a good idea, but what about 'untitled' if it's reversible? 
I am okay with 'unknown' though! Also agree that needs to be displayed differently, disabled.
