### ISSUE TITLE
Package icons on App banners - improvements 

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#869]
### @Zoospora's proposal for the package icons on App banner:

As you know, we have been studying for some time now the different options regarding how to display the type of packages in the banners. 
These days we have been generating ideas and having different conversations with the design team, and we have come to a common proposal:

- Banners with two types of packages (snap being the main one, with its own description, main package name and ratings).
![image](https://user-images.githubusercontent.com/9861718/210821979-8fda30bd-242c-449e-b857-009afd059e75.png)

 - Banners with two types of packages (debian being the main one, with its own description, main package name and ratings).
![image](https://user-images.githubusercontent.com/9861718/210822028-2959b586-4543-45ff-b181-71745b6bcf12.png)

- Banners where the only package is from Snapcraft
![image](https://user-images.githubusercontent.com/9861718/210822093-682cf655-5204-4925-93f7-19ef5141ba92.png)
 
- Banners where the only package is from Debian. 
![image](https://user-images.githubusercontent.com/9861718/210821795-2e0f3d0a-e584-40f1-bf3c-dc3c543d4c6c.png)

Below, I attach screenshots related to the search results according to the filters applied in the store  (two for each type of filter):  
*Please omit the descriptions and content as it is only for illustration.

**ALL PACKAGES**
Shows snaps with two packages with Snapcraft being the main one and those with only one package (both Debian and Snapcraft).
<img width="771" alt="Screenshot 2023-01-25 at 15 33 40" src="https://user-images.githubusercontent.com/36884067/214605757-968d1276-c5e6-4d48-9df5-085c277311cb.png">

**SNAP PACKAGES** 
Displays all Snapcraft snaps 

<img width="782" alt="Screenshot 2023-01-25 at 15 35 07" src="https://user-images.githubusercontent.com/36884067/214606018-c6b42957-4577-415b-8cf7-82a30c70e254.png">

**DEBIAN PACKAGES** 
Displays all Debian snaps

<img width="783" alt="Screenshot 2023-01-25 at 15 35 29" src="https://user-images.githubusercontent.com/36884067/214606105-07164e3e-febe-412a-bd32-0b48fa719dbe.png">

This is our proposal. As I say, many members of the design team have been involved, and we feel that this way it is always clear (top right) who is the main package and bottom right the other existing options. Any constructive feedback is welcome 😊

Greetings and thanks!

_Originally posted by @Zoospora in https://github.com/ubuntu-flutter-community/software/discussions/634#discussioncomment-4602806_

**Comment by anasereijo** [comment]
@Feichtmeier created an issue for this, as I couldn't find one - feel free to delete if it's a duplicate.
This issue is focused just the package icons (position, colours, etc). Any questions let us know!

**Comment by Feichtmeier** [comment]
thanks

question:
"snap being the main one"
"debian being the main one"
What do you mean with this?

Opinion:
My eyes jump up and down with this new design looking too much on the package formats and my attention is now too much on the package format. What I like about the current design is that the package indication is not annoying but just informative and there when you need it and not attention grabbing

**Comment by madsrh** [comment]
> question:
"snap being the main one"
"debian being the main one"
What do you mean with this?

Main one means which package formats you land on when you click the appbanner

**Comment by Feichtmeier** [comment]
that's always snap first

**Comment by anasereijo** [comment]
> that's always snap first

not if you filter by deb only

**Comment by Feichtmeier** [comment]
haha ah now I understand :D 
well, if you filter by deb only, you also search only by deb, so there is only deb

**Comment by anasereijo** [comment]
If we all agree that it is not important, or even useful, to tell the user that the app is also available as a snap when they filter by debs (or vice versa) I am okay with displaying just the icon that it was filtered by. 

However, when we filter by 'all packages' I think it's essential to tell the user that the information they are seeing in the banner is about the snap (or deb if that's the only option). As we know, the publisher name and ratings can differ from snap to deb. And what we are trying to avoid is the user thinking that, for instance, the 5 stars rating is also about the deb, and then see it is a completely different rating. 

Hope this makes sense! Hard to explain in a comment.

**Comment by Feichtmeier** [comment]
Okay let's try this to indicate with colours but let's please not move the position and not use this very long sentence
I'll try a colour difference that is not so attention grabbing

**Comment by local-optimum** [comment]
I would like us to implement as the mockups suggested to review how that feels in the application. I think it's important to make it very clear which app-info is being displayed as the ratings/reviews could have a significant delta. Let's go with the mockups and then iterate from that basis. I can see that the text may be a little long in context but let's see how busy it looks.

**Comment by Feichtmeier** [comment]
@local-optimum 

> I think it's important to make it very clear which app-info is being displayed as the ratings/reviews could have a significant delta

this is correct.

However... the mockups suggest a design that puts way too much emphasis and visual attenion on the package format. The eyes immediately jump to the right. then to the bottom. It just looks weird and wrong

This should be enough and still does not create so much visual noise
![grafik](https://user-images.githubusercontent.com/15329494/214612311-56725f3b-683a-4a0b-9540-57c1dce82f92.png)

**Comment by Feichtmeier** [comment]
Additional to the eye-jumping-layout, and especially since the banners are inside a grid which changes their size there is also no space for this sentence, I think this is a dead end:
![grafik](https://user-images.githubusercontent.com/15329494/214613719-2c1d0974-80ae-4a3e-8f25-262795f8e35e.png)

**Comment by Feichtmeier** [comment]
I would go so far and say that the color alone is too much, look how noisy this looks in a full grid:

![grafik](https://user-images.githubusercontent.com/15329494/214616394-68191358-8e0d-422c-b4f6-46f9b7f5648a.png)
![grafik](https://user-images.githubusercontent.com/15329494/214616466-8b6457e5-7465-4a1d-b66c-57653a7d0e1d.png)

**Comment by anasereijo** [comment]
Here goes another proposal (this was actually done a while ago, but wasn't the preferred choice at that time);

This option might make it clearer that there are 2 separate packages, and will solve the issue on smaller windows.
However, this will take a bit more vertical space, and in the case of no 'other packages' available the white space at the bottom will be more evident (image 2).

Image 1 - Search result showing a mix of banners
![Group 95](https://user-images.githubusercontent.com/36884067/214807737-e008b257-7f53-4b08-bb41-476747a1101d.jpg)


Image 2 - Search result showing Banners with only 1 package type
I wonder how many use cases we will have for this though
![Group 106](https://user-images.githubusercontent.com/36884067/214807767-376c61be-d509-4220-abcb-54f907effb6f.jpg)

Thanks

**Comment by local-optimum** [comment]
I like this layout, I think we should try it. The separation is clear and it makes the 'also published as' fit more comfortably.

**Comment by Feichtmeier** [comment]
There is too much white space here
![grafik](https://user-images.githubusercontent.com/15329494/214824773-4e520bc1-6baf-4704-9256-a8928f61f23b.png)

Also the colored packages are too attention grabbing
I would prefer to stick to the current design. I think ana hit the nail on the spot with the first iteration of the grey watermarks. The last two proposals make the visual focus worse and the layout also looks uneven ( I am sorry, honestly )

**Comment by anasereijo** [comment]
Hey, let's keep it both grey and at the bottom (basically what we currently have). We will user test this and then act according to the data we collect from those interviews.
