### ISSUE TITLE
UpdatesPage: do not check details for every update

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#873]
Having 500 updates on a new lobstar VM.... this manual detail checking only to get the "critical/not critical" info for the icons does not scale.... this takes 5+ minutes
![image](https://user-images.githubusercontent.com/15329494/214601814-5778f621-ebc6-4ff9-8c39-ccbdf85462f4.png)

@d-loose @jpnurmi any smart :brain: idea how this could be made faster? Otherwise I fear we need to remove this detail check here:

(general information: we ask for a list of updates, we get that list of updates in a collection, then we iterate over this collection and ask package kit for every package to get more infos, we want this infos to check the category and urgency of an update, to then change the icon to "security-shield" or normal package)
https://github.com/ubuntu-flutter-community/software/blob/d2212e3e92f931016cafe3a2b2ce2df3dac9710d/lib/services/packagekit/package_service.dart#L309-L313

**Comment by d-loose** [comment]
[`GetDetails`](https://www.freedesktop.org/software/PackageKit/gtk-doc/Transaction.html#Transaction.GetDetails) accepts multiple package IDs, so I guess this can be done in a single query rather than one for each package.
