### ISSUE TITLE
Divider colour doesn't correlate to the correct theme.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#878]
That pesky issue keeps finding ways to make itself apparent :smile: 

![Screenshot from 2023-01-26 17-13-53](https://user-images.githubusercontent.com/73116038/214903673-ff0ccc1c-e2e3-417b-ad68-38683cb77783.png)

**Comment by Feichtmeier** [comment]
yep PR is already on, will be fixed with this see #879

**Comment by whiskeyPeak** [comment]
Good stuff :ok_hand:
