### ISSUE TITLE
Software centre takes a while to quit.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#880]
Tested in release mode.

https://user-images.githubusercontent.com/73116038/214905461-b8f2fb02-41f8-4394-a699-7ee8ef4b68a6.mp4

**Comment by Feichtmeier** [comment]
Duplicate of #868

**Comment by whiskeyPeak** [comment]
Ah, this issue shows #868 in action but isn't what I'm referring to here. There is a significant delay when pressing the close button. The other issue only relates to the grey box. :)

**Comment by Feichtmeier** [comment]
woops sorry

**Comment by Feichtmeier** [comment]
Can not confirm with the PR opened at least, can't switch back now :)


https://user-images.githubusercontent.com/15329494/214907649-f97a6fad-7f64-483b-9f65-65d0267f80af.mp4

**Comment by whiskeyPeak** [comment]
Yup can confirm, updating to 3.7 and with #879 the delay is gone :D

**Comment by Feichtmeier** [comment]
Cool! Yeah yesterday was a big release update :) We managed to update our yaru libs in time (-1 day :P )
