### ISSUE TITLE
Unmaximizing window triggers page transition

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#881]
Don't know if this issue is specific to Linux Mint...

https://user-images.githubusercontent.com/73116038/214915663-7a5a273e-df5a-42a2-a95d-896bc5dba5db.mp4

**Comment by Jupi007** [comment]
Is this screen record from a debug session?
Because there is an animation in the sidebar when resizing the window, and animations can be laggy in that situation.

Ofc if you are talking about this 😅

**Comment by whiskeyPeak** [comment]
The issue isn't with the sidebar animation but with the top part of the window flickering after the window is maximised. This issue is also reproducible in release mode.

**Comment by whiskeyPeak** [comment]
Here's a more clear example:

https://user-images.githubusercontent.com/73116038/214960555-ff870677-00a7-45cc-854b-d40be231622f.mp4

**Comment by Feichtmeier** [comment]
oh... page transitions

**Comment by Feichtmeier** [comment]
no those are indeed page transitions. triggered when maximizing/unmaximizing the window. which is pbrly not wanted

**Comment by Feichtmeier** [comment]
@whiskeyPeak could you check if you can reproduce this with the latest version of the yaru widgets snap ?

**Comment by Feichtmeier** [comment]
Could you open the issue in the other repo?

**Comment by whiskeyPeak** [comment]
Will do :+1:
