### ISSUE TITLE
Wrong translation procuces overflow on `AppPage`

### ISSUE THREAD

**Issue by d-loose** [ubuntu-flutter-community/software#885]
![image](https://user-images.githubusercontent.com/113362648/215059619-d08154f9-dae7-45a6-a121-3c71ee1ba601.png)

**Comment by Feichtmeier** [comment]
😮‍💨 jesus. this is the wrong string showing there :D who the hell changed it to this one

**Comment by d-loose** [comment]
Ah, I didn't even notice :D
It was part of the 'refresh' vs 'update' naming confusing #823

**Comment by Feichtmeier** [comment]
Aha and I approved 😆 
Also the "update" var shows "Aktualisierung" in German :) I think this one is correct in english though, which should be the reference

Yeah this is why changing translations is always a little bit risky 😄 But easy to fix

**Comment by d-loose** [comment]
L10n seems a bit messy in general - e.g. it's not immediately clear if the "update" variable refers to the noun or the verb.

**Comment by Feichtmeier** [comment]
Absolutely. In the settings app I was much more verbose with the names

singleUpdateButtonLabel ?
multiUpdateButtonLabel ?
processingLabel ?
checkForUpdatesLabel ?
