### ISSUE TITLE
Unnecessary mouse-over pop-ups in App details

### ISSUE THREAD

**Issue by local-optimum** [ubuntu-flutter-community/software#887]
![image](https://user-images.githubusercontent.com/55029393/215069313-ce898e44-453b-426a-a208-ac90b4262a42.png)

The app screens have unnecessary mouseover descriptions duplicating already visible info, this is the case on the Rating/Confinement/Version bar and in the App details bar most noticeable but may be present elsewhere. We should do a pass on which elements may benefit from additional detail on mouseover (eg license or confinement) and provide additional detail or just remove them throughout.

**Comment by madsrh** [comment]
Basically publisher names, version numbers and website urls can be very long and needs a tooltip. The others labels have tooltips for consistency. Wouldn't it seem odd if only some labels have a tooltip? I mean, for publisher, version and url the tooltip are there even is the string is very short. 
Unless you want to do something like: if string is longer than XX characters long, add tooltip 🤷‍♂️ 

The Inkscape version eg. is `1.2.2-b0a8486541-2022-12-01-cust..`. and isn't even fully displayed on the snapcraft website.

**Comment by Feichtmeier** [comment]
Yep this is the reason those strings can be ultra long
