### ISSUE TITLE
UpdatesPage improvements v3

### ISSUE THREAD

**Issue by local-optimum** [ubuntu-flutter-community/software#889]
To summarise recent discussions around the updates section:

- It would be good to categorise Debian updates to be more aligned with Update Manager's presentation with sections for Ubuntu Base OS, other updates and Ubuntu Pro updates (visible if enabled) maybe as independently expandable menus, we may also want to distinguish between universe/multiverse and other sources (I have no suggestions on that presentation however)
- We should review the iconography for updates such as the shield and Ubuntu logo for security updates @anasereijo and also create a new visualisation for Ubuntu Pro updates
- We are currently missing firmware updates in this list, is that possible to incorporate?

![image](https://user-images.githubusercontent.com/55029393/215071516-fbe26bdd-7f34-4781-91e2-fab443105753.png)

**Comment by Feichtmeier** [comment]
Sounds good 👍😊

On the firmware updater. We've discussed this in the beginning but I had the impression that @kenvandine wanted to keep the firmware update in it's own repo

**Comment by local-optimum** [comment]
Ah yes, scrap that last one ;)

**Comment by local-optimum** [comment]
Adding a further request to this thread. based on the current implementation I would propose that we leverage the "two button" approach to updates rather than the drop down select approach.

Good:
![image](https://user-images.githubusercontent.com/55029393/219495474-6c9475ac-cddf-488d-89e2-764219f978a5.png)

Bad:
![image](https://user-images.githubusercontent.com/55029393/219495503-f9f41963-0db6-4ab4-93b2-e055926f370c.png)

it makes it difficult for users to find the debs they need to upgrade or see the notifcation of available updates.

I propose we also use the same 'switch' view for the Search view as well. For consistency and the same logic.

**Comment by Feichtmeier** [comment]
Both good ideas. Let's do this

**Comment by Feichtmeier** [comment]
Since the whole page changed and you made a dedicated issue for the toggle button I close this
