### ISSUE TITLE
Sources configuration improvements 

### ISSUE THREAD

**Issue by local-optimum** [ubuntu-flutter-community/software#890]
**Before considering the below** @anasereijo it would be good to work with Elio around the relationship between Software & Updates and this screen, whilst we may ultimately want to consolidate some of the features of that app into the Ubuntu Software store, it may be preferable in the meantime to have the Sources link actually simply open the correct tab on Software & Updates rather than replicate it (with my below feedback then being saved for a future release)

- It would be good to include more helpful context on syntax for adding repos/ppas matching the software & updates style
![image](https://user-images.githubusercontent.com/55029393/215072427-42af2195-a5b0-48fd-84b6-e4d1e914fa08.png)

- The sources list could likely be reduced in font size for easier readability, compare with the same list in Software & Updates for the relative compactness

![image](https://user-images.githubusercontent.com/55029393/215072252-4e9fd7ea-b4bd-4479-8671-594999984ffe.png)

compared to:

![image](https://user-images.githubusercontent.com/55029393/215072292-5ce20fc0-b556-4fe1-902b-e4004f4a3199.png)

For consistency we should also right align the checkboxes.

- Software & Updates also includes the signing key in a separate section, we may want to consider incorporating this as well if possible.

**Comment by madsrh** [comment]
Releated to discussion in: https://github.com/ubuntu-flutter-community/software/discussions/843

**Comment by Feichtmeier** [comment]
@local-optimum please try to search if issues or discussions exist first. Thank you 👍

**Comment by anasereijo** [comment]
@Feichtmeier I copied/pasted Oliver's comment into the discussion. We can close this now
