### ISSUE TITLE
Pixel Overflow in Reviews and Ratings section.

### ISSUE THREAD

**Issue by whiskeyPeak** [ubuntu-flutter-community/software#898]
https://user-images.githubusercontent.com/73116038/215167838-0a22457b-987b-4009-a308-e64a3ddaa02c.mp4

**Comment by Feichtmeier** [comment]
I checked this before and this we've played too much with the window min width
We could either put this in expanded or increase window min width again

**Comment by whiskeyPeak** [comment]
It's worth noting that the reviewers name would probably be larger than "Unknown", so we could run into this issue again if we only change the minimum size of the window.

I think it makes more sense to separate the information over 2 lines.

**Comment by Feichtmeier** [comment]
You could either use expanded or wrap
But the main size of the window is too low also
