### ISSUE TITLE
Don't use full width on Settings page

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/software#904]
Current:
![image](https://user-images.githubusercontent.com/3986894/215333852-5b69a9a5-bb2d-464f-b31b-9c5a239b92b5.png)

Expected:
![image](https://user-images.githubusercontent.com/3986894/215333804-0ca56428-5ae3-495c-a26b-50ccd5e73676.png)

I had a look at how the update page is centered, but it was wayyyyyyyy to complicated for me 😄 Perhaps something for you @whiskeyPeak ?

**Comment by anasereijo** [comment]
Could we move the radio buttons to the left side? just before the text label? I think it will look much better and also easier to 'navigate

**Comment by Feichtmeier** [comment]
How about using custom theme tiles instead?

![grafik](https://user-images.githubusercontent.com/15329494/216561502-a35bcde6-16dc-49b6-83ee-593277f24e11.png)

**Comment by Feichtmeier** [comment]
normal
![grafik](https://user-images.githubusercontent.com/15329494/216565409-c0526568-b42d-472b-b503-6adfee893a37.png)

big window
![grafik](https://user-images.githubusercontent.com/15329494/216565766-ca2cd14a-4021-42b8-8b8b-fd1060faacd4.png)

**Comment by Feichtmeier** [comment]
The about link is opening the about dialog
![grafik](https://user-images.githubusercontent.com/15329494/216566347-1de824ee-b730-4b12-a418-6d7058c89843.png)

**Comment by Feichtmeier** [comment]
or with little icons? xD So cute!

![grafik](https://user-images.githubusercontent.com/15329494/216568509-779bded8-5eee-42c6-91a1-4bf373fe8f56.png)

**Comment by Jupi007** [comment]
I love your proposal with icons!

**Comment by Jupi007** [comment]
I love your proposal with icons!

And I had a thought: I think we should add this theme variant switcher as a yaru.dart widget, because it is something that a lot of apps will share.

**Comment by Feichtmeier** [comment]
Yes very useful

Maybe also add a fake title bar?

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/216590736-5e6ccf60-680e-4762-ad0a-9685c5cd1dfa.png)

?
