### ISSUE TITLE
Installed page - update icon/button styling

### ISSUE THREAD

**Issue by anasereijo** [ubuntu-flutter-community/software#913]
I initially thought that the arrow icon was to sort out by some order. Or am I missing out something here? 🤔
It would be nice to match what we do on 'Updates' - the use of a button with icon 'Check for updates'

https://user-images.githubusercontent.com/36884067/215575919-2a8a5271-edb8-4458-bafc-a80b0f7508a3.mp4

![WhatsApp Image 2023-01-30 at 19 17 12](https://user-images.githubusercontent.com/36884067/215576391-d2368e8c-2889-42cc-819c-c458d164d3a0.jpeg)

the tooltip says 'Update available' - can we change it or simply hide it as we do on Updates?

**Comment by Feichtmeier** [comment]
Wow 😳 this is a weird artefact I never touched again. Indeed this looks horrible 😂
I can do this like you proposed

(For debs it's really a different story though)

**Comment by Feichtmeier** [comment]
This button alone could question if we should unify updates and installed to library?

**Comment by anasereijo** [comment]
Actually, I had another look just now, and could see what happens when we have updates available. It will just display the packages with updates available, and clicking back on it will display all the installed apps again. Makes me wonder if we could merge updates and installed?

https://user-images.githubusercontent.com/36884067/215578875-b7fb649b-d97e-456a-8d51-576986957031.mov

**Comment by Feichtmeier** [comment]
> Actually, I had another look just now, and could see what happens when we have updates available. It will just display the packages with updates available, and clicking back on it will display all the installed apps again. Makes me wonder if we should merge updates and installed?
> 
> https://user-images.githubusercontent.com/36884067/215578875-b7fb649b-d97e-456a-8d51-576986957031.mov
> 
> 

👍 Yes, I think it's a very similar page. Why do people re-visit their installed apps? Either to update or to uninstall

**Comment by anasereijo** [comment]
> 👍 Yes, I think it's a very similar page. Why do people re-visit their installed apps? Either to update or to uninstall

Let's do it 🚀 shall we close this issue then and move on to the [Updates page discussion](https://github.com/ubuntu-flutter-community/software/discussions/357)? Or is it better to create a whole new discussion for this? WDYT?

**Comment by Feichtmeier** [comment]
As you like. We could either make this small fix now until the big merge is done or we could make a new issue "merge installed and updates" page as this is a clear instruction what to do for Dennis and me

**Comment by Feichtmeier** [comment]
let's make this as a small step fix first, we can do the merge in a separate issue->PR

**Comment by Feichtmeier** [comment]
@anasereijo WDYT think about this as the toggle button styling  in the "filter bar"?

![grafik](https://user-images.githubusercontent.com/15329494/216262281-b33d1e95-07e1-427f-a81d-9fcdbda3bc3b.png)
![grafik](https://user-images.githubusercontent.com/15329494/216262336-0dc45823-b2f9-4e37-b379-87b6337fd2d3.png)
![grafik](https://user-images.githubusercontent.com/15329494/216262393-4e7674d3-d146-47bb-89b5-62a095fcb80d.png)

**Comment by Feichtmeier** [comment]
ohhh nice 👍 

<img width="715" alt="grafik" src="https://user-images.githubusercontent.com/15329494/216284706-86801dac-8026-4ddb-bba5-abd51f965f88.png">

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/216318563-4fc427e4-1fd6-4fa2-90a3-2936be70fca5.png)

or

![grafik](https://user-images.githubusercontent.com/15329494/216319126-589089b9-67fe-4b18-8cbd-134cd8961a19.png)

or

![grafik](https://user-images.githubusercontent.com/15329494/216319238-697e3c24-9848-440f-8358-b2e38d84c2b0.png)

?

or?

**Comment by madsrh** [comment]
[Is this one](https://user-images.githubusercontent.com/15329494/216319238-697e3c24-9848-440f-8358-b2e38d84c2b0.png) using the accent color? If so, I don't think that's a good idea. 

Since this "Snaps with updates" is a filter, wouldn't it make sense to use a checkbox rather than a button?

**Comment by Jupi007** [comment]
You can use the filled version when the button is toggled on, and unfilled when off :)

And about the button itself, I don't like the accented version, both others are fine imo.
As suggested @madsrh, a checkbox could be a better solution.

**Comment by Feichtmeier** [comment]
I don't mind as long you are happy :D and I can close the issue 😆  will do

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/216409956-4d7e6638-16b8-46d0-8012-470e89291ccd.png)

"Aktualisierung verfügbar" = "Update available"
