### ISSUE TITLE
flutter Software crashes before even starting on Fedora 37

### ISSUE THREAD

**Issue by HPlinko** [ubuntu-flutter-community/software#959]
The Software Center won't start on Fedora 37, it would simply load in the app menu for a while and then a notification will pop up saying it's crashed. The stable version of the Snap Store works, however.

**Comment by Feichtmeier** [comment]
Thanks! Could you eventually start the app from the terminal and show the output here? I wonder what's happening

**Comment by HPlinko** [comment]
Sorry for replying late, I was out and wasn't able to bring my laptop with me.
When I run `snap-store` (which I installed from the `preview/edge` channel) the output goes like this:

`GDBus.Error:org.freedesktop.DBus.Error.NotSupported: Application does not handle command line arguments`

I hope this helps.

**Comment by Feichtmeier** [comment]
Thanks @HPlinko 
It's a not much but better than nothing :D 

We got a command line listener (https://github.com/ubuntu-flutter-community/gtk.dart).

@jpnurmi any idea what dbus interface bit might be different on Fedora that the command line listener might not work there?

**Comment by jpnurmi** [comment]
This sounds a lot like the same issue I had when I was switching the snap channels back and forth while testing the old and new stores. Reboot helped here...

**Comment by HPlinko** [comment]
@jpnurmi my thoughts exactly, but when I tried rebooting it didn't seem to work

**Comment by jpnurmi** [comment]
I suspect it's somehow related to the gapplication service files getting mixed up but I'm not able to reproduce the issue right now by deliberately installing/refreshing/removing/purging the different channels back and forth.

**Comment by jpnurmi** [comment]
This happens when the old store is left running in the background. `killall snaps-store` should help.
