### ISSUE TITLE
merge updates and installed

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#960]
Actually, I had another look just now, and could see what happens when we have updates available. It will just display the packages with updates available, and clicking back on it will display all the installed apps again. Makes me wonder if we should merge updates and installed?

https://user-images.githubusercontent.com/36884067/215578875-b7fb649b-d97e-456a-8d51-576986957031.mov

_Originally posted by @anasereijo in https://github.com/ubuntu-flutter-community/software/issues/913#issuecomment-1409232696_

**Comment by Feichtmeier** [comment]
@anasereijo @madsrh or anyone else

What would be the name and icon for installed/updates ?

"Library" ?

"Collection" ?

Choose an icon here:

https://ubuntu.github.io/yaru_icons.dart/

**Comment by soumyatheman** [comment]
Well merging it may be a wrong thing, as the update available option is there only for the snaps, it's better to remove the option from the installed apps list.
