### ISSUE TITLE
Dialog with app details cannot be closed with a mouse when scrolled down

### ISSUE THREAD

**Issue by oSoMoN** [ubuntu-flutter-community/software#99]
When inspecting the details of an app/package, if I expand the description section and scroll down, the cross icon at the top-right of the dialog scrolls out of view. I can't close the dialog anymore, unless I scroll back up (I know I can with the ESC key, but not with the mouse.

How about ensuring the close icon is always visible, and maybe also the header containing the icon, app name and short description?
The header could possibly shrink to a smaller version containing only the icon and app name when scrolling down, responsive UI style.

**Comment by Feichtmeier** [comment]
Hi @oSoMoN !
Sounds like a good idea!
