### ISSUE TITLE
CollectionModel: make _installedSnaps null at start

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/software#994]
For a glance "no snaps installed" is shown until the list is filled. 
Again I made the mistake to init a prop in the model.... 
We need null values to have a "waiting"-"but not yet checked if really empty" state in the UI

**Comment by Feichtmeier** [comment]
@jpnurmi do you know any linter rule for models to prevent this? :D I make the mistake so often

**Comment by jpnurmi** [comment]
I doubt it because it's not that black and white. "It depends" :)

Using a default value is also perfectly fine when it unambiguously describes the initial/loading/whatever state.

**Comment by jpnurmi** [comment]
For example, the initial value could be an enum:

```dart
enum MyState { loading, success, error }
```

Or even a union that can be beautifully used for pattern matching:

```dart
@freezed
class MyState {
  const factory MyState.loading();
  const factory MyState.value(T value);
  const factory MyState.error(Object error);
}
```

```dart
child: state.when(
  loading: () => CircularProgressIndicator(),
  value: (value) => Text(value)
  error: (error) => ErrorWidget(error),
),
```

Null is not inherently bad. Null-safety is not for getting rid of nulls but for making one aware of them. On the other hand, null is not necessarily always the best choice either. You can often get away without them. Neither of these cases above requires nulls. :)

**Comment by Feichtmeier** [comment]
Thanks!

Yes I have taken the "state"-enum approach for package updates.
I should to the same for snap updates some day :+1: 
Very easy to consume in any part of the code
