### ISSUE TITLE
CollectionPage: re-add PackageKitFilterButton

### ISSUE THREAD

**Issue by soumyatheman** [ubuntu-flutter-community/software#998]
Please list out all the packages installed in the collection list. The old one was much better regarding that. Also adding separate buttons just for filters like games, development feels too much. Please think about it, and please please don't remove even the smallest non-gui program from the collection list.

**Comment by Feichtmeier** [comment]
@soumyatheman ontopic, we could bring back the filter but then we need to be careful how to create a model for each row because there are A LOT of packages, sub deb packages  and deb dependencies on an average ubunt uinstalltion

The other part - nope sorry, whole teams loves the shortcuts :)

**Comment by soumyatheman** [comment]
The thing is, shortcut is good, we need actually need, but the position is not fit there, that should be placed inside the explore button, not with separate buttons

**Comment by Feichtmeier** [comment]
Yes, I understood your position. Yet we want it exactly where they are now, sorry.

**Comment by madsrh** [comment]
> The thing is, shortcut is good, we need actually need, but the position is not fit there, that should be placed inside the explore button, not with separate buttons

Nothing is decided, but the Explore page will undergo a makeover and we are considering some "shortcuts" for all the categories there - maybe. If that's any consolation to you. Still, this will not replace the sidebar buttons/shortcuts.

**Comment by soumyatheman** [comment]
Instead of filter shortcuts, why not add the sources list button there?

**Comment by Feichtmeier** [comment]
Please see the discussion on this topic and stop to push your opinion here, thank you:
https://github.com/ubuntu-flutter-community/software/discussions/358#discussioncomment-4804935
